Repository GoogleCloudPlatform/professional-services, pull requests merged in 2019-08, with the labels that each got.

#292 Update DataStudio dashboard and data source URLs.
  README.md
  examples/bigquery-audit-log/README.md
  examples/bigquery-billing-dashboard/README.md
  examples/bigquery-billing-dashboard/bigquery_billing_export.sql
Labels: cla: yes, size/M

#296 Fix issue with incorrect image filename generated in annotations
  tools/cloud-vision-utils/cloud_vision_utils/annotation.py
  tools/cloud-vision-utils/cloud_vision_utils/annotation_test.py
  tools/cloud-vision-utils/cloud_vision_utils/dataset.py
  tools/cloud-vision-utils/cloud_vision_utils/dataset_test.py
Labels: cla: yes, size/M

#238 Add tool to convert from GCE VM instance disks from Google-managed encryption to CMEK encryption
  README.md
  tools/gce-google-keys-to-cmek/README.md
  tools/gce-google-keys-to-cmek/main.py
  tools/gce-google-keys-to-cmek/requirements.txt
Labels: cla: yes, size/L

#276 BQ File Load Benchmark Iteration 1
  examples/bq_file_load_benchmark/README.md
  examples/bq_file_load_benchmark/__init__.py
  examples/bq_file_load_benchmark/benchmark_tools/__init__.py
  examples/bq_file_load_benchmark/benchmark_tools/avro_util.py
  examples/bq_file_load_benchmark/benchmark_tools/benchmark_result_util.py
  examples/bq_file_load_benchmark/benchmark_tools/benchmark_table.py
  examples/bq_file_load_benchmark/benchmark_tools/bucket_util.py
  examples/bq_file_load_benchmark/benchmark_tools/file_constants.py
  examples/bq_file_load_benchmark/benchmark_tools/file_generator.py
  examples/bq_file_load_benchmark/benchmark_tools/file_parameters.py
  examples/bq_file_load_benchmark/benchmark_tools/parquet_util.py
  examples/bq_file_load_benchmark/benchmark_tools/schema_creator.py
  examples/bq_file_load_benchmark/benchmark_tools/staging_table_generator.py
  examples/bq_file_load_benchmark/benchmark_tools/table_util.py
  examples/bq_file_load_benchmark/benchmark_tools/tables_processor.py
  examples/bq_file_load_benchmark/bq_file_load_benchmark.py
  examples/bq_file_load_benchmark/json_schemas/benchmark_table_schemas/100_STRING_10.json
  examples/bq_file_load_benchmark/json_schemas/benchmark_table_schemas/100_STRING_100.json
  examples/bq_file_load_benchmark/json_schemas/benchmark_table_schemas/100_STRING_1000.json
  examples/bq_file_load_benchmark/json_schemas/benchmark_table_schemas/10_STRING_90_NUMERIC_10.json
  examples/bq_file_load_benchmark/json_schemas/benchmark_table_schemas/10_STRING_90_NUMERIC_100.json
  examples/bq_file_load_benchmark/json_schemas/benchmark_table_schemas/10_STRING_90_NUMERIC_1000.json
  examples/bq_file_load_benchmark/json_schemas/benchmark_table_schemas/50_STRING_50_NUMERIC_10.json
  examples/bq_file_load_benchmark/json_schemas/benchmark_table_schemas/50_STRING_50_NUMERIC_100.json
  examples/bq_file_load_benchmark/json_schemas/benchmark_table_schemas/50_STRING_50_NUMERIC_1000.json
  examples/bq_file_load_benchmark/json_schemas/results_table_schema.json
  examples/bq_file_load_benchmark/queries/log_query.txt
  examples/bq_file_load_benchmark/requirements.txt
  examples/bq_file_load_benchmark/setup.py
  examples/bq_file_load_benchmark/tests/__init__.py
  examples/bq_file_load_benchmark/tests/conftest.py
  examples/bq_file_load_benchmark/tests/test_avro_util.py
  examples/bq_file_load_benchmark/tests/test_bucket_util.py
  examples/bq_file_load_benchmark/tests/test_data/fileType=csv/compression=none/numColumns=10/columnTypes=50_STRING_50_NUMERIC/numFiles=1/tableSize=10MB/file1.csv
  examples/bq_file_load_benchmark/tests/test_data/fileType=json/compression=none/numColumns=10/columnTypes=100_STRING/numFiles=1/tableSize=10MB/file1.json
  examples/bq_file_load_benchmark/tests/test_data/test.csv
  examples/bq_file_load_benchmark/tests/test_file_generator.py
  examples/bq_file_load_benchmark/tests/test_parquet_util.py
  examples/bq_file_load_benchmark/tests/test_schema_creator.py
  examples/bq_file_load_benchmark/tests/test_schemas/test_schema.json
  examples/bq_file_load_benchmark/tests/test_staging_table_generator.py
  examples/bq_file_load_benchmark/tests/test_table_util.py
  examples/dataflow-data-generator/bigquery-scripts/bq_table_resizer.py
Labels: cla: yes
