Repository GoogleCloudPlatform/professional-services, pull requests merged in 2019-10, with the labels that each got.

#324 Fix typo in README.md
  README.md
Labels: cla: yes, size/XS

#326 Update GAE requirements.txt to match Beam's versions.
  tools/asset-inventory/asset_inventory/pipeline_runner.py
  tools/asset-inventory/gae/requirements.txt
Labels: cla: yes, size/S

#334 Adding support for go in Cloudbuild CI testing
  cloudbuild/Dockerfile
  helpers/check_format.sh
  helpers/exclusion_list.txt
  helpers/format.sh
Labels: cla: yes, size/L

#336 Fixes for dataflow-data-generator and dataproc-persistent-history-server
  examples/dataflow-data-generator/README.md
  examples/dataflow-data-generator/data-generator-pipeline/data_generator_pipeline.py
  examples/dataflow-data-generator/requirements.txt
  examples/dataproc-persistent-history-server/terraform/history-server.tf
Labels: cla: yes, size/S

#332 Adding Table Validator
  tools/table_validator/README.md
  tools/table_validator/__init__.py
  tools/table_validator/config_only_table.json
  tools/table_validator/config_with_schema_output.json
  tools/table_validator/config_without_schema_output.json
  tools/table_validator/tests/__init__.py
  tools/table_validator/tests/test_validation.py
  tools/table_validator/utils/__init__.py
  tools/table_validator/utils/bigquery_utils.py
  tools/table_validator/validation.py
Labels: cla: no

#312 SLO Generator
  README.md
  tools/slo-generator/.gitignore
  tools/slo-generator/.pylintrc
  tools/slo-generator/Dockerfile
  tools/slo-generator/Makefile
  tools/slo-generator/README.md
  tools/slo-generator/cloudbuild.yaml
  tools/slo-generator/setup.py
  tools/slo-generator/slo_generator/TODO.txt
  tools/slo-generator/slo_generator/__init__.py
  tools/slo-generator/slo_generator/backends/__init__.py
  tools/slo-generator/slo_generator/backends/base.py
  tools/slo-generator/slo_generator/backends/elasticsearch.py
  tools/slo-generator/slo_generator/backends/prometheus.py
  tools/slo-generator/slo_generator/backends/stackdriver.py
  tools/slo-generator/slo_generator/cli.py
  tools/slo-generator/slo_generator/compute.py
  tools/slo-generator/slo_generator/exporters/__init__.py
  tools/slo-generator/slo_generator/exporters/base.py
  tools/slo-generator/slo_generator/exporters/bigquery.py
  tools/slo-generator/slo_generator/exporters/pubsub.py
  tools/slo-generator/slo_generator/exporters/stackdriver.py
  tools/slo-generator/slo_generator/utils.py
  tools/slo-generator/tests/unit/fixtures/bq_error.json
  tools/slo-generator/tests/unit/fixtures/error_budget_policy.json
  tools/slo-generator/tests/unit/fixtures/error_budget_policy.yaml
  tools/slo-generator/tests/unit/fixtures/migrate_format.py
  tools/slo-generator/tests/unit/fixtures/slo_exponential.json
  tools/slo-generator/tests/unit/fixtures/slo_exponential.yaml
  tools/slo-generator/tests/unit/fixtures/slo_linear.json
  tools/slo-generator/tests/unit/fixtures/slo_linear.yaml
  tools/slo-generator/tests/unit/fixtures/slo_report.json
  tools/slo-generator/tests/unit/fixtures/time_series_proto.json
  tools/slo-generator/tests/unit/test_cli.py
  tools/slo-generator/tests/unit/test_compute.py
  tools/slo-generator/tests/unit/test_utils.py
Labels: cla: yes, size/XXL

#340 Adding support for gts in make test
  cloudbuild/Dockerfile
  helpers/check_format.sh
  helpers/format.sh
Labels: cla: yes, size/M

#341 Adding CI checks for java formatting. Updating exclusion list.
  cloudbuild/Dockerfile
  helpers/check_format.sh
  helpers/exclusion_list.txt
  helpers/format.sh
Labels: cla: yes, size/M

#329 Example for Stackdriver absence alerts avoiding duplicates
  examples/alert-absence-dedup/.gitignore
  examples/alert-absence-dedup/README.md
  examples/alert-absence-dedup/alert_policy.json
  examples/alert-absence-dedup/go.mod
  examples/alert-absence-dedup/go.sum
  examples/alert-absence-dedup/images/alert_all_missing.png
  examples/alert-absence-dedup/images/alert_one_missing.png
  examples/alert-absence-dedup/images/alert_two_missing.png
  examples/alert-absence-dedup/images/metrics_explorer.png
  examples/alert-absence-dedup/main.go
  examples/alert-absence-dedup/policy_doc.md
Labels: cla: yes, size/L

#311 add GCP org hierarchy viewer (gcpohv)
  README.md
  tools/gcp-org-hierarchy-viewer/README.md
  tools/gcp-org-hierarchy-viewer/gcpohv_cli.py
  tools/gcp-org-hierarchy-viewer/setup.py
Labels: cla: yes, size/L
