Repository GoogleCloudPlatform/professional-services, pull requests merged in 2019-12, with the labels that each got.

#364 [Kafka2Avro example] Update to the latest versions of SBT, Beam, Scio and others
  examples/dataflow-scala-kafka2avro/README.md
  examples/dataflow-scala-kafka2avro/build.sbt
  examples/dataflow-scala-kafka2avro/project/build.properties
  examples/dataflow-scala-kafka2avro/project/plugins.sbt
  examples/dataflow-scala-kafka2avro/src/main/scala/com/google/cloud/pso/kafka2avro/Kafka2Avro.scala
  examples/dataflow-scala-kafka2avro/src/main/scala/com/google/cloud/pso/kafka2avro/Object2Kafka.scala
Labels: cla: yes, size/S

#357 G Suite Grant Analyzer.
  tools/gsuite-grant-analyzer/README.md
  tools/gsuite-grant-analyzer/gsuite_grant_analyzer/__init__.py
  tools/gsuite-grant-analyzer/gsuite_grant_analyzer/analyze.py
  tools/gsuite-grant-analyzer/gsuite_grant_analyzer/bigquery_helpers.py
  tools/gsuite-grant-analyzer/gsuite_grant_analyzer/google_api_helpers.py
  tools/gsuite-grant-analyzer/setup.py
  tools/gsuite-grant-analyzer/tests/__init__.py
Labels: cla: yes

#368 Fix broken links in SLO generator README
  tools/slo-generator/README.md
Labels: cla: yes, size/XS

#369 fix the errors caused by integer index
  tools/ml-auto-eda/ml_eda/analysis/quantitative_analyzer.py
  tools/ml-auto-eda/ml_eda/analysis/utils.py
  tools/ml-auto-eda/ml_eda/reporting/utils.py
Labels: cla: yes, size/S

#372 Added changes for Accelerate
  examples/cryptorealtime/README.md
  examples/cryptorealtime/frontend/templates/streamingvisjs.html
  examples/cryptorealtime/terraform-setup/startup.tpl
Labels: cla: yes, size/S

#362 New tool to generate GCS Bucket Insights
  README.md
  helpers/exclusion_list.txt
  tools/gcs-usage-recommender/README.md
  tools/gcs-usage-recommender/audit_log_query.sql
  tools/gcs-usage-recommender/images/audit_log_UI.png
  tools/gcs-usage-recommender/images/output_schema.png
  tools/gcs-usage-recommender/images/stackdriver_create_advanced_filter.png
  tools/gcs-usage-recommender/images/stackdriver_create_exclusion.png
  tools/gcs-usage-recommender/images/stackdriver_enter_filter_query.png
  tools/gcs-usage-recommender/images/stackdriver_exclusion_tab.png
  tools/gcs-usage-recommender/python/backfill.py
  tools/gcs-usage-recommender/requirements.txt
  tools/gcs-usage-recommender/schema.json
Labels: cla: yes

#352 due to the change of visjs url, change to another cdn of visjs
  examples/cryptorealtime/frontend/templates/streamingvisjs.html
Labels: cla: yes, size/XS

#379 Update to work in both Python2 and Python3
  examples/dataflow-python-examples/dataflow_python_examples/data_enrichment.py
Labels: cla: yes, size/XS

#371 Added append argument to use WRITE_APPEND option
  tools/bqpipeline/bqpipeline/bqpipeline.py
Labels: cla: yes, size/XS
