Repository GoogleCloudPlatform/professional-services, pull requests merged in 2019-09, with the labels that each got.

#300 add Dataproc Edge Node scripts
  tools/dataproc-edge-node/1_create-image.sh
  tools/dataproc-edge-node/2_launch-edgenode.sh
  tools/dataproc-edge-node/README.md
  tools/dataproc-edge-node/edgenode_env
  tools/dataproc-edge-node/image_env
  tools/dataproc-edge-node/util/config-files
  tools/dataproc-edge-node/util/configure.sh
  tools/dataproc-edge-node/util/create-templates.sh
  tools/dataproc-edge-node/util/disable-services.sh
  tools/dataproc-edge-node/util/edge-node-startup-script.sh
  tools/dataproc-edge-node/util/google-edgenode-configure.service
  tools/dataproc-edge-node/util/setup_edge_node.sh
Labels: cla: yes, size/XL

#306 Gce usage log
  README.md
  tools/gce-usage-log/README.md
  tools/gce-usage-log/dependency-reduced-pom.xml
  tools/gce-usage-log/gce_usage_view.sql
  tools/gce-usage-log/images/gce-usage-log.png
  tools/gce-usage-log/images/query-results.png
  tools/gce-usage-log/images/view-schema.png
  tools/gce-usage-log/pom.xml
  tools/gce-usage-log/src/main/java/com/google/cloud/pso/gceusage/Main.java
  tools/gce-usage-log/src/main/java/com/google/cloud/pso/gceusage/initialvminventory/InitialInstanceInventoryRow.java
  tools/gce-usage-log/src/main/java/com/google/cloud/pso/gceusage/initialvminventory/InitialVMInventory.java
  tools/gce-usage-log/src/main/java/com/google/cloud/pso/gceusage/services/BQHelper.java
  tools/gce-usage-log/src/main/java/com/google/cloud/pso/gceusage/services/CloudResourceManagerService.java
  tools/gce-usage-log/src/main/java/com/google/cloud/pso/gceusage/services/ComputeService.java
  tools/gce-usage-log/src/main/java/com/google/cloud/pso/gceusage/services/EmptyRowCollection.java
  tools/gce-usage-log/src/main/java/com/google/cloud/pso/gceusage/services/GCEHelper.java
  tools/gce-usage-log/src/test/java/com/google/cloud/pso/gceusage/initialvminventory/InitialVMInventoryTest.java
  tools/gce-usage-log/src/test/resources/schema/initial_inventory_schema.json
Labels: cla: yes

#309 auto detect source and fix transform bug
  examples/cloudml-sklearn-pipeline/trainer/task.py
  examples/cloudml-sklearn-pipeline/trainer/util/transform_utils.py
Labels: cla: yes, size/S

#321 Asset duplicate fix
  tools/asset-inventory/asset_inventory/bigquery_schema.py
  tools/asset-inventory/requirements.txt
  tools/asset-inventory/setup.cfg
  tools/asset-inventory/setup.py
  tools/asset-inventory/tests/test_api_schema.py
  tools/asset-inventory/tests/test_bigquery_schema.py
Labels: cla: no, size/M

#315 Adding CI testing for tools - linting python files with yapf
  Makefile
  cloudbuild.yaml
  cloudbuild/Dockerfile
  helpers/check_format.sh
  helpers/exclusion_list.txt
  helpers/format.sh
Labels: cla: yes, size/L

#323 Update GSuite exporter version
  tools/gsuite-exporter/setup.py
Labels: cla: yes, size/XS

#322 Adding support for python3 and python3 files in make test helper script.
  cloudbuild/Dockerfile
  helpers/check_format.sh
  helpers/format.sh
Labels: cla: yes, size/M
