Repository GoogleCloudPlatform/professional-services, pull requests merged in 2019-07, with the labels that each got.

#266 add a solution template for training and serving music recommendations on caip
  README.md
  examples/cloudml-collaborative-filtering/.gitignore
  examples/cloudml-collaborative-filtering/README.md
  examples/cloudml-collaborative-filtering/bin/_common.sh
  examples/cloudml-collaborative-filtering/bin/run.predict.cloud.sh
  examples/cloudml-collaborative-filtering/bin/run.predict.local.sh
  examples/cloudml-collaborative-filtering/bin/run.preprocess.cloud.sh
  examples/cloudml-collaborative-filtering/bin/run.preprocess.local.sh
  examples/cloudml-collaborative-filtering/bin/run.serve.cloud.sh
  examples/cloudml-collaborative-filtering/bin/run.serve.local.sh
  examples/cloudml-collaborative-filtering/bin/run.train.cloud.sh
  examples/cloudml-collaborative-filtering/bin/run.train.local.sh
  examples/cloudml-collaborative-filtering/bin/run.train.tune.sh
  examples/cloudml-collaborative-filtering/constants/__init__.py
  examples/cloudml-collaborative-filtering/constants/constants.py
  examples/cloudml-collaborative-filtering/preprocessing/__init__.py
  examples/cloudml-collaborative-filtering/preprocessing/config.example.ini
  examples/cloudml-collaborative-filtering/preprocessing/preprocess.py
  examples/cloudml-collaborative-filtering/preprocessing/query.py
  examples/cloudml-collaborative-filtering/preprocessing/run_preprocess.py
  examples/cloudml-collaborative-filtering/requirements.txt
  examples/cloudml-collaborative-filtering/serving/__init__.py
  examples/cloudml-collaborative-filtering/serving/make_prediction.py
  examples/cloudml-collaborative-filtering/serving/test.json
  examples/cloudml-collaborative-filtering/setup.py
  examples/cloudml-collaborative-filtering/trainer/__init__.py
  examples/cloudml-collaborative-filtering/trainer/hptuning_config.yaml
  examples/cloudml-collaborative-filtering/trainer/inputs.py
  examples/cloudml-collaborative-filtering/trainer/model.py
  examples/cloudml-collaborative-filtering/trainer/task.py
  examples/cloudml-collaborative-filtering/trainer/utils.py
Labels: cla: yes

#140 Tool to detect recency of terraform remote module tags
  tools/terraform-module-update-scanner/README.md
  tools/terraform-module-update-scanner/check-terraform-module-versions
  tools/terraform-module-update-scanner/tests/test.sh
  tools/terraform-module-update-scanner/tests/tests.tf
Labels: cla: yes, size/L

#280 bigquery-query-plan-exporter: export jobs from all users
  tools/bigquery-query-plan-exporter/bqutil/bqexplain.py
Labels: cla: yes, size/XS

#277 Added ThrottlingStrategy and TimeDomain.timer value to DataflowThrottling library
  tools/apachebeam-throttling/README.md
  tools/apachebeam-throttling/img/dataflow-throttling-dag.png
  tools/apachebeam-throttling/pom.xml
  tools/apachebeam-throttling/src/main/java/com/google/cloud/pso/beamthrottling/DynamicThrottlingTransform.java
  tools/apachebeam-throttling/src/main/java/com/google/cloud/pso/beamthrottling/HttpServerThrottling.java
  tools/apachebeam-throttling/src/main/java/com/google/cloud/pso/beamthrottling/ThrottlingException.java
  tools/apachebeam-throttling/src/main/java/com/google/cloud/pso/beamthrottling/ThrottlingOrchestration.java
  tools/apachebeam-throttling/src/main/java/com/google/cloud/pso/beamthrottling/ThrottlingStrategy.java
  tools/apachebeam-throttling/src/main/java/com/google/cloud/pso/beamthrottling/package-info.java
  tools/apachebeam-throttling/src/test/java/com/google/cloud/pso/beamthrottling/ThrottlingOrchestrationTest.java
Labels: cla: yes

#283 Apache Beam Client Throttling readme file update
  README.md
Labels: cla: yes, size/XS

#267 Adds Python CICD example using Cloud Builder and CSR
  .gitignore
  README.md
  examples/python-cicd-with-cloudbuilder/.pylintrc
  examples/python-cicd-with-cloudbuilder/README.md
  examples/python-cicd-with-cloudbuilder/cloudbuild.yaml
  examples/python-cicd-with-cloudbuilder/my_module/__init__.py
  examples/python-cicd-with-cloudbuilder/my_module/my_module.py
  examples/python-cicd-with-cloudbuilder/python-cloud-builder/Dockerfile
  examples/python-cicd-with-cloudbuilder/python-cloud-builder/cloudbuild.yaml
  examples/python-cicd-with-cloudbuilder/requirements.txt
  examples/python-cicd-with-cloudbuilder/tests/test_my_module.py
Labels: cla: yes, size/XL

#285 Update README.md
  examples/cloudml-energy-price-forecasting/README.md
Labels: cla: yes, size/S

#286 Create requirements.txt
  examples/cloudml-energy-price-forecasting/data_preparation/requirements.txt
Labels: cla: yes, size/XS

#288 Update tools/kunksap query with correct export labeling and removing beta gcloud commands
  tools/kunskap/README.md
  tools/kunskap/cud_sud_attribution_query.sql
Labels: cla: yes, size/M

#259 Update/dataproc persistent logging
  examples/dataproc-persistent-history-server/cluster_templates/ephemeral-cluster.yaml
  examples/dataproc-persistent-history-server/cluster_templates/history-server.yaml
  examples/dataproc-persistent-history-server/init_actions/disable_history_servers.sh
  examples/dataproc-persistent-history-server/terraform/firewall.tf
  examples/dataproc-persistent-history-server/terraform/history-server.tf
  examples/dataproc-persistent-history-server/terraform/long-running-cluster.tf
  examples/dataproc-persistent-history-server/terraform/terraform.tfvars
  examples/dataproc-persistent-history-server/terraform/variables.tf
  examples/dataproc-persistent-history-server/workflow_templates/spark_mr_workflow_template.yaml
Labels: cla: yes, size/XXL

#270 Add GCF VM Delete Event Handler Example
  .gitignore
  README.md
  examples/gcf-pubsub-vm-delete-event-handler/.coveragerc
  examples/gcf-pubsub-vm-delete-event-handler/.gcloudignore
  examples/gcf-pubsub-vm-delete-event-handler/.gitignore
  examples/gcf-pubsub-vm-delete-event-handler/DEVELOPER.md
  examples/gcf-pubsub-vm-delete-event-handler/README.md
  examples/gcf-pubsub-vm-delete-event-handler/env.yaml.sample
  examples/gcf-pubsub-vm-delete-event-handler/img/example_logs.png
  examples/gcf-pubsub-vm-delete-event-handler/main.py
  examples/gcf-pubsub-vm-delete-event-handler/requirements-dev.txt
  examples/gcf-pubsub-vm-delete-event-handler/requirements.txt
  examples/gcf-pubsub-vm-delete-event-handler/tests/conftest.py
  examples/gcf-pubsub-vm-delete-event-handler/tests/data/compute-v1.json
  examples/gcf-pubsub-vm-delete-event-handler/tests/data/dns-change.json
  examples/gcf-pubsub-vm-delete-event-handler/tests/data/dns-records.json
  examples/gcf-pubsub-vm-delete-event-handler/tests/data/dns-v1.json
  examples/gcf-pubsub-vm-delete-event-handler/tests/data/instance-no-network.json
  examples/gcf-pubsub-vm-delete-event-handler/tests/data/instance.json
  examples/gcf-pubsub-vm-delete-event-handler/tests/data/rrsets-empty.json
  examples/gcf-pubsub-vm-delete-event-handler/tests/data/rrsets.json
  examples/gcf-pubsub-vm-delete-event-handler/tests/data/trigger-complete.json
  examples/gcf-pubsub-vm-delete-event-handler/tests/data/trigger-event-done.json
  examples/gcf-pubsub-vm-delete-event-handler/tests/data/trigger-event.json
  examples/gcf-pubsub-vm-delete-event-handler/tests/helpers.py
  examples/gcf-pubsub-vm-delete-event-handler/tests/main_test.py
  tools/kunskap/tests/main_test.py
Labels: cla: yes

#275 Survival Analysis for Churn Prediction
  README.md
  examples/cloudml-churn-prediction/README.md
  examples/cloudml-churn-prediction/preprocessor/__init__.py
  examples/cloudml-churn-prediction/preprocessor/preprocessor/__init__.py
  examples/cloudml-churn-prediction/preprocessor/preprocessor/features.py
  examples/cloudml-churn-prediction/preprocessor/preprocessor/preprocess.py
  examples/cloudml-churn-prediction/preprocessor/preprocessor/preprocess_test.py
  examples/cloudml-churn-prediction/preprocessor/preprocessor/query.py
  examples/cloudml-churn-prediction/preprocessor/run_preprocessing.py
  examples/cloudml-churn-prediction/preprocessor/setup.py
  examples/cloudml-churn-prediction/requirements.txt
  examples/cloudml-churn-prediction/trainer/config.yaml
  examples/cloudml-churn-prediction/trainer/hptuning_config.yaml
  examples/cloudml-churn-prediction/trainer/setup.py
  examples/cloudml-churn-prediction/trainer/trainer/__init__.py
  examples/cloudml-churn-prediction/trainer/trainer/input_util.py
  examples/cloudml-churn-prediction/trainer/trainer/metadata.py
  examples/cloudml-churn-prediction/trainer/trainer/metrics.py
  examples/cloudml-churn-prediction/trainer/trainer/model.py
  examples/cloudml-churn-prediction/trainer/trainer/task.py
Labels: cla: yes

#287 Add tools/cloud-vision-utils.
  README.md
  tools/cloud-vision-utils/.gitignore
  tools/cloud-vision-utils/README.md
  tools/cloud-vision-utils/cloud_vision_utils/__init__.py
  tools/cloud-vision-utils/cloud_vision_utils/annotation.py
  tools/cloud-vision-utils/cloud_vision_utils/annotation_test.py
  tools/cloud-vision-utils/cloud_vision_utils/cli.py
  tools/cloud-vision-utils/cloud_vision_utils/constants.py
  tools/cloud-vision-utils/cloud_vision_utils/dataset.py
  tools/cloud-vision-utils/cloud_vision_utils/dataset_test.py
  tools/cloud-vision-utils/cloud_vision_utils/test_data.xml
  tools/cloud-vision-utils/requirements-dev.txt
  tools/cloud-vision-utils/setup.py
Labels: cla: yes

#291 Optimize SUD allocation and update GEO for new SKU regions
  tools/kunskap/README.md
  tools/kunskap/cud_sud_attribution_query.sql
Labels: cla: yes, size/S

#290 updates to dataflow python examples
  examples/dataflow-python-examples/README.md
  examples/dataflow-python-examples/dataflow_python_examples/data_ingestion.py
  examples/dataflow-python-examples/dataflow_python_examples/data_ingestion_configurable.py
  examples/dataflow-python-examples/dataflow_python_examples/datastore_schema_import.py
  examples/dataflow-python-examples/requirements.txt
Labels: cla: yes, size/L
