Repository GoogleCloudPlatform/professional-services, pull requests merged in 2019-06, with the labels that each got.

#256 Add scikit-learn training and serving pipeline
  README.md
  examples/cloudml-sklearn-pipeline/README.md
  examples/cloudml-sklearn-pipeline/config/config.yaml
  examples/cloudml-sklearn-pipeline/config/hptuning_config.yaml
  examples/cloudml-sklearn-pipeline/predictor.py
  examples/cloudml-sklearn-pipeline/requirements.txt
  examples/cloudml-sklearn-pipeline/sample_data/sample_json.txt
  examples/cloudml-sklearn-pipeline/sample_data/sample_list.txt
  examples/cloudml-sklearn-pipeline/scripts/deploy.sh
  examples/cloudml-sklearn-pipeline/scripts/predict.py
  examples/cloudml-sklearn-pipeline/scripts/predict.sh
  examples/cloudml-sklearn-pipeline/scripts/train.sh
  examples/cloudml-sklearn-pipeline/setup.py
  examples/cloudml-sklearn-pipeline/sklearn.png
  examples/cloudml-sklearn-pipeline/trainer/__init__.py
  examples/cloudml-sklearn-pipeline/trainer/constants.py
  examples/cloudml-sklearn-pipeline/trainer/metadata.py
  examples/cloudml-sklearn-pipeline/trainer/model.py
  examples/cloudml-sklearn-pipeline/trainer/task.py
  examples/cloudml-sklearn-pipeline/trainer/transform_config.py
  examples/cloudml-sklearn-pipeline/trainer/util/__init__.py
  examples/cloudml-sklearn-pipeline/trainer/util/preprocess_utils.py
  examples/cloudml-sklearn-pipeline/trainer/util/transform_utils.py
  examples/cloudml-sklearn-pipeline/trainer/util/utils.py
Labels: cla: yes

#226 Minor fixes and update of angular library versions
  .gitignore
  tools/bq-visualizer/README.md
  tools/bq-visualizer/package-lock.json
  tools/bq-visualizer/package.json
  tools/bq-visualizer/src/app/app-routing.module.spec.ts
  tools/bq-visualizer/src/app/app-routing.module.ts
  tools/bq-visualizer/src/app/app.component.css
  tools/bq-visualizer/src/app/app.component.html
  tools/bq-visualizer/src/app/app.component.spec.ts
  tools/bq-visualizer/src/app/app.component.ts
  tools/bq-visualizer/src/app/app.module.ts
  tools/bq-visualizer/src/app/big-query.service.spec.ts
  tools/bq-visualizer/src/app/big-query.service.ts
  tools/bq-visualizer/src/app/bq_job.ts
  tools/bq-visualizer/src/app/bq_query_plan.spec.ts
  tools/bq-visualizer/src/app/bq_query_plan.ts
  tools/bq-visualizer/src/app/dagre-layout.service.spec.ts
  tools/bq-visualizer/src/app/dagre-layout.service.ts
  tools/bq-visualizer/src/app/google-auth.service.spec.ts
  tools/bq-visualizer/src/app/google-auth.service.ts
  tools/bq-visualizer/src/app/job/job.component.css
  tools/bq-visualizer/src/app/job/job.component.html
  tools/bq-visualizer/src/app/job/job.component.spec.ts
  tools/bq-visualizer/src/app/job/job.component.ts
  tools/bq-visualizer/src/app/log-display/log-display.component.spec.ts
  tools/bq-visualizer/src/app/log-display/log-display.component.ts
  tools/bq-visualizer/src/app/log.service.spec.ts
  tools/bq-visualizer/src/app/log.service.ts
  tools/bq-visualizer/src/app/log_message.ts
  tools/bq-visualizer/src/app/plan-side-display/plan-side-display.component.spec.ts
  tools/bq-visualizer/src/app/plan-side-display/plan-side-display.component.ts
  tools/bq-visualizer/src/app/plan-status-card/plan-status-card.component.spec.ts
  tools/bq-visualizer/src/app/plan-status-card/plan-status-card.component.ts
  tools/bq-visualizer/src/app/projects/projects.component.spec.ts
  tools/bq-visualizer/src/app/projects/projects.component.ts
  tools/bq-visualizer/src/app/query-plan.service.spec.ts
  tools/bq-visualizer/src/app/query-plan.service.ts
  tools/bq-visualizer/src/app/rest_interfaces.ts
  tools/bq-visualizer/src/app/stage-details/stage-details.component.spec.ts
  tools/bq-visualizer/src/app/stage-details/stage-details.component.ts
  tools/bq-visualizer/src/app/step-details/step-details.component.spec.ts
  tools/bq-visualizer/src/app/step-details/step-details.component.ts
  tools/bq-visualizer/src/app/timing-display/timing-display.component.css
  tools/bq-visualizer/src/app/timing-display/timing-display.component.spec.ts
  tools/bq-visualizer/src/app/timing-display/timing-display.component.ts
  tools/bq-visualizer/src/app/vis-display/vis-display.component.css
  tools/bq-visualizer/src/app/vis-display/vis-display.component.spec.ts
  tools/bq-visualizer/src/app/vis-display/vis-display.component.ts
  tools/bq-visualizer/src/app/vis-graph.ts
  tools/bq-visualizer/src/environments/environment.dparrish.ts
  tools/bq-visualizer/src/environments/environment.prod.ts
  tools/bq-visualizer/src/environments/environment.test.ts
  tools/bq-visualizer/src/environments/environment.ts
  tools/bq-visualizer/src/index.html
  tools/bq-visualizer/src/main.ts
  tools/bq-visualizer/src/polyfills.ts
  tools/bq-visualizer/src/test.ts
  tools/bq-visualizer/src/tsconfig.app.json
  tools/bq-visualizer/src/tsconfig.spec.json
Labels: cla: yes

#225 Dataflow Throttling: Client-side throttling in Dataflow
  README.md
  tools/dataflow-throttling/README.md
  tools/dataflow-throttling/img/dataflow-throttling-dag.png
  tools/dataflow-throttling/pom.xml
  tools/dataflow-throttling/src/main/java/com/google/cloud/pso/dataflowthrottling/DynamicThrottlingTransform.java
  tools/dataflow-throttling/src/main/java/com/google/cloud/pso/dataflowthrottling/HttpServerThrottling.java
  tools/dataflow-throttling/src/main/java/com/google/cloud/pso/dataflowthrottling/ThrottlingException.java
  tools/dataflow-throttling/src/main/java/com/google/cloud/pso/dataflowthrottling/ThrottlingOrchestration.java
  tools/dataflow-throttling/src/main/java/com/google/cloud/pso/dataflowthrottling/package-info.java
  tools/dataflow-throttling/src/test/java/com/google/cloud/pso/dataflowthrottling/ThrottlingOrchestrationTest.java
Labels: cla: yes

#262 fix some typo issues
  examples/kubeflow-fairing-example/Fairing_XGBoost.ipynb
Labels: cla: yes, size/S

#265 Update requirements.txt of cloudml-sentiment-analysis
  examples/cloudml-sentiment-analysis/README.md
  examples/cloudml-sentiment-analysis/requirements.txt
Labels: cla: yes, size/XS

#268 Add reminder to submit bug to Eng Council
  .github/pull_request_template.md
Labels: cla: yes, size/XS

#269 Add Python 3 support to gce-quota-sync.py
  tools/gce-quota-sync/gce-quota-sync.py
Labels: cla: yes, size/XS

#274 [dataflow-streaming-benchmark] Add some more env vars for launching the pipeline.
  examples/dataflow-streaming-benchmark/README.md
Labels: cla: yes, size/S
