Repository GoogleCloudPlatform/professional-services, pull requests merged in 2019-02, with the labels that each got.

#161 Add marketing ML model for banking notebook
  README.md
  examples/cloudml-bank-marketing/README.md
  examples/cloudml-bank-marketing/bank_marketing_classification_model.ipynb
Labels: cla: yes, size/XXL

#153 BigQuery Audit Log Dashboard Pull Request
  examples/bigquery-audit-log/README.md
  examples/bigquery-audit-log/bigquery_audit_log.sql
  examples/bigquery-audit-log/docs/copy_jobs.md
  examples/bigquery-audit-log/docs/extract_jobs.md
  examples/bigquery-audit-log/docs/load_jobs.md
  examples/bigquery-audit-log/docs/overall_usage.md
  examples/bigquery-audit-log/docs/query_jobs.md
  examples/bigquery-audit-log/images/copy_jobs/Image1.png
  examples/bigquery-audit-log/images/copy_jobs/Image2.png
  examples/bigquery-audit-log/images/copy_jobs/Image3.png
  examples/bigquery-audit-log/images/copy_jobs/Image4.png
  examples/bigquery-audit-log/images/copy_jobs/Image5.png
  examples/bigquery-audit-log/images/copy_jobs/Image6.png
  examples/bigquery-audit-log/images/copy_jobs/Image7.png
  examples/bigquery-audit-log/images/copy_jobs/Image8.png
  examples/bigquery-audit-log/images/extract_jobs/Image1.png
  examples/bigquery-audit-log/images/extract_jobs/Image2.png
  examples/bigquery-audit-log/images/extract_jobs/Image3.png
  examples/bigquery-audit-log/images/extract_jobs/Image4.png
  examples/bigquery-audit-log/images/extract_jobs/Image5.png
  examples/bigquery-audit-log/images/extract_jobs/Image6.png
  examples/bigquery-audit-log/images/extract_jobs/Image7.png
  examples/bigquery-audit-log/images/extract_jobs/Image8.png
  examples/bigquery-audit-log/images/load_jobs/Image1.png
  examples/bigquery-audit-log/images/load_jobs/Image2.png
  examples/bigquery-audit-log/images/load_jobs/Image3.png
  examples/bigquery-audit-log/images/load_jobs/Image4.png
  examples/bigquery-audit-log/images/load_jobs/Image5.png
  examples/bigquery-audit-log/images/load_jobs/Image6.png
  examples/bigquery-audit-log/images/load_jobs/Image7.png
  examples/bigquery-audit-log/images/load_jobs/Image8.png
  examples/bigquery-audit-log/images/overall_usage/Image1.png
  examples/bigquery-audit-log/images/overall_usage/Image2.png
  examples/bigquery-audit-log/images/overall_usage/Image3.png
  examples/bigquery-audit-log/images/overall_usage/Image4.png
  examples/bigquery-audit-log/images/overall_usage/Image5.png
  examples/bigquery-audit-log/images/overall_usage/Image6.png
  examples/bigquery-audit-log/images/overall_usage/Image7.png
  examples/bigquery-audit-log/images/overall_usage/Image8.png
  examples/bigquery-audit-log/images/query_jobs/Image1.png
  examples/bigquery-audit-log/images/query_jobs/Image2.png
  examples/bigquery-audit-log/images/query_jobs/Image3.png
  examples/bigquery-audit-log/images/query_jobs/Image4.png
  examples/bigquery-audit-log/images/query_jobs/Image5.png
Labels: cla: yes, size/L

#138 Kunskap
  README.md
  tools/kunskap/.gcloudignore
  tools/kunskap/README.md
  tools/kunskap/config.py
  tools/kunskap/cud_sud_attribution_query.sql
  tools/kunskap/main.py
  tools/kunskap/requirements.txt
  tools/kunskap/tests/main_test.py
Labels: cla: yes

#163 Update dlp example code path in README
  README.md
  examples/dlp/cloud_function_example/README.md
  examples/dlp/cloud_function_example/cloud_function/__init__.py
  examples/dlp/cloud_function_example/cloud_function/main.py
  examples/dlp/cloud_function_example/cloud_function/requirements.txt
  examples/dlp/cloud_function_example/img/stackdriver_cloud_function_log.png
  examples/dlp/cloud_function_example/img/stackdriver_log_img.png
  examples/dlp/cloud_function_example/tests/cloud_function_test.py
Labels: cla: yes

#174 Exit whenever credentials have expired.
  tools/gke-billing-export/README.md
  tools/gke-billing-export/billing.go
  tools/gke-billing-export/deploy.yaml
Labels: cla: yes, size/S

#173 Update README.md
  README.md
Labels: cla: yes, size/XS

#175 Fix test & alphabetical ordering in README
  README.md
  tools/kunskap/README.md
  tools/kunskap/tests/main_test.py
Labels: cla: yes, size/XXL

#171 Add example to synchronize group membership with BigQuery
  examples/bigquery-row-access-groups/.gcloudignore
  examples/bigquery-row-access-groups/.gitignore
  examples/bigquery-row-access-groups/auth_util.py
  examples/bigquery-row-access-groups/create_service_account.sh
  examples/bigquery-row-access-groups/deploy_function.sh
  examples/bigquery-row-access-groups/group_sync.py
  examples/bigquery-row-access-groups/group_sync_test.py
  examples/bigquery-row-access-groups/main.py
  examples/bigquery-row-access-groups/requirements.txt
  examples/bigquery-row-access-groups/schedule_job.sh
Labels: cla: yes, size/L

#143 Dataflow example to read from Kafka and persist in Avro -- in Scala
  README.md
  examples/dataflow-scala-kafka2avro/.gitignore
  examples/dataflow-scala-kafka2avro/README.md
  examples/dataflow-scala-kafka2avro/build.sbt
  examples/dataflow-scala-kafka2avro/cloudbuild.yaml
  examples/dataflow-scala-kafka2avro/project/build.properties
  examples/dataflow-scala-kafka2avro/project/plugins.sbt
  examples/dataflow-scala-kafka2avro/src/main/resources/application.conf
  examples/dataflow-scala-kafka2avro/src/main/resources/log4j.properties
  examples/dataflow-scala-kafka2avro/src/main/scala/com/google/cloud/pso/kafka2avro/Kafka2Avro.scala
  examples/dataflow-scala-kafka2avro/src/main/scala/com/google/cloud/pso/kafka2avro/Object2Kafka.scala
  examples/dataflow-scala-kafka2avro/src/main/scala/com/google/cloud/pso/kafka2avro/config/Kafka2AvroConfig.scala
  examples/dataflow-scala-kafka2avro/src/main/scala/com/google/cloud/pso/kafka2avro/demo/MyDemoType.scala
  examples/dataflow-scala-kafka2avro/src/main/scala/com/google/cloud/pso/kafka2avro/utils/Kafka2AvroUtils.scala
  examples/dataflow-scala-kafka2avro/src/test/scala/com/google/cloud/pso/kafka2avro/Kafka2AvroSpec.scala
  examples/dataflow-scala-kafka2avro/src/test/scala/com/google/cloud/pso/kafka2avro/Object2KafkaSpec.scala
  examples/dataflow-scala-kafka2avro/src/test/scala/com/google/cloud/pso/kafka2avro/utils/Kafka2AvroUtilsSpec.scala
Labels: cla: yes

#184 Add README to BigQuery Group Synch example.
  README.md
  examples/bigquery-row-access-groups/README.md
  examples/bigquery-row-access-groups/schedule_job.sh
Labels: cla: yes

#186 Data prep tool for Machine Learning - replaces PR #179
  tools/ml-dataprep/README.md
  tools/ml-dataprep/ml_dataprep/__init__.py
  tools/ml-dataprep/ml_dataprep/bqclient.py
  tools/ml-dataprep/ml_dataprep/config.py
  tools/ml-dataprep/ml_dataprep/dataprep.py
  tools/ml-dataprep/ml_dataprep/exceptions.py
  tools/ml-dataprep/ml_dataprep/queries.py
  tools/ml-dataprep/ml_dataprep/runner.py
  tools/ml-dataprep/requirements.txt
  tools/ml-dataprep/run.sh
  tools/ml-dataprep/setup.py
  tools/ml-dataprep/tests/__init__.py
  tools/ml-dataprep/tests/bqclient_test.py
  tools/ml-dataprep/tests/dataprep_test.py
Labels: cla: yes, size/XXL

#183 Add an example to deploy Redis cluster on GKE.
  README.md
  examples/redis-cluster-gke/README.md
  examples/redis-cluster-gke/configmaps/redis-conf.yaml
  examples/redis-cluster-gke/configmaps/redis-expect.yaml
  examples/redis-cluster-gke/redis-cache.yaml
  examples/redis-cluster-gke/redis-create-cluster.yaml
Labels: cla: yes, size/L

#188 Add link to blog post for BigQuery Row Level Group Access example.
  examples/bigquery-row-access-groups/README.md
Labels: cla: yes, size/XS

#190 Fix for issue #85
  examples/iot-nirvana/startup_install_java8.sh
Labels: cla: yes, size/XS

#177 Kunskap
  README.md
  tools/kunskap/README.md
  tools/kunskap/config.py
  tools/kunskap/cud_sud_attribution_query.sql
  tools/kunskap/main.py
  tools/kunskap/tests/main_test.py
Labels: cla: yes, size/L

#195 fixes #192 - fixed link to working example, and img link for animation
  tools/gcp-arch-viz/README.md
Labels: cla: yes, size/XS

#181 add bigquery-query-plan-exporter
  tools/bigquery-query-plan-exporter/.gitignore
  tools/bigquery-query-plan-exporter/README.md
  tools/bigquery-query-plan-exporter/bqutil/__init__.py
  tools/bigquery-query-plan-exporter/bqutil/bqexplain.py
  tools/bigquery-query-plan-exporter/requirements.txt
  tools/bigquery-query-plan-exporter/setup.py
Labels: cla: yes

#176 Update DataStudio dashboard and datasource public links, and added derived fields info.
  examples/bigquery-audit-log/README.md
  examples/bigquery-audit-log/bigquery_audit_log.sql
  examples/bigquery-audit-log/images/datastudio-source-all.png
Labels: cla: yes

#139 Feature/hive bigquery
  README.md
  tools/hive-bigquery/README.md
  tools/hive-bigquery/architectural_diagram.png
  tools/hive-bigquery/bigquery_component.py
  tools/hive-bigquery/bigquery_table.py
  tools/hive-bigquery/bigquery_table_model.py
  tools/hive-bigquery/config.json
  tools/hive-bigquery/custom_exceptions.py
  tools/hive-bigquery/database_component.py
  tools/hive-bigquery/gcp_service.py
  tools/hive-bigquery/gcs_storage_component.py
  tools/hive-bigquery/hive_component.py
  tools/hive-bigquery/hive_table.py
  tools/hive-bigquery/hive_table_model.py
  tools/hive-bigquery/hive_to_bigquery.py
  tools/hive-bigquery/init_script.py
  tools/hive-bigquery/kms_component.py
  tools/hive-bigquery/mysql_component.py
  tools/hive-bigquery/prerequisites/create_sql_instance.sh
  tools/hive-bigquery/prerequisites/prerequisites.sh
  tools/hive-bigquery/prerequisites/requirements.txt
  tools/hive-bigquery/prerequisites/tracking_table.sql
  tools/hive-bigquery/properties_reader.py
  tools/hive-bigquery/resource_validator.py
  tools/hive-bigquery/test/create_hive_tables.sql
  tools/hive-bigquery/test/generate_data.py
  tools/hive-bigquery/test_config.json
  tools/hive-bigquery/utilities.py
  tools/hive-bigquery/validations.csv
Labels: cla: no
