Repository GoogleCloudPlatform/professional-services, pull requests merged in 2019-11, with the labels that each got.

#346 New Tool: auto exploratory data analysis and feature recommendation
  README.md
  helpers/exclusion_list.txt
  tools/ml-auto-eda/README.md
  tools/ml-auto-eda/metadata.ini
  tools/ml-auto-eda/ml_eda/__init__.py
  tools/ml-auto-eda/ml_eda/analysis/__init__.py
  tools/ml-auto-eda/ml_eda/analysis/descriptive_analysis.py
  tools/ml-auto-eda/ml_eda/analysis/descriptive_analyzer.py
  tools/ml-auto-eda/ml_eda/analysis/qualitative_analysis.py
  tools/ml-auto-eda/ml_eda/analysis/qualitative_analyzer.py
  tools/ml-auto-eda/ml_eda/analysis/quantitative_analysis.py
  tools/ml-auto-eda/ml_eda/analysis/quantitative_analyzer.py
  tools/ml-auto-eda/ml_eda/analysis/utils.py
  tools/ml-auto-eda/ml_eda/constants.py
  tools/ml-auto-eda/ml_eda/datasources/__init__.py
  tools/ml-auto-eda/ml_eda/datasources/bigquery/__init__.py
  tools/ml-auto-eda/ml_eda/datasources/bigquery/bq_client.py
  tools/ml-auto-eda/ml_eda/metadata/__init__.py
  tools/ml-auto-eda/ml_eda/metadata/metadata_definition.py
  tools/ml-auto-eda/ml_eda/metadata/metadata_loader.py
  tools/ml-auto-eda/ml_eda/metadata/proto/run_metadata.proto
  tools/ml-auto-eda/ml_eda/metadata/run_metadata_pb2.py
  tools/ml-auto-eda/ml_eda/orchestration/__init__.py
  tools/ml-auto-eda/ml_eda/orchestration/analysis_run.py
  tools/ml-auto-eda/ml_eda/orchestration/analysis_tracker.py
  tools/ml-auto-eda/ml_eda/preprocessing/__init__.py
  tools/ml-auto-eda/ml_eda/preprocessing/analysis_query/__init__.py
  tools/ml-auto-eda/ml_eda/preprocessing/analysis_query/query_builder.py
  tools/ml-auto-eda/ml_eda/preprocessing/analysis_query/query_templates.py
  tools/ml-auto-eda/ml_eda/preprocessing/preprocessor_factory.py
  tools/ml-auto-eda/ml_eda/preprocessing/preprocessors/__init__.py
  tools/ml-auto-eda/ml_eda/preprocessing/preprocessors/bigquery/__init__.py
  tools/ml-auto-eda/ml_eda/preprocessing/preprocessors/bigquery/bq_preprocessor.py
  tools/ml-auto-eda/ml_eda/preprocessing/preprocessors/data_preprocessor.py
  tools/ml-auto-eda/ml_eda/preprocessing/preprocessors/dataflow/__init__.py
  tools/ml-auto-eda/ml_eda/reporting/__init__.py
  tools/ml-auto-eda/ml_eda/reporting/figure/Correlation_heatmap.png
  tools/ml-auto-eda/ml_eda/reporting/figure/Information-Gain_heatmap.png
  tools/ml-auto-eda/ml_eda/reporting/figure/age_histogram.png
  tools/ml-auto-eda/ml_eda/reporting/figure/education_histogram.png
  tools/ml-auto-eda/ml_eda/reporting/figure/functional_weight_histogram.png
  tools/ml-auto-eda/ml_eda/reporting/figure/hours_per_week_histogram.png
  tools/ml-auto-eda/ml_eda/reporting/figure/marital_status_histogram.png
  tools/ml-auto-eda/ml_eda/reporting/figure/native_country_histogram.png
  tools/ml-auto-eda/ml_eda/reporting/figure/race_histogram.png
  tools/ml-auto-eda/ml_eda/reporting/recommendation.py
  tools/ml-auto-eda/ml_eda/reporting/report_generator.py
  tools/ml-auto-eda/ml_eda/reporting/template.py
  tools/ml-auto-eda/ml_eda/reporting/templates/report_classification.md
  tools/ml-auto-eda/ml_eda/reporting/templates/report_eda.md
  tools/ml-auto-eda/ml_eda/reporting/templates/report_regression.md
  tools/ml-auto-eda/ml_eda/reporting/templates/report_snapshot.png
  tools/ml-auto-eda/ml_eda/reporting/utils.py
  tools/ml-auto-eda/ml_eda/reporting/visualization.py
  tools/ml-auto-eda/ml_eda/runner.py
  tools/ml-auto-eda/requirements.txt
  tools/ml-auto-eda/run.sh
  tools/ml-auto-eda/setup.py
  tools/ml-auto-eda/tests/__init__.py
  tools/ml-auto-eda/tests/quantitative_analyzer_test.py
Labels: cla: yes

#349 better documentation for slo-generator
  tools/slo-generator/README.md
Labels: cla: yes, size/S

#339 Adding Time-Series Info to GCE usage logs
  README.md
  examples/ml-audio-content-profiling/app/angular/README.md
  tools/gce-usage-log/README.md
  tools/gce-usage-log/gce_interval_view.sql
  tools/gce-usage-log/gce_usage_view.sql
  tools/gce-usage-log/images/base-view-schema.png
  tools/gce-usage-log/images/copy-data-source.png
  tools/gce-usage-log/images/copy-report.png
  tools/gce-usage-log/images/custom-interval-dimension.png
  tools/gce-usage-log/images/gce-usage-log.png
  tools/gce-usage-log/images/interval-query-results.png
  tools/gce-usage-log/images/interval-view-schema.png
  tools/gce-usage-log/images/time-series-graph.png
  tools/gce-usage-log/images/usage-graph.png
Labels: cla: yes

#335 Add GCS Fixity Function
  examples/gcs-fixity-function/Makefile
  examples/gcs-fixity-function/README.md
  examples/gcs-fixity-function/deploy.sh
  examples/gcs-fixity-function/docs/images/cloud-shell.png
  examples/gcs-fixity-function/docs/images/process-diagram.png
  examples/gcs-fixity-function/docs/setup.md
  examples/gcs-fixity-function/prepare.sh
  examples/gcs-fixity-function/scripts/current-manifest.sql
  examples/gcs-fixity-function/scripts/file-operations.sql
  examples/gcs-fixity-function/scripts/schema.json
  examples/gcs-fixity-function/src/main.py
  examples/gcs-fixity-function/src/requirements.txt
Labels: cla: yes

#344 Never convert properties to a timestamp.
  tools/asset-inventory/README.md
  tools/asset-inventory/asset_inventory/api_schema.py
  tools/asset-inventory/asset_inventory/bigquery_schema.py
  tools/asset-inventory/asset_inventory/import_pipeline.py
  tools/asset-inventory/gae/requirements.txt
  tools/asset-inventory/setup.py
  tools/asset-inventory/tests/test_bigquery_schema.py
Labels: cla: yes, size/M

#350 Hotfix to change fileSize type from int to float
  examples/bq_file_load_benchmark/README.md
  examples/bq_file_load_benchmark/benchmark_tools/benchmark_result_util.py
  examples/bq_file_load_benchmark/bq_file_load_benchmark.py
  examples/bq_file_load_benchmark/json_schemas/results_table_schema.json
Labels: cla: yes, size/M

#351 fixing README for composer http request example
  examples/cloud-composer-examples/composer_http_post_example/README.md
Labels: cla: yes, size/M

#361 SLO Generator - Always cast threshold_bucket to int
  tools/slo-generator/setup.py
  tools/slo-generator/slo_generator/backends/stackdriver.py
Labels: cla: yes, size/XS
