Repository GoogleCloudPlatform/professional-services, pull requests merged in 2019-01, with the labels that each got.

#141 Apps Script Netblock Monitor Tool
  README.md
  tools/netblock-monitor/README.md
  tools/netblock-monitor/code.js
Labels: cla: yes

#146 usage shouldn't be a metric label
  tools/gce-quota-sync/gce-quota-sync.py
Labels: cla: yes

#147 Update solution
  examples/cloudml-energy-price-forecasting/data_preparation/data_prep.py
  examples/cloudml-energy-price-forecasting/kubeflow_pipeline/Energy Price Forecasting Pipeline.ipynb
Labels: cla: yes

#149 Choosing a better protocol
  examples/cloudml-energy-price-forecasting/data_preparation/data_prep.py
  examples/cloudml-energy-price-forecasting/kubeflow_pipeline/Energy Price Forecasting Pipeline.ipynb
Labels: cla: yes

#150 Updated README.md with Cloud Connect published article.
  tools/netblock-monitor/README.md
Labels: cla: yes

#159 end2end demo system
  README.md
  examples/e2e-home-appliance-status-monitoring/README.md
  examples/e2e-home-appliance-status-monitoring/ml/config.yaml
  examples/e2e-home-appliance-status-monitoring/ml/hptuning_config.yaml
  examples/e2e-home-appliance-status-monitoring/ml/setup.py
  examples/e2e-home-appliance-status-monitoring/ml/start.sh
  examples/e2e-home-appliance-status-monitoring/ml/trainer/__init__.py
  examples/e2e-home-appliance-status-monitoring/ml/trainer/model.py
  examples/e2e-home-appliance-status-monitoring/ml/trainer/task.py
  examples/e2e-home-appliance-status-monitoring/ml/trainer/util.py
  examples/e2e-home-appliance-status-monitoring/notebook/EnergyDisaggregationDemo_Client.ipynb
  examples/e2e-home-appliance-status-monitoring/notebook/EnergyDisaggregationDemo_View.ipynb
  examples/e2e-home-appliance-status-monitoring/notebook/EnergyDisaggregationEDA.ipynb
  examples/e2e-home-appliance-status-monitoring/notebook/requirements.txt
  examples/e2e-home-appliance-status-monitoring/server/app.yaml
  examples/e2e-home-appliance-status-monitoring/server/appengine_config.py
  examples/e2e-home-appliance-status-monitoring/server/main.py
  examples/e2e-home-appliance-status-monitoring/server/requirements.txt
Labels: cla: yes, size/XXL

#145 Kubeflow Pipelines sentiment analysis on New York Times Archive API data
  README.md
  examples/kubeflow-pipelines-sentiment-analysis/.gitignore
  examples/kubeflow-pipelines-sentiment-analysis/README.md
  examples/kubeflow-pipelines-sentiment-analysis/pipeline/build_sentiment_analysis.py
  examples/kubeflow-pipelines-sentiment-analysis/sentiment-analysis/Dockerfile
  examples/kubeflow-pipelines-sentiment-analysis/sentiment-analysis/build_image.sh
  examples/kubeflow-pipelines-sentiment-analysis/sentiment-analysis/pom.xml
  examples/kubeflow-pipelines-sentiment-analysis/sentiment-analysis/src/license/license-header-style.xml
  examples/kubeflow-pipelines-sentiment-analysis/sentiment-analysis/src/license/license-header.txt
  examples/kubeflow-pipelines-sentiment-analysis/sentiment-analysis/src/main/java/com/google/cloud/pso/common/Doc.java
  examples/kubeflow-pipelines-sentiment-analysis/sentiment-analysis/src/main/java/com/google/cloud/pso/pipelines/SentimentAnalysis.java
  examples/kubeflow-pipelines-sentiment-analysis/sentiment-analysis/src/test/java/com/google/cloud/pso/pipelines/SentimentAnalysisTest.java
Labels: cla: yes

#164 Fixing stackdriver_exporter to work with python 3+
  tools/gsuite-exporter/gsuite_exporter/exporters/stackdriver_exporter.py
Labels: cla: yes, size/XS
