Repository GoogleCloudPlatform/professional-services, pull requests merged in 2019-03, with the labels that each got.

#198 BQ Table Resizer Fix for target_gb Method
  examples/dataflow-data-generator/bigquery-scripts/bq_table_resizer.py
  examples/dataflow-data-generator/bigquery-scripts/tests/test_bq_table_resizer.py
Labels: cla: yes, size/M

#205 Add helper for sorting the Readme
  Makefile
  README.md
  helpers/sort_lists.py
Labels: cla: yes, size/M

#208 Fixed formmating issue when displaying latency on the backend
  examples/cryptorealtime/README.md
  examples/cryptorealtime/TERRAFORM-README.md
  examples/cryptorealtime/frontend/app.py
  examples/cryptorealtime/terraform-setup/main.tf
  examples/cryptorealtime/terraform-setup/terraform.tfvars
Labels: cla: yes, size/XS

#182 add bqpipeline
  tools/bqpipeline/.gitignore
  tools/bqpipeline/README.md
  tools/bqpipeline/bqpipeline/__init__.py
  tools/bqpipeline/bqpipeline/bqpipeline.py
  tools/bqpipeline/bqpipeline/tests/__init__.py
  tools/bqpipeline/bqpipeline/tests/test_bqpipeline.py
  tools/bqpipeline/example/example.py
  tools/bqpipeline/example/q1.sql
  tools/bqpipeline/example/q2.sql
  tools/bqpipeline/example/q3.sql
  tools/bqpipeline/example/q4.sql
  tools/bqpipeline/requirements.txt
  tools/bqpipeline/setup.py
Labels: cla: yes

#213 Three new features for the Asset Inventory tool.
  tools/asset-inventory/MANIFEST.in
  tools/asset-inventory/asset_inventory/api_schema.py
  tools/asset-inventory/asset_inventory/bigquery_schema.py
  tools/asset-inventory/asset_inventory/cai_to_api.py
  tools/asset-inventory/asset_inventory/cai_to_api_properties.json
  tools/asset-inventory/asset_inventory/import_pipeline.py
  tools/asset-inventory/asset_inventory/import_pipeline_metadata
  tools/asset-inventory/asset_inventory/main.py
  tools/asset-inventory/gae/config.yaml
  tools/asset-inventory/setup.py
  tools/asset-inventory/tests/test_api_schema.py
  tools/asset-inventory/tests/test_bigquery_schema.py
  tools/asset-inventory/tests/test_cai_to_resource_mapping.py
  tools/asset-inventory/tests/test_import_pipeline.py
Labels: cla: yes, size/XXL

#215 Three new features for the Asset Inventory tool. (#213)
  tools/asset-inventory/MANIFEST.in
  tools/asset-inventory/asset_inventory/api_schema.py
  tools/asset-inventory/asset_inventory/bigquery_schema.py
  tools/asset-inventory/asset_inventory/cai_to_api.py
  tools/asset-inventory/asset_inventory/cai_to_api_properties.json
  tools/asset-inventory/asset_inventory/import_pipeline.py
  tools/asset-inventory/asset_inventory/import_pipeline_metadata
  tools/asset-inventory/asset_inventory/main.py
  tools/asset-inventory/gae/config.yaml
  tools/asset-inventory/setup.py
  tools/asset-inventory/tests/test_api_schema.py
  tools/asset-inventory/tests/test_bigquery_schema.py
  tools/asset-inventory/tests/test_cai_to_resource_mapping.py
  tools/asset-inventory/tests/test_import_pipeline.py
Labels: cla: yes, size/XXL

#216 Update checkstyle version to fix security vunerability
  examples/dataflow-streaming-benchmark/pom.xml
Labels: cla: yes, size/XS

#204 Updates to the notebook so it can be used in ML notebooks
  examples/cloudml-bank-marketing/bank_marketing_classification_model.ipynb
Labels: cla: yes

#219 mwallman gce to adminsdk
  LICENSE
  README.md
  examples/gce-to-adminsdk/README.md
  examples/gce-to-adminsdk/main.py
  examples/gce-to-adminsdk/pics/admin_role.png
  examples/gce-to-adminsdk/pics/api_access.png
  examples/gce-to-adminsdk/pics/permission_model.png
  examples/gce-to-adminsdk/requirements.txt
Labels: cla: yes

#220 Add "Open in Cloud Shell" shortcut
  README.md
Labels: cla: yes, size/XS

#221 Feature/hive-bigquery Changed static filenames
  tools/hive-bigquery/bigquery_table_model.py
  tools/hive-bigquery/gcs_storage_component.py
  tools/hive-bigquery/hive_component.py
Labels: cla: yes, size/S

#214 add an example to realize uploading files directly to GCS by using Signed URL
  README.md
  examples/direct-upload-to-gcs/README.md
  examples/direct-upload-to-gcs/appengine/app.yaml
  examples/direct-upload-to-gcs/appengine/go.mod
  examples/direct-upload-to-gcs/appengine/go.sum
  examples/direct-upload-to-gcs/appengine/main.go
  examples/direct-upload-to-gcs/architecture.png
  examples/direct-upload-to-gcs/function/go.mod
  examples/direct-upload-to-gcs/function/go.sum
  examples/direct-upload-to-gcs/function/main.go
Labels: cla: yes

#201 Feature/dataproc persistent logging
  README.md
  examples/dataproc-persistent-history-server/.gitignore
  examples/dataproc-persistent-history-server/README.md
  examples/dataproc-persistent-history-server/cluster_templates/ephemeral-cluster.yaml
  examples/dataproc-persistent-history-server/cluster_templates/history-server.yaml
  examples/dataproc-persistent-history-server/img/persistent-history-arch.png
  examples/dataproc-persistent-history-server/init_actions/disable_history_servers.sh
  examples/dataproc-persistent-history-server/terraform/firewall.tf
  examples/dataproc-persistent-history-server/terraform/history-bucket.tf
  examples/dataproc-persistent-history-server/terraform/history-server.tf
  examples/dataproc-persistent-history-server/terraform/long-running-cluster.tf
  examples/dataproc-persistent-history-server/terraform/network.tf
  examples/dataproc-persistent-history-server/terraform/service-account.tf
  examples/dataproc-persistent-history-server/terraform/terraform.tfvars
  examples/dataproc-persistent-history-server/terraform/variables.tf
  examples/dataproc-persistent-history-server/workflow_templates/spark_mr_workflow_template.yaml
Labels: cla: yes
