Repository GoogleCloudPlatform/professional-services, pull requests merged in 2019-04, with the labels that each got.

#222 Documentation Update
  tools/asset-inventory/README.md
  tools/asset-inventory/gae/config.yaml
  tools/asset-inventory/tests/test_api_schema.py
Labels: cla: yes, size/XXL

#210 Cloudera GCS connector Parcel: copy current folder content into the parcel
  tools/cloudera-parcel-gcsconnector/create_parcel.sh
Labels: cla: yes, size/XS

#180 Add offset for querying Admin API
  tools/gsuite-exporter/README.md
  tools/gsuite-exporter/gsuite_exporter/cli.py
  tools/gsuite-exporter/gsuite_exporter/collectors/reports.py
  tools/gsuite-exporter/gsuite_exporter/exporters/base.py
  tools/gsuite-exporter/gsuite_exporter/exporters/stackdriver_exporter.py
  tools/gsuite-exporter/setup.py
Labels: cla: yes, size/L

#227 Formatting changes.
  tools/asset-inventory/README.md
Labels: cla: yes, size/L

#224 Add Agile Machine Learning API
  README.md
  tools/agile-machine-learning-api/README.md
  tools/agile-machine-learning-api/codes/config.yaml
  tools/agile-machine-learning-api/codes/setup.py
  tools/agile-machine-learning-api/codes/trainer/__init__.py
  tools/agile-machine-learning-api/codes/trainer/input_pipeline_dask.py
  tools/agile-machine-learning-api/codes/trainer/launch_demo.py
  tools/agile-machine-learning-api/codes/trainer/models.py
  tools/agile-machine-learning-api/codes/trainer/utils/__init__.py
  tools/agile-machine-learning-api/codes/trainer/utils/custom_utils_fns.py
  tools/agile-machine-learning-api/codes/trainer/utils/metric_utils.py
  tools/agile-machine-learning-api/codes/trainer/utils/optimizer_utils.py
  tools/agile-machine-learning-api/config/developer.yaml
  tools/agile-machine-learning-api/data/census_train.csv
  tools/agile-machine-learning-api/data/iris_formatted.csv
  tools/agile-machine-learning-api/data/iris_names.txt
  tools/agile-machine-learning-api/deploy.py
  tools/agile-machine-learning-api/lime_utils.py
  tools/agile-machine-learning-api/main.py
  tools/agile-machine-learning-api/predict.py
  tools/agile-machine-learning-api/requirements.txt
  tools/agile-machine-learning-api/sample_lime.html
  tools/agile-machine-learning-api/schema.py
  tools/agile-machine-learning-api/tests/__init__.py
  tools/agile-machine-learning-api/tests/files_for_testing/predict_points_batch.json
  tools/agile-machine-learning-api/tests/files_for_testing/predict_points_batch_with_id.json
  tools/agile-machine-learning-api/tests/tests_api.py
  tools/agile-machine-learning-api/tests/tests_input_dask.py
  tools/agile-machine-learning-api/tests/tests_launch_demo.py
  tools/agile-machine-learning-api/tests/tests_lime.py
  tools/agile-machine-learning-api/tests/tests_model.py
  tools/agile-machine-learning-api/train.py
  tools/agile-machine-learning-api/update.sh
Labels: cla: yes

#229 Fix gsuite exporter
  tools/gsuite-exporter/gsuite_exporter/exporters/base.py
Labels: cla: yes, size/XS

#202 Addition of Parquet Output Type with Fixed Author
  examples/dataflow-data-generator/README.md
  examples/dataflow-data-generator/data-generator-pipeline/data_generator/AvroUtil.py
  examples/dataflow-data-generator/data-generator-pipeline/data_generator/ParquetUtil.py
  examples/dataflow-data-generator/data-generator-pipeline/data_generator/PrettyDataGenerator.py
  examples/dataflow-data-generator/data-generator-pipeline/data_generator/TimeUtil.py
  examples/dataflow-data-generator/data-generator-pipeline/data_generator_pipeline.py
  examples/dataflow-data-generator/data-generator-pipeline/tests/test_parquet_util.py
Labels: cla: yes, size/L

#207 Initial add of CloudSQL custom metric
  README.md
  examples/cloudsql-custom-metric/.gitignore
  examples/cloudsql-custom-metric/Dockerfile
  examples/cloudsql-custom-metric/README.md
  examples/cloudsql-custom-metric/images/CloudSQL_Metric.png
  examples/cloudsql-custom-metric/images/metric_config.png
  examples/cloudsql-custom-metric/main.py
  examples/cloudsql-custom-metric/requirements.txt
Labels: cla: yes

#232 Fix timestamp when None
  tools/gsuite-exporter/gsuite_exporter/cli.py
Labels: cla: yes, size/XS

#230 Fixing PR 185
  examples/dataflow-data-generator/README.md
  examples/dataflow-data-generator/data-generator-pipeline/data_distribution_matcher.py
  examples/dataflow-data-generator/data-generator-pipeline/data_generator/AvroUtil.py
  examples/dataflow-data-generator/data-generator-pipeline/data_generator/CsvUtil.py
  examples/dataflow-data-generator/data-generator-pipeline/data_generator/DataGenerator.py
  examples/dataflow-data-generator/data-generator-pipeline/data_generator/PerformantDataGenerator.py
  examples/dataflow-data-generator/data-generator-pipeline/data_generator/PrettyDataGenerator.py
  examples/dataflow-data-generator/data-generator-pipeline/data_generator_pipeline.py
  examples/dataflow-data-generator/data-generator-pipeline/resources/lineorder-schema.json
  examples/dataflow-data-generator/data-generator-pipeline/tests/test_data_generator.py
  examples/dataflow-data-generator/data-generator-pipeline/tests/test_fix_record_for_avro.py
  examples/dataflow-data-generator/data-generator-pipeline/tests/test_performant_data_generator.py
  examples/dataflow-data-generator/data-generator-pipeline/tests/test_pretty_data_generator.py
Labels: cla: yes, size/XXL

#233 Fix Broken Link in README
  README.md
Labels: cla: yes, size/XS

#234 Add RECORD type support for parquet.
  examples/dataflow-data-generator/README.md
  examples/dataflow-data-generator/data-generator-pipeline/data_generator/AvroUtil.py
  examples/dataflow-data-generator/data-generator-pipeline/data_generator/ParquetUtil.py
  examples/dataflow-data-generator/data-generator-pipeline/tests/__init__.py
  examples/dataflow-data-generator/data-generator-pipeline/tests/test_parquet_util.py
Labels: cla: yes

#236 Improving bqpipeline README
  README.md
  tools/bqpipeline/README.md
  tools/bqpipeline/bqpipeline/bqpipeline.py
  tools/bqpipeline/docs.md
  tools/bqpipeline/example/example.py
Labels: cla: yes, size/XS

#170 Modifying kubeflow pipeline so anybody can run it on their own projects.
  examples/cloudml-energy-price-forecasting/data_preparation/prepare_data.sql
  examples/cloudml-energy-price-forecasting/data_preparation/weather_mean_std.sql
  examples/cloudml-energy-price-forecasting/kubeflow_pipeline/Energy Price Forecasting Pipeline.ipynb
  examples/cloudml-energy-price-forecasting/kubeflow_pipeline/copy-table.component.yaml
  examples/cloudml-energy-price-forecasting/kubeflow_pipeline/energy-forecasting.tar.gz
  examples/cloudml-energy-price-forecasting/kubeflow_pipeline/export-table.component.yaml
  examples/cloudml-energy-price-forecasting/kubeflow_pipeline/run-git-python-script.component.yaml
  examples/cloudml-energy-price-forecasting/kubeflow_pipeline/train-git-cmle-model.component.yaml
Labels: cla: yes

#242 Update requirements versions in fraud detection package.
  examples/cloudml-fraud-detection/requirements.txt
Labels: cla: yes, size/XS
