Repository GoogleCloudPlatform/professional-services, pull requests merged in 2019-05, with the labels that each got.

#244 Fixed typo
  examples/cloudml-energy-price-forecasting/kubeflow_pipeline/Energy Price Forecasting Pipeline.ipynb
Labels: cla: yes, size/XS

#237 Use discovery document rather then hardcoding api name, support OpenAPI Specification.
  tools/asset-inventory/README.md
  tools/asset-inventory/asset_inventory/api_schema.py
  tools/asset-inventory/asset_inventory/bigquery_schema.py
  tools/asset-inventory/asset_inventory/import_pipeline.py
  tools/asset-inventory/asset_inventory/import_pipeline_metadata
  tools/asset-inventory/asset_inventory/main.py
  tools/asset-inventory/asset_inventory/pipeline_runner.py
  tools/asset-inventory/gae/config.yaml
  tools/asset-inventory/gae/main.py
  tools/asset-inventory/tests/test_api_schema.py
  tools/asset-inventory/tests/test_bigquery_schema.py
Labels: cla: yes, size/L

#246 Fix some style issues in the readme
  examples/gce-to-adminsdk/README.md
Labels: cla: yes, size/XS

#248 Updated to AI Platform
  examples/cloudml-bank-marketing/bank_marketing_classification_model.ipynb
Labels: cla: yes, size/M

#253 Create version 1.1 of maven-archetype-dataflow using Apache Beam 2.12.0
  tools/maven-archetype-dataflow/README.md
  tools/maven-archetype-dataflow/pom.xml
  tools/maven-archetype-dataflow/src/main/resources/archetype-resources/pom.xml
Labels: cla: yes, size/M

#252 Move to v1 cloud asset inventory.
  tools/asset-inventory/asset_inventory/export.py
  tools/asset-inventory/asset_inventory/import_pipeline.py
  tools/asset-inventory/gae/requirements.txt
Labels: cla: yes, size/S

#247 add mk dataset feature to bqpipeline
  tools/bqpipeline/bqpipeline/bqpipeline.py
  tools/bqpipeline/bqpipeline/tests/test_bqpipeline.py
  tools/bqpipeline/docs.md
Labels: cla: yes, size/M

#255 Update curl, bq load and fixed typos
  examples/cloudml-bank-marketing/bank_marketing_classification_model.ipynb
Labels: cla: yes, size/S
