Repository GoogleCloudPlatform/professional-services, pull requests merged in 2020-02, with the labels that each got.

#390 Cloud Composer CI/CD example
  README.md
  examples/cloud-composer-cicd/.gitignore
  examples/cloud-composer-cicd/Dockerfile
  examples/cloud-composer-cicd/README.md
  examples/cloud-composer-cicd/cloudbuild.yaml
  examples/cloud-composer-cicd/dags/echo_and_wait.py
  examples/cloud-composer-cicd/requirements.txt
  examples/cloud-composer-cicd/tests/dag_integrity_test.py
Labels: cla: yes, size/L

#363 bash script to export data & schema from snowflake to bigquery.
  README.md
  tools/snowflake2bq/README.md
  tools/snowflake2bq/bash/sf_config.txt
  tools/snowflake2bq/bash/snowflake-bq.sh
  tools/snowflake2bq/bash/tables.list
Labels: cla: yes, size/L

#383 Update data generator to python3 reduce rendundant clients in tests
  examples/dataflow-data-generator/bigquery-scripts/bq_histogram_tool.py
  examples/dataflow-data-generator/bigquery-scripts/bq_load_batches.py
  examples/dataflow-data-generator/bigquery-scripts/bq_table_resizer.py
  examples/dataflow-data-generator/bigquery-scripts/tests/test_bq_load_batches.py
  examples/dataflow-data-generator/bigquery-scripts/tests/test_bq_table_resizer.py
  examples/dataflow-data-generator/data-generator-pipeline/data_distribution_matcher.py
  examples/dataflow-data-generator/data-generator-pipeline/data_generator/AvroUtil.py
  examples/dataflow-data-generator/data-generator-pipeline/data_generator/CsvUtil.py
  examples/dataflow-data-generator/data-generator-pipeline/data_generator/ParquetUtil.py
  examples/dataflow-data-generator/data-generator-pipeline/data_generator/PerformantDataGenerator.py
  examples/dataflow-data-generator/data-generator-pipeline/data_generator/PrettyDataGenerator.py
  examples/dataflow-data-generator/data-generator-pipeline/data_generator/TimeUtil.py
  examples/dataflow-data-generator/data-generator-pipeline/data_generator/enforce_primary_keys.py
  examples/dataflow-data-generator/data-generator-pipeline/data_generator_joinable_table.py
  examples/dataflow-data-generator/data-generator-pipeline/data_generator_pipeline.py
  examples/dataflow-data-generator/data-generator-pipeline/setup.py
  examples/dataflow-data-generator/data-generator-pipeline/tests/test_dict_to_csv.py
  examples/dataflow-data-generator/data-generator-pipeline/tests/test_fix_record_for_avro.py
  examples/dataflow-data-generator/data-generator-pipeline/tests/test_parquet_util.py
  examples/dataflow-data-generator/data-generator-pipeline/tests/test_performant_data_generator.py
  examples/dataflow-data-generator/data-generator-pipeline/tests/test_pretty_data_generator.py
  examples/dataflow-data-generator/requirements.txt
Labels: cla: yes, size/XXL

#394 slo-generator v0.2.1
  tools/slo-generator/.pylintrc
  tools/slo-generator/Makefile
  tools/slo-generator/README.md
  tools/slo-generator/docs/bigquery.md
  tools/slo-generator/docs/elasticsearch.md
  tools/slo-generator/docs/prometheus.md
  tools/slo-generator/docs/pubsub.md
  tools/slo-generator/docs/stackdriver.md
  tools/slo-generator/samples/error_budget_policy.yaml
  tools/slo-generator/samples/slo_elk_test_good_bad.yaml
  tools/slo-generator/samples/slo_prom_metrics_availability_good_bad.yaml
  tools/slo-generator/samples/slo_prom_metrics_availability_query_sli.yaml
  tools/slo-generator/samples/slo_sd_gae_app_availability.yaml
  tools/slo-generator/samples/slo_sd_gae_app_latency64ms.yaml
  tools/slo-generator/samples/slo_sd_gae_app_latency724ms.yaml
  tools/slo-generator/samples/slo_sd_pubsub_throughput.yaml
  tools/slo-generator/setup.py
  tools/slo-generator/slo_generator/TODO.txt
  tools/slo-generator/slo_generator/backends/base.py
  tools/slo-generator/slo_generator/backends/elasticsearch.py
  tools/slo-generator/slo_generator/backends/prometheus.py
  tools/slo-generator/slo_generator/backends/stackdriver.py
  tools/slo-generator/slo_generator/cli.py
  tools/slo-generator/slo_generator/compute.py
  tools/slo-generator/slo_generator/exporters/base.py
  tools/slo-generator/slo_generator/exporters/bigquery.py
  tools/slo-generator/slo_generator/exporters/prometheus.py
  tools/slo-generator/slo_generator/exporters/pubsub.py
  tools/slo-generator/slo_generator/exporters/stackdriver.py
  tools/slo-generator/slo_generator/utils.py
  tools/slo-generator/tests/unit/fixtures/migrate_format.py
  tools/slo-generator/tests/unit/fixtures/slo_exponential.yaml
  tools/slo-generator/tests/unit/fixtures/slo_prometheus_good_bad_ratio.json
  tools/slo-generator/tests/unit/fixtures/slo_prometheus_good_bad_ratio.yaml
  tools/slo-generator/tests/unit/fixtures/slo_prometheus_query_sli.json
  tools/slo-generator/tests/unit/fixtures/slo_prometheus_query_sli.yaml
  tools/slo-generator/tests/unit/test_compute.py
  tools/slo-generator/tests/unit/test_utils.py
Labels: cla: yes, size/XXL

#382 Feature/composer py3
  examples/cloud-composer-examples/README.md
  examples/cloud-composer-examples/composer_dataflow_examples/dataflow/process_delimited.py
  examples/cloud-composer-examples/composer_http_post_example/dag_trigger.py
  examples/cloud-composer-examples/composer_http_post_example/ephemeral_dataproc_spark_dag.py
  examples/cloud-composer-examples/composer_http_post_example/make_iap_request.py
  examples/cloud-composer-examples/composer_http_post_example/spark_avg_speed.py
  examples/cloud-composer-examples/requirements.txt
  examples/cloud-composer-examples/run_tests.sh
  examples/cloud-composer-examples/tests/test_cloud_composer_examples.py
  examples/cloud-composer-examples/tests/test_dag_validation.py
  examples/cloud-composer-examples/tests/test_spark_avg_speed.py
Labels: cla: yes, size/L

#402 Code for new tutorial on web instrumentation
  examples/web-instrumentation/.eslintrc.js
  examples/web-instrumentation/Dockerfile
  examples/web-instrumentation/README.md
  examples/web-instrumentation/browser/.eslintrc.js
  examples/web-instrumentation/browser/.gitignore
  examples/web-instrumentation/browser/package-lock.json
  examples/web-instrumentation/browser/package.json
  examples/web-instrumentation/browser/src/LoadTest.js
  examples/web-instrumentation/browser/src/TestApp.js
  examples/web-instrumentation/browser/src/TestPayload.js
  examples/web-instrumentation/browser/src/TestResults.js
  examples/web-instrumentation/browser/src/TestSummary.js
  examples/web-instrumentation/browser/src/index.js
  examples/web-instrumentation/browser/src/lib/LogCollector.js
  examples/web-instrumentation/browser/src/lib/LogCollectorBuilder.js
  examples/web-instrumentation/browser/webpack.config.js
  examples/web-instrumentation/cloudbuild.yaml
  examples/web-instrumentation/conf/otservice-config.yaml
  examples/web-instrumentation/dist/index.html
  examples/web-instrumentation/dist/style.css
  examples/web-instrumentation/drawings/app_engine_latency_change.png
  examples/web-instrumentation/drawings/client_latency_median.png
  examples/web-instrumentation/drawings/client_latency_scatterr.png
  examples/web-instrumentation/drawings/error_reporting.png
  examples/web-instrumentation/drawings/error_reporting_spike.png
  examples/web-instrumentation/drawings/gce_cpu_spike.png
  examples/web-instrumentation/drawings/gclb_latency.png
  examples/web-instrumentation/drawings/gclb_latency_spike.png
  examples/web-instrumentation/drawings/gclb_request_count.png
  examples/web-instrumentation/drawings/gclb_rtt_spike.png
  examples/web-instrumentation/drawings/k8s_deployment.png
  examples/web-instrumentation/drawings/load_test_client_latency.png
  examples/web-instrumentation/drawings/local_test_emptyform.png
  examples/web-instrumentation/drawings/local_test_webform.png
  examples/web-instrumentation/drawings/log_analysis_errors.png
  examples/web-instrumentation/drawings/pod_cpu_spike.png
  examples/web-instrumentation/drawings/trace_scatter_plot_load_spike.png
  examples/web-instrumentation/drawings/trace_timeline_spike.png
  examples/web-instrumentation/drawings/web_trace_child_spans.png
  examples/web-instrumentation/drawings/webform_complete.png
  examples/web-instrumentation/drawings/webform_steady_state.png
  examples/web-instrumentation/drawings/webform_steady_state_complete.png
  examples/web-instrumentation/k8s/deployment.yaml
  examples/web-instrumentation/k8s/ingress.yaml
  examples/web-instrumentation/k8s/ot-service.yaml
  examples/web-instrumentation/k8s/service.yaml
  examples/web-instrumentation/load_test_analysis.ipynb
  examples/web-instrumentation/package-lock.json
  examples/web-instrumentation/package.json
  examples/web-instrumentation/src/.gitignore
  examples/web-instrumentation/src/ConsoleLogger.js
  examples/web-instrumentation/src/app.js
  examples/web-instrumentation/src/tracing.js
Labels: cla: yes

#401 Update README.md
  examples/cloudml-energy-price-forecasting/README.md
Labels: cla: yes, size/XS

#396 [Kafka2Avro example] Update to latest Scio release
  examples/dataflow-scala-kafka2avro/build.sbt
Labels: cla: yes, size/XS

#380 Feature/big query hive issue fixes
  tools/hive-bigquery/README.md
  tools/hive-bigquery/bigquery_component.py
  tools/hive-bigquery/bigquery_table.py
  tools/hive-bigquery/bigquery_table_model.py
  tools/hive-bigquery/custom_exceptions.py
  tools/hive-bigquery/database_component.py
  tools/hive-bigquery/gcp_service.py
  tools/hive-bigquery/gcs_storage_component.py
  tools/hive-bigquery/hive_component.py
  tools/hive-bigquery/hive_table.py
  tools/hive-bigquery/hive_table_model.py
  tools/hive-bigquery/hive_to_bigquery.py
  tools/hive-bigquery/init_script.py
  tools/hive-bigquery/kms_component.py
  tools/hive-bigquery/mysql_component.py
  tools/hive-bigquery/properties_reader.py
  tools/hive-bigquery/resource_validator.py
  tools/hive-bigquery/test/generate_data.py
  tools/hive-bigquery/utilities.py
Labels: cla: yes, size/XS

#398 Bigtable: how can we change the key of an existing table?
  README.md
  examples/bigtable-change-key/.gitignore
  examples/bigtable-change-key/README.md
  examples/bigtable-change-key/imgs/pipeline_graph.png
  examples/bigtable-change-key/pom.xml
  examples/bigtable-change-key/scripts/copy_schema_to_new_table.sh
  examples/bigtable-change-key/scripts/create_sandbox_table.sh
  examples/bigtable-change-key/src/main/java/com/google/cloud/pso/dofns/UpdateKey.java
  examples/bigtable-change-key/src/main/java/com/google/cloud/pso/options/BigtablePipelineOptions.java
  examples/bigtable-change-key/src/main/java/com/google/cloud/pso/pipeline/BigtableChangeKey.java
  examples/bigtable-change-key/src/test/java/com/google/cloud/pso/dofns/UpdateKeyTest.java
Labels: cla: yes

#409 change audit query to use base 2 rather than base 10 for calculating billed terabytes/gigabytes
  examples/bigquery-audit-log/bigquery_audit_log.sql
Labels: cla: yes, size/S

#411 Fix Cloud Shell link in Fixity example
  examples/gcs-fixity-function/docs/setup.md
Labels: cla: yes, size/XS

#413 use fastavro to address #412
  examples/dataflow-data-generator/.gitignore
  examples/dataflow-data-generator/data-generator-pipeline/data_distribution_matcher.py
  examples/dataflow-data-generator/data-generator-pipeline/data_generator/AvroUtil.py
  examples/dataflow-data-generator/data-generator-pipeline/data_generator_joinable_table.py
  examples/dataflow-data-generator/data-generator-pipeline/data_generator_pipeline.py
  examples/dataflow-data-generator/data-generator-pipeline/setup.py
  examples/dataflow-data-generator/data-generator-pipeline/tests/test_fix_record_for_avro.py
  examples/dataflow-data-generator/requirements.txt
Labels: cla: yes, size/L

#405 GCS usage recommender - Extra Error Handling
  tools/gcs-usage-recommender/README.md
  tools/gcs-usage-recommender/python/backfill.py
Labels: cla: yes

#414 Replace constant with instance variable in Fixity example
  examples/gcs-fixity-function/src/main.py
Labels: cla: yes, size/XS

#410 Update BQ Benchmark Code to Python3
  examples/bq_file_load_benchmark/benchmark_tools/benchmark_result_util.py
  examples/bq_file_load_benchmark/bq_file_load_benchmark.py
  examples/bq_file_load_benchmark/generic_benchmark_tools/avro_util.py
  examples/bq_file_load_benchmark/generic_benchmark_tools/benchmark_result_util.py
  examples/bq_file_load_benchmark/generic_benchmark_tools/bucket_util.py
  examples/bq_file_load_benchmark/generic_benchmark_tools/file_constants.py
  examples/bq_file_load_benchmark/generic_benchmark_tools/parquet_util.py
  examples/bq_file_load_benchmark/generic_benchmark_tools/schema_creator.py
  examples/bq_file_load_benchmark/generic_benchmark_tools/staging_table_generator.py
  examples/bq_file_load_benchmark/generic_benchmark_tools/table_util.py
  examples/bq_file_load_benchmark/load_benchmark_tools/benchmark_load_table.py
  examples/bq_file_load_benchmark/load_benchmark_tools/load_file_generator.py
  examples/bq_file_load_benchmark/load_benchmark_tools/load_file_parameters.py
  examples/bq_file_load_benchmark/load_benchmark_tools/load_tables_processor.py
  examples/bq_file_load_benchmark/requirements.txt
  examples/bq_file_load_benchmark/tests/test_avro_util.py
  examples/bq_file_load_benchmark/tests/test_bucket_util.py
  examples/bq_file_load_benchmark/tests/test_file_generator.py
  examples/bq_file_load_benchmark/tests/test_parquet_util.py
  examples/bq_file_load_benchmark/tests/test_schema_creator.py
  examples/bq_file_load_benchmark/tests/test_schemas/50_STRING_50_NUMERIC_4.json
  examples/bq_file_load_benchmark/tests/test_staging_table_generator.py
  examples/bq_file_load_benchmark/tests/test_table_util.py
Labels: cla: yes, size/XL

#407 gce-quota-sync: Add linux-headers to alpine pkgs installed in Docker & README update
  tools/gce-quota-sync/Dockerfile
  tools/gce-quota-sync/README.md
Labels: cla: yes, size/S
