Repository GoogleCloudPlatform/professional-services, pull requests merged in 2020-10, with the labels that each got.

#565 Move SLO generator to new repo
  tools/slo-generator/.pylintrc
  tools/slo-generator/Dockerfile
  tools/slo-generator/Makefile
  tools/slo-generator/README.md
  tools/slo-generator/cloudbuild.yaml
  tools/slo-generator/docs/bigquery.md
  tools/slo-generator/docs/elasticsearch.md
  tools/slo-generator/docs/prometheus.md
  tools/slo-generator/docs/pubsub.md
  tools/slo-generator/docs/stackdriver.md
  tools/slo-generator/docs/stackdriver_service_monitoring.md
  tools/slo-generator/samples/README.md
  tools/slo-generator/samples/elasticsearch/slo_elk_test_ratio.yaml
  tools/slo-generator/samples/error_budget_policy.yaml
  tools/slo-generator/samples/error_budget_policy_ssm.yaml
  tools/slo-generator/samples/prometheus/slo_prom_metrics_availability_query_sli.yaml
  tools/slo-generator/samples/prometheus/slo_prom_metrics_availability_ratio.yaml
  tools/slo-generator/samples/stackdriver/slo_gae_app_availability.yaml
  tools/slo-generator/samples/stackdriver/slo_gae_app_latency.yaml
  tools/slo-generator/samples/stackdriver/slo_lb_request_availability.yaml
  tools/slo-generator/samples/stackdriver/slo_lb_request_latency.yaml
  tools/slo-generator/samples/stackdriver/slo_pubsub_subscription_throughput.yaml
  tools/slo-generator/samples/stackdriver_service_monitoring/slo_gae_app_availability.yaml
  tools/slo-generator/samples/stackdriver_service_monitoring/slo_gae_app_availability_basic.yaml
  tools/slo-generator/samples/stackdriver_service_monitoring/slo_gae_app_latency.yaml
  tools/slo-generator/samples/stackdriver_service_monitoring/slo_gae_app_latency_basic.yaml
  tools/slo-generator/samples/stackdriver_service_monitoring/slo_gke_app_availability_basic.yaml
  tools/slo-generator/samples/stackdriver_service_monitoring/slo_gke_app_availability_basic_deprecated.yaml
  tools/slo-generator/samples/stackdriver_service_monitoring/slo_gke_app_latency_basic.yaml
  tools/slo-generator/samples/stackdriver_service_monitoring/slo_gke_app_latency_basic_deprecated.yaml
  tools/slo-generator/samples/stackdriver_service_monitoring/slo_lb_request_availability.yaml
  tools/slo-generator/samples/stackdriver_service_monitoring/slo_lb_request_latency.yaml
  tools/slo-generator/samples/stackdriver_service_monitoring/zzz_slo_pubsub_subscription_throughput.yaml
  tools/slo-generator/setup.py
  tools/slo-generator/slo_generator/__init__.py
  tools/slo-generator/slo_generator/backends/__init__.py
  tools/slo-generator/slo_generator/backends/elasticsearch.py
  tools/slo-generator/slo_generator/backends/prometheus.py
  tools/slo-generator/slo_generator/backends/stackdriver.py
  tools/slo-generator/slo_generator/backends/stackdriver_service_monitoring.py
  tools/slo-generator/slo_generator/cli.py
  tools/slo-generator/slo_generator/compute.py
  tools/slo-generator/slo_generator/exporters/__init__.py
  tools/slo-generator/slo_generator/exporters/bigquery.py
  tools/slo-generator/slo_generator/exporters/prometheus.py
  tools/slo-generator/slo_generator/exporters/pubsub.py
  tools/slo-generator/slo_generator/exporters/stackdriver.py
  tools/slo-generator/slo_generator/report.py
  tools/slo-generator/slo_generator/utils.py
  tools/slo-generator/tests/unit/fixtures/bq_error.json
  tools/slo-generator/tests/unit/fixtures/exporters.yaml
  tools/slo-generator/tests/unit/fixtures/slo_report.json
  tools/slo-generator/tests/unit/fixtures/ssm_services.json
  tools/slo-generator/tests/unit/fixtures/ssm_slos.json
  tools/slo-generator/tests/unit/fixtures/time_series_proto.json
  tools/slo-generator/tests/unit/test_cli.py
  tools/slo-generator/tests/unit/test_compute.py
  tools/slo-generator/tests/unit/test_stubs.py
  tools/slo-generator/tests/unit/test_utils.py
Labels: cla: yes, size/XXL

#542 Add gcpviz visualization tool.
  README.md
  tools/gcpviz/Dockerfile
  tools/gcpviz/README.md
  tools/gcpviz/cmd/main.go
  tools/gcpviz/gcpviz.sh
  tools/gcpviz/gitlab-ci.yml
  tools/gcpviz/go.mod
  tools/gcpviz/go.sum
  tools/gcpviz/labels.yaml
  tools/gcpviz/main.go
  tools/gcpviz/queries/data.js
  tools/gcpviz/queries/everything.js
  tools/gcpviz/queries/gke.js
  tools/gcpviz/queries/instances.js
  tools/gcpviz/queries/load-balancing.js
  tools/gcpviz/queries/network-basic.js
  tools/gcpviz/queries/one-project-example.js
  tools/gcpviz/queries/security.js
  tools/gcpviz/queries/shared-vpc.js
  tools/gcpviz/queries/vpc-security.js
  tools/gcpviz/queries/vpns.js
  tools/gcpviz/redactor.py
  tools/gcpviz/relations.yaml
  tools/gcpviz/requirements.txt
  tools/gcpviz/samples/data.png
  tools/gcpviz/samples/gke.png
  tools/gcpviz/samples/header.png
  tools/gcpviz/samples/instances.png
  tools/gcpviz/samples/network.png
  tools/gcpviz/style.yaml
  tools/gcpviz/wait_for_export.sh
Labels: cla: yes

#571 Fix Python syntax error in bqpipeline.py
  tools/bqpipeline/bqpipeline/bqpipeline.py
Labels: cla: yes, size/XS

#549 A tool to help in applying IAM recommendations at scale.
  README.md
  tools/iam-recommender-at-scale/.gitignore
  tools/iam-recommender-at-scale/README.md
  tools/iam-recommender-at-scale/apply_recommendation.py
  tools/iam-recommender-at-scale/asset/project-security-status-after-apply.png
  tools/iam-recommender-at-scale/asset/project-security-status-graph.png
  tools/iam-recommender-at-scale/asset/project-security-status.png
  tools/iam-recommender-at-scale/common.py
  tools/iam-recommender-at-scale/get_projects_security_status.py
  tools/iam-recommender-at-scale/get_recommendation.py
  tools/iam-recommender-at-scale/install.sh
  tools/iam-recommender-at-scale/requirement.txt
  tools/iam-recommender-at-scale/revert_recommendation.py
Labels: cla: yes

#564 updating webhook pipeline docs and minor enhancements
  tools/webhook-ingestion-pipeline/README.md
  tools/webhook-ingestion-pipeline/assets/app_engine_diagram.png
  tools/webhook-ingestion-pipeline/deploy_dataflow.sh
  tools/webhook-ingestion-pipeline/webhook_endpoint/main.py
Labels: cla: yes

#574 Changes in naming of the file
  tools/iam-recommender-at-scale/apply_recommendations.py
  tools/iam-recommender-at-scale/asset/project-security-status.png
  tools/iam-recommender-at-scale/get_projects_security_status.py
  tools/iam-recommender-at-scale/get_recommendations.py
  tools/iam-recommender-at-scale/revert_recommendations.py
Labels: cla: yes

#560 Update to new billing export schema
  tools/cuds-prioritized-attribution/composer/dependencies/billingoutput.sql
Labels: cla: yes, size/M

#578 Job doesn't need catch-up. Correct typo in dag.
  tools/cuds-prioritized-attribution/composer/cud_correction_dag.py
  tools/cuds-prioritized-attribution/composer/dependencies/helper_function.py
Labels: cla: yes, size/XS

#570 examples of tensorflow serving on GKE and load testing
  README.md
  examples/tf-load-testing/README.md
  examples/tf-load-testing/create-cluster.sh
  examples/tf-load-testing/locust/Dockerfile
  examples/tf-load-testing/locust/cloudbuild.yaml
  examples/tf-load-testing/locust/kubernetes.yaml
  examples/tf-load-testing/locust/locustfile.py
  examples/tf-load-testing/locust/master.conf
  examples/tf-load-testing/locust/worker.conf
  examples/tf-load-testing/tensorflow/Dockerfile
  examples/tf-load-testing/tensorflow/batching_parameters_default.txt
  examples/tf-load-testing/tensorflow/cloudbuild.yaml
  examples/tf-load-testing/tensorflow/create_model.py
  examples/tf-load-testing/tensorflow/experiment.py
  examples/tf-load-testing/tensorflow/experiment_test.py
  examples/tf-load-testing/tensorflow/kubernetes_default.yaml
  examples/tf-load-testing/tensorflow/models.config
Labels: cla: yes, size/XL
