Repository GoogleCloudPlatform/professional-services, pull requests merged in 2020-07, with the labels that each got.

#507 Create a partition table for SLI/SLO.
  tools/slo-generator/setup.py
  tools/slo-generator/slo_generator/exporters/bigquery.py
Labels: cla: yes, size/XS

#514 Adds link to Airflow variables concept
  examples/cloud-composer-examples/composer_dataflow_examples/README.md
Labels: cla: yes, size/XS

#515 Fix typo in Bytes in TB in BQ load batches
  examples/dataflow-data-generator/bigquery-scripts/bq_load_batches.py
Labels: cla: yes, size/XS

#513 Add solution diagram
  examples/cloudml-support-routing/README.md
  examples/cloudml-support-routing/solution-diagram.png
Labels: cla: yes

#516 org-policy-enforcer
  README.md
  tools/org-policy-enforcer/README.md
  tools/org-policy-enforcer/org_policy_not_enforced.py
  tools/org-policy-enforcer/requirement.txt
  tools/slo-generator/slo_generator/backends/stackdriver.py
Labels: cla: yes, size/L

#518 remove org-policy-enforcer
  README.md
  tools/org-policy-enforcer/README.md
  tools/org-policy-enforcer/org_policy_not_enforced.py
  tools/org-policy-enforcer/requirement.txt
Labels: cla: yes, size/L

#524 Add tools permission-discrepancy-finder and boolean-org-policy-enforcer
  README.md
  tools/boolean-org-policy-enforcer/README.md
  tools/boolean-org-policy-enforcer/enforce_boolean_org_policy_in_bulk.py
  tools/boolean-org-policy-enforcer/projects_deviate_from_boolean_org_policy.py
  tools/boolean-org-policy-enforcer/requirement.txt
  tools/permission-discrepancy-finder/README.md
  tools/permission-discrepancy-finder/grant_role.py
  tools/permission-discrepancy-finder/permission_discrepancy_finder.py
  tools/permission-discrepancy-finder/requirement.txt
Labels: cla: yes, size/XXL

#519 Dataflow pipeline to match DLP SSN quotes to keyed hash dictionary
  README.md
  examples/dataflow-dlp-hash-pipeline/.gitignore
  examples/dataflow-dlp-hash-pipeline/Makefile
  examples/dataflow-dlp-hash-pipeline/README.md
  examples/dataflow-dlp-hash-pipeline/img/arch.png
  examples/dataflow-dlp-hash-pipeline/infrastructure/iam.tf
  examples/dataflow-dlp-hash-pipeline/infrastructure/main.tf
  examples/dataflow-dlp-hash-pipeline/infrastructure/terraform.tfvars.sample
  examples/dataflow-dlp-hash-pipeline/infrastructure/variables.tf
  examples/dataflow-dlp-hash-pipeline/inputs/.gitkeep
  examples/dataflow-dlp-hash-pipeline/pom.xml
  examples/dataflow-dlp-hash-pipeline/scripts/generate-input-file.py
  examples/dataflow-dlp-hash-pipeline/scripts/generate-test-socials.py
  examples/dataflow-dlp-hash-pipeline/scripts/hasher.py
  examples/dataflow-dlp-hash-pipeline/scripts/poller.py
  examples/dataflow-dlp-hash-pipeline/scripts/requirements.txt
  examples/dataflow-dlp-hash-pipeline/src/license/license-header-style.xml
  examples/dataflow-dlp-hash-pipeline/src/license/license-header.txt
  examples/dataflow-dlp-hash-pipeline/src/main/java/com/google/cloud/pso/hashpipeline/ChunkFileDoFn.java
  examples/dataflow-dlp-hash-pipeline/src/main/java/com/google/cloud/pso/hashpipeline/DLPFindingsDoFn.java
  examples/dataflow-dlp-hash-pipeline/src/main/java/com/google/cloud/pso/hashpipeline/HashQuotesDoFn.java
  examples/dataflow-dlp-hash-pipeline/src/main/java/com/google/cloud/pso/hashpipeline/Hashpipeline.java
  examples/dataflow-dlp-hash-pipeline/src/main/java/com/google/cloud/pso/hashpipeline/KVtoJSONDoFn.java
  examples/dataflow-dlp-hash-pipeline/src/main/java/com/google/cloud/pso/hashpipeline/MatchHashDoFn.java
  examples/dataflow-dlp-hash-pipeline/src/main/java/com/google/cloud/pso/hashpipeline/package-info.java
  examples/dataflow-dlp-hash-pipeline/src/test/java/com/google/cloud/pso/hashpipeline/ChunkFileDoFnTest.java
  examples/dataflow-dlp-hash-pipeline/src/test/resources/tiny.txt
Labels: cla: yes
