Repository GoogleCloudPlatform/professional-services, pull requests merged in 2020-03, with the labels that each got.

#404 Fix arithmetics in tools/gce-quota-sync
  tools/gce-quota-sync/gce-quota-sync.py
Labels: cla: yes, size/XS

#425 Remove cai_to_api.
  tools/asset-inventory/README.md
  tools/asset-inventory/asset_inventory/cai_to_api.py
  tools/asset-inventory/asset_inventory/cai_to_api_properties.json
  tools/asset-inventory/asset_inventory/import_pipeline.py
  tools/asset-inventory/gae/config.yaml
  tools/asset-inventory/gae/main.py
  tools/asset-inventory/gae/requirements.txt
  tools/asset-inventory/requirements.txt
  tools/asset-inventory/setup.py
  tools/asset-inventory/tests/test_api_schema.py
  tools/asset-inventory/tests/test_cai_to_resource_mapping.py
Labels: cla: yes, size/XL

#426 Update dependency versions for maven-archetype-dataflow
  tools/maven-archetype-dataflow/README.md
  tools/maven-archetype-dataflow/pom.xml
  tools/maven-archetype-dataflow/src/main/resources/archetype-resources/pom.xml
Labels: cla: yes, size/S

#392 E2E test for Dataflow application
  examples/e2e-test-dataflow/Readme.md
  examples/e2e-test-dataflow/data/expected-output/IngestionE2EDataValidation/result.csv
  examples/e2e-test-dataflow/data/input/IngestionE2EDataValidation/data1.csv
  examples/e2e-test-dataflow/data/input/IngestionE2ESmokeTest/data1.csv
  examples/e2e-test-dataflow/pom.xml
  examples/e2e-test-dataflow/src/main/java/util/BQUtils.java
  examples/e2e-test-dataflow/src/main/java/util/BashOutput.java
  examples/e2e-test-dataflow/src/main/java/util/CompareContent.java
  examples/e2e-test-dataflow/src/main/java/util/DFJobConstants.java
  examples/e2e-test-dataflow/src/main/java/util/MyBashExecutor.java
  examples/e2e-test-dataflow/src/main/java/util/Utils.java
  examples/e2e-test-dataflow/src/test/java/e2etest/E2ETest.java
  examples/e2e-test-dataflow/src/test/java/e2etest/RunCucumberTest.java
  examples/e2e-test-dataflow/src/test/resources/e2etest/dataflow-e2e-test.feature
Labels: cla: yes

#427 fix: use yapf as a Python module in format/check_format
  helpers/check_format.sh
  helpers/format.sh
Labels: cla: yes, size/S

#428 Update Readme.md - Fix typos.
  tools/bq-visualizer/src/README.md
Labels: cla: yes, size/XS

#424 add integration tests. use google-api-core instead of google-cloud-core
  tools/cdf-lineage-exporter/README.md
  tools/cdf-lineage-exporter/cdap_lineage_export/__init__.py
  tools/cdf-lineage-exporter/cdap_lineage_export/cdap/client.py
  tools/cdf-lineage-exporter/cdap_lineage_export/main.py
  tools/cdf-lineage-exporter/cdap_lineage_export/requirements.txt
  tools/cdf-lineage-exporter/cdap_lineage_export/setup.py
  tools/cdf-lineage-exporter/dev-requirements.txt
  tools/cdf-lineage-exporter/tests/system/test_client.py
  tools/cdf-lineage-exporter/tests/unit/test_client.py
Labels: cla: yes

#431 E2E test DF
  examples/e2e-test-dataflow/Readme.md
  examples/e2e-test-dataflow/data/expected-output/IngestionE2EDataValidation/result.csv
  examples/e2e-test-dataflow/data/input/IngestionE2EDataValidation/data1.csv
  examples/e2e-test-dataflow/data/input/IngestionE2ESmokeTest/data1.csv
  examples/e2e-test-dataflow/pom.xml
  examples/e2e-test-dataflow/src/main/java/util/BQUtils.java
  examples/e2e-test-dataflow/src/main/java/util/BashOutput.java
  examples/e2e-test-dataflow/src/main/java/util/CompareContent.java
  examples/e2e-test-dataflow/src/main/java/util/DFJobConstants.java
  examples/e2e-test-dataflow/src/main/java/util/MyBashExecutor.java
  examples/e2e-test-dataflow/src/main/java/util/Utils.java
  examples/e2e-test-dataflow/src/test/java/e2etest/E2ETest.java
  examples/e2e-test-dataflow/src/test/java/e2etest/RunCucumberTest.java
  examples/e2e-test-dataflow/src/test/resources/e2etest/dataflow-e2e-test.feature
Labels: cla: yes

#430 Dataproc GCS Connector
  README.md
  examples/dataproc-gcs-connector/.gitignore
  examples/dataproc-gcs-connector/README.md
  examples/dataproc-gcs-connector/build_gcs_connector.sh
  examples/dataproc-gcs-connector/connectors.sh
  examples/dataproc-gcs-connector/terraform/README.md
  examples/dataproc-gcs-connector/terraform/main.tf
  examples/dataproc-gcs-connector/terraform/variables.tf
  examples/dataproc-gcs-connector/test_gcs_connector.sh
Labels: cla: yes, size/XL
