Repository GoogleCloudPlatform/professional-services, pull requests merged in 2020-12, with the labels that each got.

#474 BigQuery email exports example
  README.md
  examples/bq-email-exports/.gitignore
  examples/bq-email-exports/README.md
  examples/bq-email-exports/__init__.py
  examples/bq-email-exports/export_query_results_function/__init__.py
  examples/bq-email-exports/export_query_results_function/main.py
  examples/bq-email-exports/export_query_results_function/requirements.txt
  examples/bq-email-exports/send_email_function/__init__.py
  examples/bq-email-exports/send_email_function/main.py
  examples/bq-email-exports/send_email_function/requirements.txt
  examples/bq-email-exports/terraform/README.md
  examples/bq-email-exports/terraform/main.tf
  examples/bq-email-exports/terraform/variables.tf
  examples/bq-email-exports/tests/__init__.py
  examples/bq-email-exports/tests/export_query_results_function/__init__.py
  examples/bq-email-exports/tests/export_query_results_function/test_main.py
  examples/bq-email-exports/tests/send_email_function/__init__.py
  examples/bq-email-exports/tests/send_email_function/test_main.py
Labels: cla: yes, size/XL

#584 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: cla: yes, size/XS

#585 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: cla: yes, size/XS

#582 fix mapping between region specified and location for multi-regional …
  examples/kerberized_data_lake/main.tf
  examples/kerberized_data_lake/variables.tf
Labels: cla: yes, size/S

#587 Add benchmark code for spanner subquery
  README.md
  examples/spanner-interleave-subquery/README.md
  examples/spanner-interleave-subquery/go.mod
  examples/spanner-interleave-subquery/go.sum
  examples/spanner-interleave-subquery/main.go
  examples/spanner-interleave-subquery/schema.sql
Labels: cla: yes, size/L
