Repository GoogleCloudPlatform/professional-services, pull requests merged in 2020-08, with the labels that each got.

#529 Fixed README.md typo, "Dialoflow" -> "Dialogflow"
  README.md
Labels: cla: yes, size/XS

#530 CloudBuild Cleanup
  cloudbuild.yaml
  examples/dataflow-python-examples/cloudbuild.yaml
Labels: cla: yes, size/S

#531 Updated architecture diagram
  examples/dataflow-dlp-hash-pipeline/README.md
  examples/dataflow-dlp-hash-pipeline/img/arch.png
  examples/dataflow-dlp-hash-pipeline/infrastructure/main.tf
Labels: cla: yes

#538 Fix #537
  README.md
Labels: cla: yes, size/XS

#535 Prune columns over 10,000.
  tools/asset-inventory/asset_inventory/bigquery_schema.py
  tools/asset-inventory/tests/test_bigquery_schema.py
Labels: cla: yes, size/M

#539 deps: add max version for google-cloud-* libraries
  cloudbuild.yaml
  tools/hive-bigquery/setup.py
Labels: cla: yes, size/S

#544 Translate additionalProperties API properties into arrays.
  tools/asset-inventory/README.md
  tools/asset-inventory/asset_inventory/api_schema.py
  tools/asset-inventory/asset_inventory/bigquery_schema.py
  tools/asset-inventory/setup.py
  tools/asset-inventory/tests/test_api_schema.py
  tools/asset-inventory/tests/test_bigquery_schema.py
Labels: cla: yes, size/L

#543 Add STS Job Manager
  .gitignore
  README.md
  tools/sts-job-manager/.dockerignore
  tools/sts-job-manager/.gitignore
  tools/sts-job-manager/Dockerfile
  tools/sts-job-manager/README.md
  tools/sts-job-manager/constants/__init__.py
  tools/sts-job-manager/constants/schemas.py
  tools/sts-job-manager/constants/status.py
  tools/sts-job-manager/lib/__init__.py
  tools/sts-job-manager/lib/options.py
  tools/sts-job-manager/lib/services.py
  tools/sts-job-manager/lib/table_util.py
  tools/sts-job-manager/pause_all_jobs.py
  tools/sts-job-manager/prepare_tables.py
  tools/sts-job-manager/remove_successful_one_time_jobs.py
  tools/sts-job-manager/requirements.txt
  tools/sts-job-manager/sts_job_manager.py
Labels: cla: yes, size/XXL
