Repository GoogleCloudPlatform/professional-services, pull requests merged in 2020-01, with the labels that each got.

#355 Generalize benchmark code for future benchmark tests
  examples/bq_file_load_benchmark/README.md
  examples/bq_file_load_benchmark/bq_file_load_benchmark.py
  examples/bq_file_load_benchmark/generic_benchmark_tools/__init__.py
  examples/bq_file_load_benchmark/generic_benchmark_tools/avro_util.py
  examples/bq_file_load_benchmark/generic_benchmark_tools/benchmark_parameters.py
  examples/bq_file_load_benchmark/generic_benchmark_tools/benchmark_result_util.py
  examples/bq_file_load_benchmark/generic_benchmark_tools/bucket_util.py
  examples/bq_file_load_benchmark/generic_benchmark_tools/file_constants.py
  examples/bq_file_load_benchmark/generic_benchmark_tools/parquet_util.py
  examples/bq_file_load_benchmark/generic_benchmark_tools/schema_creator.py
  examples/bq_file_load_benchmark/generic_benchmark_tools/staging_table_generator.py
  examples/bq_file_load_benchmark/generic_benchmark_tools/table_util.py
  examples/bq_file_load_benchmark/json_schemas/results_table_schema.json
  examples/bq_file_load_benchmark/load_benchmark_tools/__init__.py
  examples/bq_file_load_benchmark/load_benchmark_tools/benchmark_load_table.py
  examples/bq_file_load_benchmark/load_benchmark_tools/load_file_generator.py
  examples/bq_file_load_benchmark/load_benchmark_tools/load_file_parameters.py
  examples/bq_file_load_benchmark/load_benchmark_tools/load_tables_processor.py
  examples/bq_file_load_benchmark/setup.py
  examples/bq_file_load_benchmark/tests/test_avro_util.py
  examples/bq_file_load_benchmark/tests/test_bucket_util.py
  examples/bq_file_load_benchmark/tests/test_file_generator.py
  examples/bq_file_load_benchmark/tests/test_parquet_util.py
  examples/bq_file_load_benchmark/tests/test_schema_creator.py
  examples/bq_file_load_benchmark/tests/test_schemas/test_schema.json
  examples/bq_file_load_benchmark/tests/test_staging_table_generator.py
  examples/bq_file_load_benchmark/tests/test_table_util.py
Labels: cla: yes

#387 Python2 to python3
  examples/cryptorealtime/README.md
  examples/cryptorealtime/frontend/README.MD
  examples/cryptorealtime/frontend/app.py
  examples/cryptorealtime/frontend/requirements.txt
  examples/cryptorealtime/terraform-setup/startup.tpl
Labels: cla: yes, size/L

#391 deleting tables after done recording benchmark results
  examples/bq_file_load_benchmark/load_benchmark_tools/benchmark_load_table.py
Labels: cla: yes, size/XS
