Repository GoogleCloudPlatform/professional-services, pull requests merged in 2020-04, with the labels that each got.

#433 Dialogflow Webhook Example in Python
  README.md
  examples/dialogflow-webhook-example/README.md
  examples/dialogflow-webhook-example/agent.zip
  examples/dialogflow-webhook-example/intents_config.yaml
  examples/dialogflow-webhook-example/main.py
  examples/dialogflow-webhook-example/requirements.txt
Labels: cla: yes

#440 Revert "Dialogflow Webhook Example in Python"
  README.md
  examples/dialogflow-webhook-example/README.md
  examples/dialogflow-webhook-example/agent.zip
  examples/dialogflow-webhook-example/intents_config.yaml
  examples/dialogflow-webhook-example/main.py
  examples/dialogflow-webhook-example/requirements.txt
Labels: cla: yes

#441 Dialogflow Webhook Example
  README.md
  examples/dialogflow-webhook-example/README.md
  examples/dialogflow-webhook-example/agent.zip
  examples/dialogflow-webhook-example/intents_config.yaml
  examples/dialogflow-webhook-example/main.py
  examples/dialogflow-webhook-example/requirements.txt
Labels: cla: yes

#435 fix: missing import sys
  examples/dataflow-python-examples/dataflow_python_examples/data_enrichment.py
Labels: cla: yes, size/XS

#445 update retention property for job history files
  examples/dataproc-persistent-history-server/README.md
Labels: cla: yes, size/XS

#432 adds quota manager, which helps in updating the project quotas
  README.md
  tools/quota-manager/Pipfile
  tools/quota-manager/Pipfile.lock
  tools/quota-manager/README.md
  tools/quota-manager/quota.py
  tools/quota-manager/update-bigquery-quota.py
Labels: cla: yes, size/XL

#400 Update ReadMe.md
  examples/dlp/cloud_function_example/README.md
Labels: cla: yes, size/XS

#416 Update base image for cloud builds
  cloudbuild/Dockerfile
Labels: cla: yes, size/XS

#438 Example how to create and update entities for Dialogflow
  README.md
  examples/dialogflow-entities-example/README.md
  examples/dialogflow-entities-example/entities.json
  examples/dialogflow-entities-example/main.py
  examples/dialogflow-entities-example/requirements.txt
  examples/dialogflow-webhook-example/main.py
Labels: cla: yes, size/L

#446 fix 2to3 error in updating composer example
  examples/cloud-composer-examples/composer_http_post_example/dag_trigger.py
  examples/cloud-composer-examples/requirements.txt
Labels: cla: yes, size/XS

#447 fix broken ml code due to tf2 release
  examples/cloudml-collaborative-filtering/README.md
  examples/cloudml-collaborative-filtering/bin/run.predict.cloud.sh
  examples/cloudml-collaborative-filtering/bin/run.serve.cloud.sh
  examples/cloudml-collaborative-filtering/bin/run.train.cloud.sh
  examples/cloudml-collaborative-filtering/bin/run.train.local.sh
  examples/cloudml-collaborative-filtering/preprocessing/config.example.ini
  examples/cloudml-collaborative-filtering/preprocessing/run_preprocess.py
  examples/cloudml-collaborative-filtering/requirements.txt
  examples/cloudml-collaborative-filtering/trainer/model.py
  examples/cloudml-collaborative-filtering/trainer/utils.py
Labels: cla: yes, size/M

#458 fix #457
  examples/dataflow-data-generator/bigquery-scripts/tests/test_bq_table_resizer.py
  examples/dataflow-data-generator/data-generator-pipeline/data_generator/PrettyDataGenerator.py
Labels: cla: yes, size/XS

#452 [slo-generator] Fix frequent 500s in Stackdriver metric.timeseries.write, release bug…
  tools/slo-generator/setup.py
  tools/slo-generator/slo_generator/exporters/stackdriver.py
Labels: cla: yes, size/S

#448 fix dependencies for recommendation solution
  examples/cloudml-collaborative-filtering/requirements.txt
Labels: cla: yes, size/XS

#455 Fix loading of commitments_schema.
  tools/cuds-prioritized-attribution/README.md
  tools/cuds-prioritized-attribution/composer/dependencies/commitments_schema.py
  tools/cuds-prioritized-attribution/composer/dependencies/helper_function.py
  tools/cuds-prioritized-attribution/terraform/.gitignore
  tools/cuds-prioritized-attribution/terraform/main.tf
  tools/cuds-prioritized-attribution/test/tests/commitments_load.json
  tools/cuds-prioritized-attribution/test/tests/expected_output.json
  tools/cuds-prioritized-attribution/test/tests/export_load.json
  tools/cuds-prioritized-attribution/test/tests/test_10_2/expected_load.json
  tools/cuds-prioritized-attribution/test/tests/test_11_1/expected_load.json
  tools/cuds-prioritized-attribution/test/tests/test_11_2/expected_load.json
Labels: cla: yes

#454 Condition on value not index when checking for lastModifiedTime.
  tools/asset-inventory/asset_inventory/api_schema.py
  tools/asset-inventory/tests/test_api_schema.py
Labels: cla: yes, size/M

#463 patch codelab issues due to airflow version update
  examples/cloud-composer-examples/composer_http_post_example/ephemeral_dataproc_spark_dag.py
  examples/cloud-composer-examples/composer_http_post_example/make_iap_request.py
Labels: cla: yes, size/L

#465 fix: allow builds from forks
  cloudbuild.yaml
Labels: cla: yes, size/XS
