Repository GoogleCloudPlatform/professional-services, pull requests merged in 2020-06, with the labels that each got.

#486 feat: add user-agent to hive-bigquery tool
  cloudbuild.yaml
  helpers/exclusion_list.txt
  tools/hive-bigquery/README.md
  tools/hive-bigquery/cloudbuild.yaml
  tools/hive-bigquery/hive_to_bigquery/__init__.py
  tools/hive-bigquery/hive_to_bigquery/__main__.py
  tools/hive-bigquery/hive_to_bigquery/bigquery_component.py
  tools/hive-bigquery/hive_to_bigquery/bigquery_table.py
  tools/hive-bigquery/hive_to_bigquery/bigquery_table_model.py
  tools/hive-bigquery/hive_to_bigquery/client_info.py
  tools/hive-bigquery/hive_to_bigquery/custom_exceptions.py
  tools/hive-bigquery/hive_to_bigquery/database_component.py
  tools/hive-bigquery/hive_to_bigquery/gcp_service.py
  tools/hive-bigquery/hive_to_bigquery/gcs_storage_component.py
  tools/hive-bigquery/hive_to_bigquery/hive_component.py
  tools/hive-bigquery/hive_to_bigquery/hive_table.py
  tools/hive-bigquery/hive_to_bigquery/hive_table_model.py
  tools/hive-bigquery/hive_to_bigquery/init_script.py
  tools/hive-bigquery/hive_to_bigquery/kms_component.py
  tools/hive-bigquery/hive_to_bigquery/mysql_component.py
  tools/hive-bigquery/hive_to_bigquery/properties_reader.py
  tools/hive-bigquery/hive_to_bigquery/resource_validator.py
  tools/hive-bigquery/hive_to_bigquery/utilities.py
  tools/hive-bigquery/prerequisites/create_sql_instance.sh
  tools/hive-bigquery/prerequisites/prerequisites.sh
  tools/hive-bigquery/prerequisites/requirements.txt
  tools/hive-bigquery/setup.py
  tools/hive-bigquery/tests/create_hive_tables.sql
  tools/hive-bigquery/tests/generate_data.py
  tools/hive-bigquery/tests/run_tests.sh
  tools/hive-bigquery/tests/unit/conftest.py
  tools/hive-bigquery/tests/unit/test_bigquery_component.py
  tools/hive-bigquery/tests/unit/test_gcs_storage_component.py
  tools/hive-bigquery/tests/unit/test_kms_component.py
Labels: cla: yes, size/L

#492 Deployable Webhook App
  README.md
  tools/webhook-ingestion-pipeline/.gitignore
  tools/webhook-ingestion-pipeline/Makefile
  tools/webhook-ingestion-pipeline/README.md
  tools/webhook-ingestion-pipeline/build.sh
  tools/webhook-ingestion-pipeline/deploy_dataflow.sh
  tools/webhook-ingestion-pipeline/tear_down.sh
  tools/webhook-ingestion-pipeline/terraform/app_engine.tf
  tools/webhook-ingestion-pipeline/terraform/bigquery.tf
  tools/webhook-ingestion-pipeline/terraform/dataflow.tf
  tools/webhook-ingestion-pipeline/terraform/gcs.tf
  tools/webhook-ingestion-pipeline/terraform/network.tf
  tools/webhook-ingestion-pipeline/terraform/pub_sub.tf
  tools/webhook-ingestion-pipeline/terraform/service_account.tf
  tools/webhook-ingestion-pipeline/terraform/variables.tf
  tools/webhook-ingestion-pipeline/tests/system/send_data.py
  tools/webhook-ingestion-pipeline/tests/system/test_deploy_webhook.sh
  tools/webhook-ingestion-pipeline/webhook_endpoint/app.yaml
  tools/webhook-ingestion-pipeline/webhook_endpoint/consts.py
  tools/webhook-ingestion-pipeline/webhook_endpoint/exceptions.py
  tools/webhook-ingestion-pipeline/webhook_endpoint/main.py
  tools/webhook-ingestion-pipeline/webhook_endpoint/pubsub_publisher.py
  tools/webhook-ingestion-pipeline/webhook_endpoint/requirements.txt
Labels: cla: yes, size/XL

#439 Adding example files/scripts to support shutdown of dataproc clusters…
  examples/dataproc-idle-shutdown/README.md
  examples/dataproc-idle-shutdown/create-idlemonitoringjob.sh
  examples/dataproc-idle-shutdown/idle-check.sh
  examples/dataproc-idle-shutdown/img/idle-script.png
Labels: cla: yes, size/L

#498 Patch/composer code lab
  examples/cloud-composer-examples/.gitignore
  examples/cloud-composer-examples/Dockerfile
  examples/cloud-composer-examples/cloudbuild.yaml
  examples/cloud-composer-examples/composer_http_post_example/ephemeral_dataproc_spark_dag.py
  examples/cloud-composer-examples/composer_http_post_example/nyc-tlc-yellow.json
  examples/cloud-composer-examples/requirements.txt
  examples/cloud-composer-examples/run_tests.sh
  examples/cloud-composer-examples/tests/test_dag_validation.py
Labels: cla: yes, size/L

#504 Add test entry for composer http post example tests
  cloudbuild.yaml
Labels: cla: yes, size/S

#503 Formatted & Fixed Static check issues for batch examples
  cloudbuild.yaml
  examples/dataflow-python-examples/batch-examples/cookbook-examples/Dockerfile
  examples/dataflow-python-examples/batch-examples/cookbook-examples/pipelines/data_enrichment.py
  examples/dataflow-python-examples/batch-examples/cookbook-examples/pipelines/data_ingestion.py
  examples/dataflow-python-examples/batch-examples/cookbook-examples/pipelines/data_ingestion_configurable.py
  examples/dataflow-python-examples/batch-examples/cookbook-examples/pipelines/data_lake_to_mart.py
  examples/dataflow-python-examples/batch-examples/cookbook-examples/pipelines/data_lake_to_mart_cogroupbykey.py
  examples/dataflow-python-examples/batch-examples/cookbook-examples/pipelines/data_transformation.py
  examples/dataflow-python-examples/batch-examples/cookbook-examples/pipelines/image_labels.py
  examples/dataflow-python-examples/batch-examples/cookbook-examples/tests/test_image_labels.py
  examples/dataflow-python-examples/batch-examples/cookbook-examples/tests/test_parsing_logic.py
  examples/dataflow-python-examples/streaming-examples/slowlychanging-sideinput/Dockerfile
  helpers/exclusion_list.txt
Labels: cla: yes, size/L

#481 Example to retrieve user profile from an IAP-enabled GAE application
  README.md
  examples/iap-user-profile/.gcloudignore
  examples/iap-user-profile/README.md
  examples/iap-user-profile/__tests__/auth/index.test.js
  examples/iap-user-profile/__tests__/routes/index.test.js
  examples/iap-user-profile/__tests__/services/user-service.test.js
  examples/iap-user-profile/app.js
  examples/iap-user-profile/app.yaml
  examples/iap-user-profile/auth/index.js
  examples/iap-user-profile/bin/www
  examples/iap-user-profile/logging/index.d.ts
  examples/iap-user-profile/logging/index.js
  examples/iap-user-profile/package-lock.json
  examples/iap-user-profile/package.json
  examples/iap-user-profile/public/images/blank-profile.jpg
  examples/iap-user-profile/public/stylesheets/style.css
  examples/iap-user-profile/routes/index.js
  examples/iap-user-profile/services/user-service.js
  examples/iap-user-profile/views/error.mustache
  examples/iap-user-profile/views/index.mustache
Labels: cla: yes

#505 Add DAI support message routing example.
  README.md
  __init__.py
  examples/cloudml-support-routing/Notebooks/EDA.ipynb
  examples/cloudml-support-routing/Notebooks/SciKit_models.ipynb
  examples/cloudml-support-routing/Notebooks/wrapping_labels_analysis.ipynb
  examples/cloudml-support-routing/README.md
  examples/cloudml-support-routing/config/pipeline.yaml
  examples/cloudml-support-routing/online_predict.sh
  examples/cloudml-support-routing/predict_payload.json
  examples/cloudml-support-routing/queries/clean_categories.sql
  examples/cloudml-support-routing/queries/combine_tables.sql
  examples/cloudml-support-routing/queries/prediction_features.sql
  examples/cloudml-support-routing/queries/remove_nulls.sql
  examples/cloudml-support-routing/queries/train_and_predict_split.sql
  examples/cloudml-support-routing/queries/training_features.sql
  examples/cloudml-support-routing/requirements.txt
  examples/cloudml-support-routing/run_pipeline.sh
  examples/cloudml-support-routing/scripts/create_features.py
  examples/cloudml-support-routing/scripts/predict.py
  examples/cloudml-support-routing/scripts/train.py
  examples/cloudml-support-routing/scripts/utils.py
Labels: cla: yes
