Repository GoogleCloudPlatform/professional-services, pull requests merged in 2020-11, with the labels that each got.

#577 Ignore properties with no valid characters.
  tools/asset-inventory/asset_inventory/bigquery_schema.py
  tools/asset-inventory/requirements.txt
  tools/asset-inventory/setup.py
  tools/asset-inventory/tests/test_bigquery_schema.py
Labels: cla: yes, size/S

#580 Correction in reverting recommendations
  tools/iam-recommender-at-scale/README.md
  tools/iam-recommender-at-scale/apply_recommendations.py
  tools/iam-recommender-at-scale/asset/project-security-status-graph.png
  tools/iam-recommender-at-scale/common.py
  tools/iam-recommender-at-scale/get_recommendations.py
Labels: cla: yes

#579 Update README.md
  tools/iam-recommender-at-scale/README.md
Labels: cla: yes, size/XS

#569 add dataproc kerberos tf example
  examples/kerberized_data_lake/README.md
  examples/kerberized_data_lake/img/dataproc_kerberos_cross-realm.png
  examples/kerberized_data_lake/main.tf
  examples/kerberized_data_lake/modules/template_bash_script/README.md
  examples/kerberized_data_lake/modules/template_bash_script/main.tf
  examples/kerberized_data_lake/modules/template_bash_script/outputs.tf
  examples/kerberized_data_lake/modules/template_bash_script/variables.tf
  examples/kerberized_data_lake/outputs.tf
  examples/kerberized_data_lake/requirements-dev.txt
  examples/kerberized_data_lake/scripts/destroy-generated-secrets.sh
  examples/kerberized_data_lake/scripts/init-actions/create-users.sh.logic
  examples/kerberized_data_lake/scripts/init-actions/create-users.sh.tmpl
  examples/kerberized_data_lake/scripts/init-actions/disable-history-server.sh
  examples/kerberized_data_lake/scripts/init-actions/export-hadoop-configs.sh
  examples/kerberized_data_lake/scripts/init-actions/setup-kerberos-config.sh.logic
  examples/kerberized_data_lake/scripts/init-actions/setup-kerberos-config.sh.tmpl
  examples/kerberized_data_lake/scripts/init-actions/setup-kerberos-trust.sh.logic
  examples/kerberized_data_lake/scripts/init-actions/setup-kerberos-trust.sh.tmpl
  examples/kerberized_data_lake/scripts/init-actions/setup-users-config.sh.logic
  examples/kerberized_data_lake/scripts/init-actions/setup-users-config.sh.tmpl
  examples/kerberized_data_lake/scripts/shutdown-scripts/shutdown-cleanup-trust.sh.logic
  examples/kerberized_data_lake/scripts/shutdown-scripts/shutdown-cleanup-trust.sh.tmpl
  examples/kerberized_data_lake/scripts/stage-generated-secrets.sh
  examples/kerberized_data_lake/variables.tf
  examples/kerberized_data_lake/version.tf
  license-templates/LICENSE.txt
Labels: cla: yes

#581 gce-usage-log: add filter on active projects
  tools/gce-usage-log/.gitignore
  tools/gce-usage-log/src/main/java/com/google/cloud/pso/gceusage/services/GCEHelper.java
Labels: cla: yes
