Repository GoogleCloudPlatform/professional-services, pull requests merged in 2020-05, with the labels that each got.

#470 New tool: gcs2bq
  README.md
  tools/gcs2bq/.gitignore
  tools/gcs2bq/Dockerfile
  tools/gcs2bq/README.md
  tools/gcs2bq/bigquery.schema
  tools/gcs2bq/datastudio.png
  tools/gcs2bq/gcs2bq-custom-role.yaml
  tools/gcs2bq/gcs2bq.avsc
  tools/gcs2bq/gcs2bq.yaml
  tools/gcs2bq/main.go
  tools/gcs2bq/run.sh
Labels: cla: yes

#467 test: add terraform config for Cloud Build trigger
  .gitignore
  CONTRIBUTING.md
  cloudbuild/README.md
  cloudbuild/main.tf
  cloudbuild/variables.tf
Labels: cla: yes

#476 Limiting flake to logical checks
  helpers/check_format.sh
Labels: cla: yes, size/XS

#480 Fix typo
  CONTRIBUTING.md
Labels: cla: yes, size/XS

#469 test: add shellcheck to CI tests
  CONTRIBUTING.md
  cloudbuild.yaml
  cloudbuild/Dockerfile
  examples/bigtable-change-key/scripts/copy_schema_to_new_table.sh
  examples/bigtable-change-key/scripts/create_sandbox_table.sh
  examples/dataproc-gcs-connector/build_gcs_connector.sh
  examples/dataproc-gcs-connector/connectors.sh
  helpers/check_format.sh
  helpers/exclusion_list.txt
  helpers/format.sh
  helpers/sort_lists.py
  tools/bigquery_user_info_updater_tool/cron/bigquery_user_updater.sh
  tools/dns-sync/dns_sync/connect_with_dns_sync.sh
  tools/gcs2bq/run.sh
  tools/snowflake2bq/bash/snowflake-bq.sh
Labels: cla: yes, size/L

#461 Include eventid and eventtimestamp fields as pubsub attributes
  examples/dataflow-streaming-benchmark/README.md
  examples/dataflow-streaming-benchmark/pom.xml
  examples/dataflow-streaming-benchmark/src/main/java/com/google/cloud/pso/pipeline/StreamingBenchmark.java
  examples/dataflow-streaming-benchmark/src/main/java/com/google/cloud/pso/pipeline/package-info.java
  examples/dataflow-streaming-benchmark/src/test/java/com/google/cloud/pso/pipeline/StreamingBenchmarkTest.java
Labels: cla: yes

#484 Remove GCP arch viz since it's moved to Forseti
  README.md
  tools/gcp-arch-viz/README.md
  tools/gcp-arch-viz/gcp-arch-viz.gif
  tools/gcp-arch-viz/gcp-arch-viz.html
  tools/gcp-arch-viz/gcp-data.csv
Labels: cla: yes, size/XS

#434 Add Cloud Functions implementation for gsuite exporter
  tools/gsuite-exporter-cloud-function/README.md
  tools/gsuite-exporter-cloud-function/deploy.sh
  tools/gsuite-exporter-cloud-function/main.py
  tools/gsuite-exporter-cloud-function/requirements.txt
Labels: cla: yes, size/L

#490 README cleanup. Linked to tool in the main README
  README.md
  tools/gsuite-exporter-cloud-function/README.md
Labels: cla: yes, size/M

#494 Add direct runner to pipeline
  examples/bigtable-change-key/pom.xml
Labels: cla: yes, size/XS

#493 Column family names not correctly extracted in helper script
  examples/bigtable-change-key/scripts/copy_schema_to_new_table.sh
Labels: cla: yes, size/XS

#381 update dataflow python examples #378
  examples/dataflow-python-examples/dataflow_python_examples/__init__.py
  examples/dataflow-python-examples/dataflow_python_examples/data_enrichment.py
  examples/dataflow-python-examples/dataflow_python_examples/data_ingestion.py
  examples/dataflow-python-examples/dataflow_python_examples/data_ingestion_configurable.py
  examples/dataflow-python-examples/dataflow_python_examples/data_lake_to_mart.py
  examples/dataflow-python-examples/dataflow_python_examples/data_lake_to_mart_cogroupbykey.py
  examples/dataflow-python-examples/dataflow_python_examples/data_transformation.py
  examples/dataflow-python-examples/dataflow_python_examples/datastore_schema_import.py
  examples/dataflow-python-examples/dataflow_python_examples/image_labels.py
  examples/dataflow-python-examples/requirements.txt
  examples/dataflow-python-examples/tests/test_image_labels.py
  examples/dataflow-python-examples/tests/test_parsing_logic.py
Labels: cla: yes

#483 examples how to write unit tests for tensorflow
  README.md
  examples/tensorflow-unit-testing/README.md
  examples/tensorflow-unit-testing/example.py
  examples/tensorflow-unit-testing/example_test.py
Labels: cla: yes, size/L

#495 Exchange stream fix
  examples/cryptorealtime/src/main/java/run/RunThePipeline.java
Labels: cla: yes
