Repository GoogleCloudPlatform/professional-services, pull requests merged in 2021-04, with the labels that each got.

#636 Ansible module for installation of Anthos on Bare Metal
  README.md
  tools/anthosbm-ansible-module/README.md
  tools/anthosbm-ansible-module/ansible.cfg
  tools/anthosbm-ansible-module/anthos.yml
  tools/anthosbm-ansible-module/inventory/hosts.yml
  tools/anthosbm-ansible-module/roles/anthos/files/cloud-console-reader.yaml
  tools/anthosbm-ansible-module/roles/anthos/tasks/main.yml
  tools/anthosbm-ansible-module/roles/anthos/templates/cluster.yaml.j2
  tools/anthosbm-ansible-module/roles/bmctl-tool/tasks/main.yml
  tools/anthosbm-ansible-module/roles/connect-gateway/tasks/main.yml
  tools/anthosbm-ansible-module/roles/connect-gateway/templates/admin-permission.yaml.j2
  tools/anthosbm-ansible-module/roles/connect-gateway/templates/impersonate.yaml.j2
  tools/anthosbm-ansible-module/roles/gcloud-sdk/tasks/main.yml
  tools/anthosbm-ansible-module/roles/kubectl-tool/tasks/main.yml
  tools/anthosbm-ansible-module/roles/rhel-prereq/tasks/main.yml
  tools/anthosbm-ansible-module/roles/service-accounts/tasks/main.yml
  tools/anthosbm-ansible-module/roles/ubuntu-prereq/tasks/main.yml
  tools/anthosbm-ansible-module/roles/ws-docker/tasks/main.yml
  tools/anthosbm-ansible-module/vars/anthos_vars.yml
Labels: cla: yes, size/XXL

#637 updated for correcting name of ansible module for anthos on bare metal
  README.md
Labels: cla: yes, size/XS

#640 Update variables.tf
  examples/dataflow-production-ready/terraform/modules/bigquery/variables.tf
Labels: cla: yes, size/XS

#639 Fix java formatting As it breaks Cloud Build
  helpers/check_format.sh
  helpers/exclusion_list.txt
  helpers/format.sh
Labels: cla: yes, size/S

#642 remove quota-monitoring-alerting from the exclusion list
  helpers/exclusion_list.txt
Labels: cla: yes, size/XS

#641 Toptalkers
  README.md
  tools/vpc-flowlogs-analysis/main.tf
  tools/vpc-flowlogs-toptalkers/README.md
  tools/vpc-flowlogs-toptalkers/asset/example_report.png
  tools/vpc-flowlogs-toptalkers/ip-range-labels.yaml
  tools/vpc-flowlogs-toptalkers/ip-range-labels/main.py
  tools/vpc-flowlogs-toptalkers/ip-range-labels/requirements.txt
  tools/vpc-flowlogs-toptalkers/labels.yaml
  tools/vpc-flowlogs-toptalkers/main.tf
  tools/vpc-flowlogs-toptalkers/routines.tf
  tools/vpc-flowlogs-toptalkers/terraform.tfvars.example
  tools/vpc-flowlogs-toptalkers/update-ip-range-labels.sh
  tools/vpc-flowlogs-toptalkers/variables.tf
  tools/vpc-flowlogs-toptalkers/views.tf
Labels: cla: yes

#643 [gsuite-exporter] Fix auth problem + bump patch version
  tools/gsuite-exporter/gsuite_exporter/auth.py
  tools/gsuite-exporter/setup.py
Labels: cla: yes, size/M

#630 Add SQL scripts required for Cost Optimization DataStudio Dashboard
  README.md
  examples/cost-optimization-dashboard/README.md
  examples/cost-optimization-dashboard/scripts/billing_dashboard_view.sql
  examples/cost-optimization-dashboard/scripts/co_billing_data.sql
  examples/cost-optimization-dashboard/scripts/co_dashboard_view.sql
  examples/cost-optimization-dashboard/scripts/co_pricing_data.sql
  examples/cost-optimization-dashboard/scripts/co_recommendations_data.sql
  examples/cost-optimization-dashboard/scripts/co_recommendations_view.sql
  examples/cost-optimization-dashboard/scripts/common_functions.sql
Labels: cla: yes, size/XL
