Repository GoogleCloudPlatform/professional-services, pull requests merged in 2021-07, with the labels that each got.

#644 New tool: Firewall Enforcer
  README.md
  tools/firewall-enforcer/.gitignore
  tools/firewall-enforcer/.tfvars
  tools/firewall-enforcer/README.md
  tools/firewall-enforcer/function/main.py
  tools/firewall-enforcer/function/requirements.txt
  tools/firewall-enforcer/function/samples.py
  tools/firewall-enforcer/main.tf
  tools/firewall-enforcer/providers.tf
  tools/firewall-enforcer/variables.tf
Labels: cla: yes, size/L

#666 Issue 665: Don't fail when there are no resources in the API schema.
  tools/asset-inventory/asset_inventory/api_schema.py
  tools/asset-inventory/asset_inventory/import_pipeline_metadata
Labels: cla: yes, size/XS

#664 Anthos CICD with Gitlab Guide
  README.md
  examples/anthos-cicd-with-gitlab/.gitignore
  examples/anthos-cicd-with-gitlab/README.md
  examples/anthos-cicd-with-gitlab/docs/1-prerequisites.md
  examples/anthos-cicd-with-gitlab/docs/2-register-gke-clusters-with-anthos.md
  examples/anthos-cicd-with-gitlab/docs/3-set-up-anthos-config-management.md
  examples/anthos-cicd-with-gitlab/docs/4-cicd-with-anthos-and-gitlab.md
  examples/anthos-cicd-with-gitlab/docs/images/create-blank-project.png
  examples/anthos-cicd-with-gitlab/docs/images/deploy-ssh-keys.png
  examples/anthos-cicd-with-gitlab/docs/images/environment-variables.png
  examples/anthos-cicd-with-gitlab/docs/images/registration-token.png
  examples/anthos-cicd-with-gitlab/src/acm/README.md
  examples/anthos-cicd-with-gitlab/src/acm/cluster/constraint-restrict-privileged-container.yaml
  examples/anthos-cicd-with-gitlab/src/acm/clusterregistry/dev-cluster-selector.yaml
  examples/anthos-cicd-with-gitlab/src/acm/clusterregistry/prod-cluster-selector.yaml
  examples/anthos-cicd-with-gitlab/src/acm/namespaces/dev/namespace.yaml
  examples/anthos-cicd-with-gitlab/src/acm/namespaces/gitlab-rbac.yaml
  examples/anthos-cicd-with-gitlab/src/acm/namespaces/operations/gitlab/config-map.yaml
  examples/anthos-cicd-with-gitlab/src/acm/namespaces/operations/gitlab/deployment.yaml
  examples/anthos-cicd-with-gitlab/src/acm/namespaces/operations/gitlab/namespace.yaml
  examples/anthos-cicd-with-gitlab/src/acm/namespaces/operations/gitlab/service-account.yaml
  examples/anthos-cicd-with-gitlab/src/acm/namespaces/prod/namespace.yaml
  examples/anthos-cicd-with-gitlab/src/acm/namespaces/stage/namespace.yaml
  examples/anthos-cicd-with-gitlab/src/acm/setup/config-management-dev.yaml
  examples/anthos-cicd-with-gitlab/src/acm/setup/config-management-operator.yaml
  examples/anthos-cicd-with-gitlab/src/acm/setup/config-management-prod.yaml
  examples/anthos-cicd-with-gitlab/src/acm/system/README.md
  examples/anthos-cicd-with-gitlab/src/acm/system/repo.yaml
  examples/anthos-cicd-with-gitlab/src/hello-kubernetes/Dockerfile
  examples/anthos-cicd-with-gitlab/src/hello-kubernetes/README.md
  examples/anthos-cicd-with-gitlab/src/hello-kubernetes/app/package-lock.json
  examples/anthos-cicd-with-gitlab/src/hello-kubernetes/app/package.json
  examples/anthos-cicd-with-gitlab/src/hello-kubernetes/app/server.js
  examples/anthos-cicd-with-gitlab/src/hello-kubernetes/app/static/css/main.css
  examples/anthos-cicd-with-gitlab/src/hello-kubernetes/app/static/images/kubernetes.png
  examples/anthos-cicd-with-gitlab/src/hello-kubernetes/app/views/home.handlebars
  examples/anthos-cicd-with-gitlab/src/hello-kubernetes/app/views/layouts/main.handlebars
  examples/anthos-cicd-with-gitlab/src/hello-kubernetes/hello-kubernetes.png
  examples/anthos-cicd-with-gitlab/src/hello-kubernetes/kubernetes/overlays/dev/kustomization.yaml
  examples/anthos-cicd-with-gitlab/src/hello-kubernetes/kubernetes/overlays/prod/kustomization.yaml
  examples/anthos-cicd-with-gitlab/src/hello-kubernetes/kubernetes/overlays/stage/kustomization.yaml
  examples/anthos-cicd-with-gitlab/src/platform-admin/acm/download-policies.yaml
  examples/anthos-cicd-with-gitlab/src/platform-admin/acm/read-acm.yaml
  examples/anthos-cicd-with-gitlab/src/platform-admin/acm/validate-acm.yaml
  examples/anthos-cicd-with-gitlab/src/platform-admin/binauth/binauth.yaml
  examples/anthos-cicd-with-gitlab/src/platform-admin/build/build-container.yaml
  examples/anthos-cicd-with-gitlab/src/platform-admin/deploy/deploy-dev.yaml
  examples/anthos-cicd-with-gitlab/src/platform-admin/deploy/deploy-prod.yaml
  examples/anthos-cicd-with-gitlab/src/platform-admin/kustomize-steps/fetch-base.yaml
  examples/anthos-cicd-with-gitlab/src/platform-admin/kustomize-steps/hydrate-dev.yaml
  examples/anthos-cicd-with-gitlab/src/platform-admin/kustomize-steps/hydrate-prod.yaml
  examples/anthos-cicd-with-gitlab/src/platform-admin/shared-kustomize-bases/nodejs/deployment.yaml
  examples/anthos-cicd-with-gitlab/src/platform-admin/shared-kustomize-bases/nodejs/kustomization.yaml
  examples/anthos-cicd-with-gitlab/src/platform-admin/shared-kustomize-bases/nodejs/service.yaml
  examples/anthos-cicd-with-gitlab/src/platform-admin/vulnerability/vulnerability-scan-result.yaml
  examples/anthos-cicd-with-gitlab/src/platform-admin/vulnerability/vulnerability-scan-verify.yaml
Labels: cla: yes

#667 adding instructions for Slack Alerting for Quota Monitoring Tool
  tools/quota-monitoring-alerting/java/README.md
  tools/quota-monitoring-alerting/java/terraform/example.tfvars
  tools/quota-monitoring-alerting/java/terraform/terraform.tfvars
  tools/quota-monitoring-alerting/java/terraform/variables.tf
  tools/quota-monitoring-alerting/python/docs/manual_deploy.README.md
  tools/quota-monitoring-alerting/python/docs/terraform_deploy.README.md
Labels: cla: yes, size/M

#672 updated for Anthos BM 1.8.0
  tools/anthosbm-ansible-module/README.md
  tools/anthosbm-ansible-module/roles/rhel-prereq/tasks/main.yml
  tools/anthosbm-ansible-module/vars/anthos_vars.yml
Labels: cla: yes, size/M

#670 Updating Email alias in README for Quota MonitoringTool
  tools/quota-monitoring-alerting/java/README.md
Labels: cla: yes, size/XS

#669 create cluster command is missing \
  examples/anthos-cicd-with-gitlab/docs/2-register-gke-clusters-with-anthos.md
Labels: cla: yes, size/XS

#668 BQTag Alpha Version
  README.md
  tools/bqtag/.gitignore
  tools/bqtag/README.md
  tools/bqtag/bqtag/__init__.py
  tools/bqtag/bqtag/bqtag.py
  tools/bqtag/example/__init__.py
  tools/bqtag/example/example.py
  tools/bqtag/imgs/figure1.png
  tools/bqtag/requirements.txt
  tools/bqtag/setup.py
  tools/bqtag/tests/__init__.py
  tools/bqtag/tests/test_bqtag.py
Labels: cla: yes, size/XXL
