Repository GoogleCloudPlatform/professional-services, pull requests merged in 2021-12, with the labels that each got.

#731 Update to latest log4j dependency
  examples/dataflow-xmlio-to-bq/pom.xml
Labels: size/XS

#730 Update to latest log4j dependency
  examples/e2e-test-dataflow/pom.xml
Labels: size/XS

#728 Update SendNotification.java to write log entries synchronously
  tools/quota-monitoring-alerting/java/quota-notification/src/main/java/functions/SendNotification.java
Labels: size/XS

#734 Update to Beam 2.34 to avoid pulling log4j
  examples/dataflow-dlp-hash-pipeline/pom.xml
Labels: size/XS

#733 Update to Beam 2.34 to avoid pulling log4j
  examples/bigtable-change-key/pom.xml
Labels: size/XS

#735 Update to latest CDAP and don't pull unused deps that pull log4j 2.11
  examples/cloud-datafusion-functions-plugins/pom.xml
Labels: size/XS

#727 IPAM Autopilot tool for IP management
  .gitignore
  README.md
  tools/ipam-autopilot/.gitignore
  tools/ipam-autopilot/Dockerfile
  tools/ipam-autopilot/README.md
  tools/ipam-autopilot/container/.dockerignore
  tools/ipam-autopilot/container/.gitignore
  tools/ipam-autopilot/container/api.go
  tools/ipam-autopilot/container/cai.go
  tools/ipam-autopilot/container/data_access.go
  tools/ipam-autopilot/container/go.mod
  tools/ipam-autopilot/container/go.sum
  tools/ipam-autopilot/container/ipam_test.go
  tools/ipam-autopilot/container/main.go
  tools/ipam-autopilot/container/migrate.go
  tools/ipam-autopilot/container/migrations/1632132107_create_routing_domains_table.down.sql
  tools/ipam-autopilot/container/migrations/1632132107_create_routing_domains_table.up.sql
  tools/ipam-autopilot/container/migrations/1632132108_create_subnets_table.down.sql
  tools/ipam-autopilot/container/migrations/1632132108_create_subnets_table.up.sql
  tools/ipam-autopilot/container/migrations/1632132109_populate_sample_data.up.sql
  tools/ipam-autopilot/container/provider_registry.go
  tools/ipam-autopilot/examples/example-with-multiple-ranges/main.tf
  tools/ipam-autopilot/examples/simple-example/main.tf
  tools/ipam-autopilot/examples/vpc-example/main.tf
  tools/ipam-autopilot/img/architecture.png
  tools/ipam-autopilot/infrastructure/.gitignore
  tools/ipam-autopilot/infrastructure/cloudsql.tf
  tools/ipam-autopilot/infrastructure/main.tf
  tools/ipam-autopilot/infrastructure/providers.tf
  tools/ipam-autopilot/infrastructure/storage.tf
  tools/ipam-autopilot/infrastructure/templates/shasum.tpl
  tools/ipam-autopilot/infrastructure/templates/version_json.tpl
  tools/ipam-autopilot/infrastructure/templates/versions_json.tpl
  tools/ipam-autopilot/infrastructure/variables.tf
  tools/ipam-autopilot/provider/Makefile
  tools/ipam-autopilot/provider/go.mod
  tools/ipam-autopilot/provider/go.sum
  tools/ipam-autopilot/provider/ipam/config/config.go
  tools/ipam-autopilot/provider/ipam/provider.go
  tools/ipam-autopilot/provider/ipam/provider_test.go
  tools/ipam-autopilot/provider/ipam/resources/resource_ip_range.go
  tools/ipam-autopilot/provider/ipam/resources/resource_routing_domain.go
  tools/ipam-autopilot/provider/main.go
Labels: cla: yes, size/XXL

#738 Heavy rebase of the vm-migrator
  tools/vm-migrator/Makefile
  tools/vm-migrator/Readme.md
  tools/vm-migrator/export.csv
  tools/vm-migrator/migrator/disk.py
  tools/vm-migrator/migrator/subnet.py
  tools/vm-migrator/migrator/subnet_region_migrator.py
  tools/vm-migrator/requirements.txt
  tools/vm-migrator/setup.py
  tools/vm-migrator/source.csv
  tools/vm-migrator/src/migrator/.gitignore
  tools/vm-migrator/src/migrator/__init__.py
  tools/vm-migrator/src/migrator/disk.py
  tools/vm-migrator/src/migrator/exceptions.py
  tools/vm-migrator/src/migrator/fields.py
  tools/vm-migrator/src/migrator/instance.py
  tools/vm-migrator/src/migrator/machine_image.py
  tools/vm-migrator/src/migrator/machine_type_mapping.py
  tools/vm-migrator/src/migrator/node_group_mapping.py
  tools/vm-migrator/src/migrator/project.py
  tools/vm-migrator/src/migrator/subnet.py
  tools/vm-migrator/src/migrator/subnet_region_migrator.py
  tools/vm-migrator/src/migrator/uri.py
  tools/vm-migrator/src/migrator/zone_mapping.py
  tools/vm-migrator/test/test_uri.py
Labels: size/XXL

#729 Dbt on composer
  examples/dbt-on-cloud-composer/README.md
  examples/dbt-on-cloud-composer/basic/dbt-project/.dbt/profiles.yml
  examples/dbt-on-cloud-composer/basic/dbt-project/cloudbuild.yaml
  examples/dbt-on-cloud-composer/optimized/dbt-project/.dbt/profiles.yml
  examples/dbt-on-cloud-composer/optimized/dbt-project/cloudbuild.yaml
Labels: size/M

#740 fix go dependencies
  examples/direct-upload-to-gcs/appengine/.gcloudignore
  examples/direct-upload-to-gcs/appengine/go.mod
  examples/direct-upload-to-gcs/appengine/go.sum
Labels: size/S

#741 removed duplicated manage from Readme
  tools/ipam-autopilot/README.md
Labels: size/XS

#744 Pubsub2inbox: add environment variables
  tools/pubsub2inbox/main.py
Labels: size/XS
