Repository GoogleCloudPlatform/professional-services, pull requests merged in 2021-05, with the labels that each got.

#649 Fix to support for non 'us' keys, Add support to Global KMS keys and Key update
  tools/gce-google-keys-to-cmek/README.md
  tools/gce-google-keys-to-cmek/main.py
Labels: cla: yes, size/M

#646 README.md update
  README.md
  examples/anthos-service-mesh-multicluster/README.md
  examples/anthos-service-mesh-multicluster/postgres/Istio-Sidecar.md
  examples/anthos-service-mesh-multicluster/postgres/README.md
Labels: cla: yes, size/M

#651 Fix main.py as it fails on VMs with multiple disks and regional keys
  tools/gce-google-keys-to-cmek/main.py
Labels: cla: yes, size/S

#647 Do not explicitly specify COS where not needed
  examples/redis-cluster-gke/README.md
Labels: cla: yes, size/XS

#604 BQMan: BigQuery Schema Management tool
  Makefile
  README.md
  tools/bqman/Makefile
  tools/bqman/README.md
  tools/bqman/golang/bqadmin/bqadmin.go
  tools/bqman/golang/bqhandler/bqhandler.go
  tools/bqman/golang/bqman.go
  tools/bqman/golang/bqman_test.go
  tools/bqman/golang/configparser/configparser.go
  tools/bqman/golang/connector/spreadsheet2bq.go
  tools/bqman/golang/connector/spreadsheethandler.go
  tools/bqman/golang/connector/sqlserverhandler.go
  tools/bqman/golang/controller/trotter.go
  tools/bqman/golang/executionmode/executionmode.go
  tools/bqman/golang/gcshandler/gcshandler.go
  tools/bqman/golang/go.mod
  tools/bqman/golang/go.sum
  tools/bqman/golang/projecthandler/projecthandler.go
  tools/bqman/golang/util/errorhandler.go
  tools/bqman/golang/util/fileutil.go
  tools/bqman/golang/util/showinfo.go
  tools/bqman/testdata/GlobalTest.properties
  tools/bqman/testdata/TestProcessBackup.properties
  tools/bqman/testdata/TestProcessImportSpreadsheet.properties
  tools/bqman/testdata/TestProcessImportSqlserver.properties
  tools/bqman/testdata/TestProcessPatch/bq-metadata-manager:sec_au.calculation.schema
  tools/bqman/testdata/TestProcessPull.properties
  tools/bqman/testdata/TestProcessRestore.properties
  tools/bqman/testdata/TestProcessUpdate/bq-metadata-manager:sec_au.calculation.schema
Labels: cla: yes, size/XXL

#652 New example: Terraform ILB example.
  README.md
  examples/terraform-ilb/README.md
  examples/terraform-ilb/main.tf
  examples/terraform-ilb/outputs.tf
  examples/terraform-ilb/variables.tf
Labels: cla: yes, size/L

#635 New Tool - Quota Monitoring and Alerting
  README.md
  tools/quota-monitoring-alerting/.gitignore
  tools/quota-monitoring-alerting/README.md
  tools/quota-monitoring-alerting/img/datastudio_schedule_email.png
  tools/quota-monitoring-alerting/img/ds_copy.png
  tools/quota-monitoring-alerting/img/ds_copy_report.png
  tools/quota-monitoring-alerting/img/ds_data_source_config_step_2.png
  tools/quota-monitoring-alerting/img/ds_data_source_config_step_3.png
  tools/quota-monitoring-alerting/img/ds_datasource_config_step_1.png
  tools/quota-monitoring-alerting/img/ds_edit_data_source.png
  tools/quota-monitoring-alerting/img/ds_edit_data_source_big_query.png
  tools/quota-monitoring-alerting/img/ds_region_datasource_config.png
  tools/quota-monitoring-alerting/img/ds_switch_view_mode.png
  tools/quota-monitoring-alerting/img/ds_template.png
  tools/quota-monitoring-alerting/img/ds_template_copy.png
  tools/quota-monitoring-alerting/img/edit_terraform_variables.png
  tools/quota-monitoring-alerting/img/quota-monitoring-alerting-architecture.png
  tools/quota-monitoring-alerting/img/quota_monitoring_key_features.png
  tools/quota-monitoring-alerting/img/run_cloud_scheduler.png
  tools/quota-monitoring-alerting/img/service_account_roles.png
  tools/quota-monitoring-alerting/img/test_bigquery_table.png
  tools/quota-monitoring-alerting/quota-notification/pom.xml
  tools/quota-monitoring-alerting/quota-notification/src/main/java/functions/SendNotification.java
  tools/quota-monitoring-alerting/quota-notification/src/main/java/functions/eventpojos/PubSubMessage.java
  tools/quota-monitoring-alerting/quota-notification/src/test/java/functions/SendNotificationTest.java
  tools/quota-monitoring-alerting/quota-scan/input.json
  tools/quota-monitoring-alerting/quota-scan/pom.xml
  tools/quota-monitoring-alerting/quota-scan/src/main/java/functions/ListProjects.java
  tools/quota-monitoring-alerting/quota-scan/src/main/java/functions/ScanProject.java
  tools/quota-monitoring-alerting/quota-scan/src/main/java/functions/ScanProjectHelper.java
  tools/quota-monitoring-alerting/quota-scan/src/main/java/functions/eventpojos/Notification.java
  tools/quota-monitoring-alerting/quota-scan/src/main/java/functions/eventpojos/PubSubMessage.java
  tools/quota-monitoring-alerting/terraform/main.tf
  tools/quota-monitoring-alerting/terraform/terraform.tfvars
  tools/quota-monitoring-alerting/terraform/variables.tf
Labels: cla: yes
