Repository GoogleCloudPlatform/professional-services, pull requests merged in 2021-01, with the labels that each got.

#593 Update gce-quota-sync.py
  tools/gce-quota-sync/gce-quota-sync.py
Labels: cla: yes, size/XS

#596 Change call to get_bq_schema_string()
  examples/dataflow-data-generator/data-generator-pipeline/data_generator_joinable_table.py
Labels: cla: yes, size/XS

#588 VM Migrator to move VM's between GCP zones, regions & projects
  README.md
  tools/vm-migrator/.gitignore
  tools/vm-migrator/Makefile
  tools/vm-migrator/Readme.md
  tools/vm-migrator/export.csv
  tools/vm-migrator/filter.csv
  tools/vm-migrator/instances.csv
  tools/vm-migrator/migrator/.gitignore
  tools/vm-migrator/migrator/__init__.py
  tools/vm-migrator/migrator/disk.py
  tools/vm-migrator/migrator/exceptions.py
  tools/vm-migrator/migrator/fields.py
  tools/vm-migrator/migrator/instance.py
  tools/vm-migrator/migrator/machine_image.py
  tools/vm-migrator/migrator/machine_type_mapping.py
  tools/vm-migrator/migrator/node_group_mapping.py
  tools/vm-migrator/migrator/subnet.py
  tools/vm-migrator/migrator/subnet_region_migrator.py
  tools/vm-migrator/migrator/zone_mapping.py
  tools/vm-migrator/pylintrc
  tools/vm-migrator/requirements.txt
  tools/vm-migrator/run.sh
  tools/vm-migrator/setup.py
  tools/vm-migrator/source.csv
Labels: cla: yes

#590 Creating Anthos Service Mesh example
  README.md
  examples/anthos-service-mesh-multicluster/.gitignore
  examples/anthos-service-mesh-multicluster/.shellcheckrc
  examples/anthos-service-mesh-multicluster/README.md
  examples/anthos-service-mesh-multicluster/asm-private-multiclusters-intranet.png
  examples/anthos-service-mesh-multicluster/infrastructure/anthos-service-accounts.tf
  examples/anthos-service-mesh-multicluster/infrastructure/application-firewalls.tf
  examples/anthos-service-mesh-multicluster/infrastructure/backend.tf_tmpl
  examples/anthos-service-mesh-multicluster/infrastructure/bastion.tf
  examples/anthos-service-mesh-multicluster/infrastructure/clusters.tf
  examples/anthos-service-mesh-multicluster/infrastructure/firewalls.tf
  examples/anthos-service-mesh-multicluster/infrastructure/network.tf
  examples/anthos-service-mesh-multicluster/infrastructure/projects.tf
  examples/anthos-service-mesh-multicluster/infrastructure/providers.tf
  examples/anthos-service-mesh-multicluster/infrastructure/shared.tf
  examples/anthos-service-mesh-multicluster/infrastructure/terraform.example.tfvars
  examples/anthos-service-mesh-multicluster/infrastructure/variables.tf
  examples/anthos-service-mesh-multicluster/istio-profiles/internal-load-balancer.yaml
  examples/anthos-service-mesh-multicluster/postgres/Dockerfile
  examples/anthos-service-mesh-multicluster/postgres/Istio-Sidecar.md
  examples/anthos-service-mesh-multicluster/postgres/README.md
  examples/anthos-service-mesh-multicluster/postgres/destination-rule.yaml
  examples/anthos-service-mesh-multicluster/postgres/postgres-cloudproxy.yaml
  examples/anthos-service-mesh-multicluster/postgres/postgres-istio.yaml
  examples/anthos-service-mesh-multicluster/postgres/postgres-plain.yaml
  examples/anthos-service-mesh-multicluster/postgres/service-account.yaml
  examples/anthos-service-mesh-multicluster/postgres/service-entry.yaml
  examples/anthos-service-mesh-multicluster/scripts/main.sh
  examples/anthos-service-mesh-multicluster/twistlock/README.md
  examples/anthos-service-mesh-multicluster/twistlock/install_defender.sh
  examples/anthos-service-mesh-multicluster/vars.sh
Labels: cla: yes

#583 initial checkin of Reusable Cloud Data Fusion Functions / Plugins
  .gitignore
  README.md
  examples/cloud-datafusion-functions-plugins/.gitignore
  examples/cloud-datafusion-functions-plugins/README.md
  examples/cloud-datafusion-functions-plugins/img/1-create_pipeline_checkpoint_collection.png
  examples/cloud-datafusion-functions-plugins/img/10-checkpoint_read_action_ui_pipeline_parameters.png
  examples/cloud-datafusion-functions-plugins/img/11-truncate_table_action_ui_pipeline_parameters.png
  examples/cloud-datafusion-functions-plugins/img/12-database_source_ui_pipeline_parameters.png
  examples/cloud-datafusion-functions-plugins/img/13-bigquery_sink_ui_pipeline_parameters.png
  examples/cloud-datafusion-functions-plugins/img/14-merge_last_update_ts_action.png
  examples/cloud-datafusion-functions-plugins/img/15-checkpoint_update_action_ui_pipeline_parameters.png
  examples/cloud-datafusion-functions-plugins/img/2-create_check_point_collection.png
  examples/cloud-datafusion-functions-plugins/img/3-runtime_arguments.png
  examples/cloud-datafusion-functions-plugins/img/4-checkpoint_read_action_plugin_ui.png
  examples/cloud-datafusion-functions-plugins/img/5-checkpoint_update_action_plugin_ui.png
  examples/cloud-datafusion-functions-plugins/img/6-copy_table_action_ui.png
  examples/cloud-datafusion-functions-plugins/img/7-drop_table_action_ui.png
  examples/cloud-datafusion-functions-plugins/img/8-truncate_table_action_ui.png
  examples/cloud-datafusion-functions-plugins/img/9-set_runtime_arugments_latestWatermarkValue.png
  examples/cloud-datafusion-functions-plugins/img/9-successful_run_incremental_v2_pipeline.png
  examples/cloud-datafusion-functions-plugins/pom.xml
  examples/cloud-datafusion-functions-plugins/src/main/java/com/google/cloud/pso/common/GCPConfig.java
  examples/cloud-datafusion-functions-plugins/src/main/java/com/google/cloud/pso/common/GCPReferenceSinkConfig.java
  examples/cloud-datafusion-functions-plugins/src/main/java/com/google/cloud/pso/common/GCPUtils.java
  examples/cloud-datafusion-functions-plugins/src/main/java/com/google/cloud/pso/firestore/dao/CheckpointDAO.java
  examples/cloud-datafusion-functions-plugins/src/main/java/com/google/cloud/pso/functions/CheckPointReadFunction.java
  examples/cloud-datafusion-functions-plugins/src/main/java/com/google/cloud/pso/functions/CheckPointUpdateFunction.java
  examples/cloud-datafusion-functions-plugins/src/main/java/com/google/cloud/pso/functions/DropTableFunction.java
  examples/cloud-datafusion-functions-plugins/src/main/java/com/google/cloud/pso/functions/InsertOverwriteFunction.java
  examples/cloud-datafusion-functions-plugins/src/main/java/com/google/cloud/pso/functions/MergeLastUpdateTSFunction.java
  examples/cloud-datafusion-functions-plugins/src/main/java/com/google/cloud/pso/functions/TruncateTableFunction.java
  examples/cloud-datafusion-functions-plugins/src/main/java/com/google/cloud/pso/functions/Utils.java
  examples/cloud-datafusion-functions-plugins/src/main/java/com/google/cloud/pso/plugin/CheckPointReadAction.java
  examples/cloud-datafusion-functions-plugins/src/main/java/com/google/cloud/pso/plugin/CheckPointUpdateAction.java
  examples/cloud-datafusion-functions-plugins/src/main/java/com/google/cloud/pso/plugin/CopyTableAction.java
  examples/cloud-datafusion-functions-plugins/src/main/java/com/google/cloud/pso/plugin/DropTableAction.java
  examples/cloud-datafusion-functions-plugins/src/main/java/com/google/cloud/pso/plugin/MergeLastUpdateTSAction.java
  examples/cloud-datafusion-functions-plugins/src/main/java/com/google/cloud/pso/plugin/TruncateTableAction.java
  examples/cloud-datafusion-functions-plugins/widgets/CheckPointReadAction-action.json
  examples/cloud-datafusion-functions-plugins/widgets/CheckPointUpdateAction-action.json
  examples/cloud-datafusion-functions-plugins/widgets/CopyTableAction-action.json
  examples/cloud-datafusion-functions-plugins/widgets/DropTableAction-action.json
  examples/cloud-datafusion-functions-plugins/widgets/MergeLastUpdateTSAction-action.json
  examples/cloud-datafusion-functions-plugins/widgets/TruncateTableAction-action.json
Labels: cla: yes

#600 [gmon] Support Cloud Monitoring API filters
  tools/gmon/README.md
  tools/gmon/gmon/cli.py
  tools/gmon/gmon/clients/monitoring.py
  tools/gmon/setup.py
Labels: cla: yes, size/S
