Repository GoogleCloudPlatform/professional-services, pull requests merged in 2021-06, with the labels that each got.

#658 Update README.md
  examples/dataflow-python-examples/batch-examples/cookbook-examples/README.md
Labels: cla: yes, size/XS

#660 Update README
  examples/cost-optimization-dashboard/README.md
  examples/cost-optimization-dashboard/docs/image1.png
  examples/cost-optimization-dashboard/docs/image10.png
  examples/cost-optimization-dashboard/docs/image11.png
  examples/cost-optimization-dashboard/docs/image12.png
  examples/cost-optimization-dashboard/docs/image13.png
  examples/cost-optimization-dashboard/docs/image2.png
  examples/cost-optimization-dashboard/docs/image3.png
  examples/cost-optimization-dashboard/docs/image4.png
  examples/cost-optimization-dashboard/docs/image5.png
  examples/cost-optimization-dashboard/docs/image6.png
  examples/cost-optimization-dashboard/docs/image7.png
  examples/cost-optimization-dashboard/docs/image8.png
  examples/cost-optimization-dashboard/docs/image9.png
Labels: cla: yes

#656 New tool: Airpiler
  README.md
  tools/airpiler/README.md
  tools/airpiler/airpiler.py
  tools/airpiler/requirements.txt
Labels: cla: yes, size/XL

#661 Python Dataflow code example optimize
  examples/dataflow-python-examples/batch-examples/cookbook-examples/pipelines/data_ingestion_configurable.py
  examples/dataflow-python-examples/batch-examples/cookbook-examples/pipelines/data_transformation.py
  tools/gce-usage-log/.gitignore
  tools/gce-usage-log/src/main/java/com/google/cloud/pso/gceusage/services/GCEHelper.java
  tools/iam-recommender-at-scale/README.md
Labels: cla: yes

#662 add examples to airpiler dir
  tools/airpiler/README.md
  tools/airpiler/examples/use-case1.jil
  tools/airpiler/examples/use-case2.jil
Labels: cla: yes, size/M

#663 Pubsub2Inbox enhancements (GCS copier, GCS read, filemagic)
  tools/pubsub2inbox/README.md
  tools/pubsub2inbox/examples/bigquery-example.yaml
  tools/pubsub2inbox/examples/budget-config.yaml
  tools/pubsub2inbox/examples/gcscopy-example.yaml
  tools/pubsub2inbox/examples/generic-config.yaml
  tools/pubsub2inbox/examples/monitoring-config.yaml
  tools/pubsub2inbox/examples/recommendations-example.yaml
  tools/pubsub2inbox/examples/scc-config.yaml
  tools/pubsub2inbox/examples/storage-example.yaml
  tools/pubsub2inbox/filters/__init__.py
  tools/pubsub2inbox/filters/strings.py
  tools/pubsub2inbox/main.py
  tools/pubsub2inbox/main.tf
  tools/pubsub2inbox/output/gcscopy.py
  tools/pubsub2inbox/output/logger.py
  tools/pubsub2inbox/requirements.txt
  tools/pubsub2inbox/variables.tf
Labels: cla: yes, size/L
