Repository GoogleCloudPlatform/professional-services, pull requests merged in 2021-02, with the labels that each got.

#599 598: Added explanation for gcs_output_prefix parameter in README
  examples/dataflow-data-generator/README.md
Labels: cla: yes, size/XS

#606 Removing disrespectful terms
  examples/anthos-service-mesh-multicluster/README.md
  examples/anthos-service-mesh-multicluster/asm-private-multiclusters-intranet.png
Labels: cla: yes

#576 Creating BigQuery -> XML export tool
  README.md
  tools/bigquery-to-xml/README.md
  tools/bigquery-to-xml/bigquery_to_xml/__init__.py
  tools/bigquery-to-xml/bigquery_to_xml/bigquery_to_xml.py
  tools/bigquery-to-xml/requirements.txt
  tools/bigquery-to-xml/test_nested_repeated.py
  tools/bigquery-to-xml/tests/results.txt
Labels: cla: yes, size/L

#602 Initial commit of VPC FlowLogs Analysis
  README.md
  tools/vpc-flowlogs-analysis/README.md
  tools/vpc-flowlogs-analysis/asset/example_report.png
  tools/vpc-flowlogs-analysis/backend.tf.example
  tools/vpc-flowlogs-analysis/main.tf
  tools/vpc-flowlogs-analysis/variables.tf
Labels: cla: yes

#609 Add pubsub2inbox tool
  README.md
  tools/pubsub2inbox/.gcloudignore
  tools/pubsub2inbox/README.md
  tools/pubsub2inbox/examples/bigquery-example.yaml
  tools/pubsub2inbox/examples/budget-config.yaml
  tools/pubsub2inbox/examples/generic-config.yaml
  tools/pubsub2inbox/examples/scc-config.yaml
  tools/pubsub2inbox/examples/storage-example.yaml
  tools/pubsub2inbox/filters/__init__.py
  tools/pubsub2inbox/filters/date.py
  tools/pubsub2inbox/filters/lists.py
  tools/pubsub2inbox/filters/regex.py
  tools/pubsub2inbox/filters/strings.py
  tools/pubsub2inbox/helpers/grant-gsuite-role.py
  tools/pubsub2inbox/img/logo.png
  tools/pubsub2inbox/img/sample-logo-small.png
  tools/pubsub2inbox/main.py
  tools/pubsub2inbox/main.tf
  tools/pubsub2inbox/output/base.py
  tools/pubsub2inbox/output/gcs.py
  tools/pubsub2inbox/output/mail.py
  tools/pubsub2inbox/output/webhook.py
  tools/pubsub2inbox/processors/base.py
  tools/pubsub2inbox/processors/bigquery.py
  tools/pubsub2inbox/processors/budget.py
  tools/pubsub2inbox/processors/genericjson.py
  tools/pubsub2inbox/processors/scc.py
  tools/pubsub2inbox/processors/storage.py
  tools/pubsub2inbox/requirements.txt
  tools/pubsub2inbox/test/__init__.py
  tools/pubsub2inbox/test/configs/budget.yaml
  tools/pubsub2inbox/test/fixtures/bigquery.json
  tools/pubsub2inbox/test/fixtures/budget.json
  tools/pubsub2inbox/test/fixtures/scc.json
  tools/pubsub2inbox/test/fixtures/storage.json
  tools/pubsub2inbox/test/helpers.py
  tools/pubsub2inbox/test/test_pubsub.py
  tools/pubsub2inbox/variables.tf
Labels: cla: yes, size/XXL

#612 gmon: Update to 1.1.1
  tools/gmon/setup.py
Labels: cla: yes, size/XS

#607 gcs-bucket-mover: Fix extra retry caused by unhandled exception
  tools/gcs-bucket-mover/gcs_bucket_mover/bucket_mover_service.py
Labels: cla: yes, size/M

#615 Correct link to Dataflow DLP Hashpipeline example
  README.md
Labels: cla: yes, size/XS

#613 asset_inventory: Fix/additional properties schema
  tools/asset-inventory/asset_inventory/bigquery_schema.py
  tools/asset-inventory/tests/test_bigquery_schema.py
Labels: cla: yes, size/L

#617 Add Secret Manager Helpers
  README.md
  tools/secret-manager-helper/.gitignore
  tools/secret-manager-helper/README.md
  tools/secret-manager-helper/cloudbuild.yaml
  tools/secret-manager-helper/config/checkstyle/checkstyle.xml
  tools/secret-manager-helper/config/checkstyle/suppressions.xml
  tools/secret-manager-helper/pom.xml
  tools/secret-manager-helper/src/main/java/com/google/cloud/secrethelper/SecretLookup.java
  tools/secret-manager-helper/src/main/java/com/google/cloud/secrethelper/SecretLookupToFile.java
  tools/secret-manager-helper/src/main/java/com/google/cloud/secrethelper/SecretManagerPropertiesExample.java
  tools/secret-manager-helper/src/main/java/com/google/cloud/secrethelper/SecretManagerStringSubstitutor.java
  tools/secret-manager-helper/src/test/java/com/google/cloud/secrethelper/SecretLookupTest.java
  tools/secret-manager-helper/src/test/java/com/google/cloud/secrethelper/SecretLookupToFileTest.java
  tools/secret-manager-helper/src/test/java/com/google/cloud/secrethelper/SecretManagerStringSubstitutorTest.java
  tools/secret-manager-helper/src/test/java/com/google/cloud/secrethelper/SecretManagerSubstitutorPropertiesTest.java
Labels: cla: yes
