Repository GoogleCloudPlatform/professional-services, pull requests merged in 2021-11, with the labels that each got.

#707 Dbt on cloud composer
  README.md
  examples/dataflow-python-examples/batch-examples/cookbook-examples/README.md
  examples/dbt-on-cloud-composer/README.md
  examples/dbt-on-cloud-composer/basic/dag/dbt_with_kubernetes.py
  examples/dbt-on-cloud-composer/basic/dbt-project/.dbt/profiles.yml
  examples/dbt-on-cloud-composer/basic/dbt-project/.dockerignore
  examples/dbt-on-cloud-composer/basic/dbt-project/.gitignore
  examples/dbt-on-cloud-composer/basic/dbt-project/Dockerfile
  examples/dbt-on-cloud-composer/basic/dbt-project/cloudbuild.yaml
  examples/dbt-on-cloud-composer/basic/dbt-project/dbt_project.yml
  examples/dbt-on-cloud-composer/basic/dbt-project/models/datamart/report.sql
  examples/dbt-on-cloud-composer/basic/dbt-project/models/intermediate/dim_users.sql
  examples/dbt-on-cloud-composer/basic/dbt-project/models/intermediate/fact_posts_daily.sql
  examples/dbt-on-cloud-composer/basic/dbt-project/models/raw/stackoverflow_posts.sql
  examples/dbt-on-cloud-composer/basic/dbt-project/models/raw/users.sql
  examples/dbt-on-cloud-composer/basic/dbt-project/models/sources.yml
  examples/dbt-on-cloud-composer/img/dbt-on-cloud-composer-diagram.PNG
  examples/dbt-on-cloud-composer/optimized/dag/dbt_with_kubernetes_optimized.py
  examples/dbt-on-cloud-composer/optimized/dbt-project/.dbt/profiles.yml
  examples/dbt-on-cloud-composer/optimized/dbt-project/.dockerignore
  examples/dbt-on-cloud-composer/optimized/dbt-project/.gitignore
  examples/dbt-on-cloud-composer/optimized/dbt-project/Dockerfile
  examples/dbt-on-cloud-composer/optimized/dbt-project/cloudbuild.yaml
  examples/dbt-on-cloud-composer/optimized/dbt-project/dbt_project.yml
  examples/dbt-on-cloud-composer/optimized/dbt-project/models/datamart/report.sql
  examples/dbt-on-cloud-composer/optimized/dbt-project/models/datamart/schema.yml
  examples/dbt-on-cloud-composer/optimized/dbt-project/models/intermediate/dim_users.sql
  examples/dbt-on-cloud-composer/optimized/dbt-project/models/intermediate/fact_posts_daily.sql
  examples/dbt-on-cloud-composer/optimized/dbt-project/models/intermediate/schema.yml
  examples/dbt-on-cloud-composer/optimized/dbt-project/models/raw/schema.yml
  examples/dbt-on-cloud-composer/optimized/dbt-project/models/raw/stackoverflow_posts.sql
  examples/dbt-on-cloud-composer/optimized/dbt-project/models/raw/users.sql
  examples/dbt-on-cloud-composer/optimized/dbt-project/models/sources.yml
  examples/dbt-on-cloud-composer/optimized/dbt-project/tests/.gitkeep
Labels: cla: yes, size/XXL

#716 [New example] XML to BigQuery via Dataflow
  README.md
  examples/dataflow-xmlio-to-bq/.gitattributes
  examples/dataflow-xmlio-to-bq/.gitignore
  examples/dataflow-xmlio-to-bq/README.md
  examples/dataflow-xmlio-to-bq/example_input/default.xml
  examples/dataflow-xmlio-to-bq/img/graph.png
  examples/dataflow-xmlio-to-bq/pom.xml
  examples/dataflow-xmlio-to-bq/run.sh
  examples/dataflow-xmlio-to-bq/src/main/java/xml2bq/Order.java
  examples/dataflow-xmlio-to-bq/src/main/java/xml2bq/ShipInfo.java
  examples/dataflow-xmlio-to-bq/src/main/java/xml2bq/XmlIoDemo.java
Labels: cla: yes, size/XXL

#717 [New Example]Adding Cloud Audit Log Examples
  README.md
  examples/audit-log-examples/README.md
  examples/audit-log-examples/cloud-identity/identity-add-groupmember.log
  examples/audit-log-examples/cloud-identity/identity-create-user.log
  examples/audit-log-examples/cloud-identity/identity-user-login.log
  examples/audit-log-examples/cloud-storage/gcs-admin-activity.log
  examples/audit-log-examples/cloud-storage/gcs-admin-set-iam-permissions.log
  examples/audit-log-examples/cloud-storage/gcs-data-access-object-create.log
  examples/audit-log-examples/cloud-storage/gcs-data-access-object-get.log
  examples/audit-log-examples/cloud-storage/gcs-data-access-object-list.log
  examples/audit-log-examples/cloud-storage/gcs-obj-vers.log
  examples/audit-log-examples/cloud-storage/gcs-usage.log
  examples/audit-log-examples/compute-engine/gce-admin-set-instance-metadata-instance.log
  examples/audit-log-examples/compute-engine/gce-admin-set-instance-metadata-project-2.log
  examples/audit-log-examples/compute-engine/gce-admin-set-instance-metadata-project.log
  examples/audit-log-examples/compute-engine/gce-os-agent-logging.log
  examples/audit-log-examples/kubernetes-engine/gke-admin-create-cluster.log
  examples/audit-log-examples/kubernetes-engine/gke-auditD.log
  examples/audit-log-examples/kubernetes-engine/gke-data-access-admin-read.log
  examples/audit-log-examples/kubernetes-engine/gke-intranode-visibility.log
  examples/audit-log-examples/kubernetes-engine/gke-k8s.log
  examples/audit-log-examples/network/cloud-cdn-response.log
  examples/audit-log-examples/network/create-dns-record.log
  examples/audit-log-examples/network/dns-query.log
  examples/audit-log-examples/network/firewall-rule.log
  examples/audit-log-examples/network/https-load-balancer-response.log
  examples/audit-log-examples/network/identity-aware-proxy.log
  examples/audit-log-examples/network/network-cloud-nat.log
  examples/audit-log-examples/network/network-vpc-flow.log
  examples/audit-log-examples/organization/org-policy-deny-service-account-creation.log
  examples/audit-log-examples/organization/org-policy-deny-service-account-key-creation.log
  examples/audit-log-examples/other/access-transparency.log
  examples/audit-log-examples/other/system-event.log
  examples/audit-log-examples/security-command-center/scc-bad-domain.log
  examples/audit-log-examples/security-command-center/scc-bad-ip.log
  examples/audit-log-examples/security-command-center/scc-coin-mining.log
  examples/audit-log-examples/security-command-center/scc-leaked-credentials.log
  examples/audit-log-examples/security-command-center/scc-outgoing-intrusion-attempt.log
  examples/audit-log-examples/security-command-center/scc-self-account-investigation.log
  examples/audit-log-examples/vpc-service-controls/vpc-sc-policy-violation.log
Labels: cla: yes, size/XXL

#721 QMS bug fix and document update
  tools/quota-monitoring-alerting/java/README.md
  tools/quota-monitoring-alerting/java/terraform/main.tf
Labels: cla: yes, size/M

#722 Cloud build fixed
  tools/bq-visualizer/cloudbuild.yaml
  tools/bq-visualizer/package-lock.json
  tools/bq-visualizer/package.json
Labels: cla: yes, size/XS
