Repository GoogleCloudPlatform/professional-services, pull requests merged in 2021-03, with the labels that each got.

#619 VPC Flow Logs enforcer
  README.md
  tools/vpc-flowlogs-enforcer/README.md
  tools/vpc-flowlogs-enforcer/sample_logs/asset_inventory.json
  tools/vpc-flowlogs-enforcer/sample_logs/insert_subnet_call_first.json
  tools/vpc-flowlogs-enforcer/sample_logs/insert_subnet_call_last.json
  tools/vpc-flowlogs-enforcer/terraform/cai_feeds.tf
  tools/vpc-flowlogs-enforcer/terraform/cloud_function.tf
  tools/vpc-flowlogs-enforcer/terraform/common.tf
  tools/vpc-flowlogs-enforcer/terraform/config.tf
  tools/vpc-flowlogs-enforcer/terraform/iam_cloud_function.tf
  tools/vpc-flowlogs-enforcer/terraform/log_export.tf
  tools/vpc-flowlogs-enforcer/terraform/outputs.tf
  tools/vpc-flowlogs-enforcer/terraform/projects.tf
  tools/vpc-flowlogs-enforcer/terraform/pubsub.tf
  tools/vpc-flowlogs-enforcer/terraform/service_accounts.tf
  tools/vpc-flowlogs-enforcer/terraform/templates/cloud_function/main.py
  tools/vpc-flowlogs-enforcer/terraform/templates/cloud_function/requirements.txt
  tools/vpc-flowlogs-enforcer/terraform/terraform.tfvars
  tools/vpc-flowlogs-enforcer/terraform/variables.tf
Labels: cla: yes, size/XL

#623 Update gmon to google-cloud-monitoring v2.x.x and above
  tools/gmon/gmon/cli.py
  tools/gmon/gmon/clients/monitoring.py
  tools/gmon/gmon/clients/service_monitoring.py
  tools/gmon/gmon/clients/utils.py
  tools/gmon/setup.py
  tools/gmon/tests/unit/test_cli.py
  tools/gmon/tests/unit/test_stubs.py
Labels: cla: yes, size/L

#628 Update README.md
  tools/vpc-flowlogs-enforcer/README.md
Labels: cla: yes, size/M

#627 Example - Dataflow Production Ready
  README.md
  examples/dataflow-production-ready/.gitignore
  examples/dataflow-production-ready/CONTRIBUTORS.MD
  examples/dataflow-production-ready/README.MD
  examples/dataflow-production-ready/cloudbuild_tf.yaml
  examples/dataflow-production-ready/data/integration_test_input.csv
  examples/dataflow-production-ready/java/README.md
  examples/dataflow-production-ready/python/.dockerignore
  examples/dataflow-production-ready/python/Dockerfile
  examples/dataflow-production-ready/python/README.md
  examples/dataflow-production-ready/python/cloudbuild.yaml
  examples/dataflow-production-ready/python/ml_preproc/main.py
  examples/dataflow-production-ready/python/ml_preproc/pipeline/__init__.py
  examples/dataflow-production-ready/python/ml_preproc/pipeline/beam_classes/__init__.py
  examples/dataflow-production-ready/python/ml_preproc/pipeline/beam_classes/clean_records.py
  examples/dataflow-production-ready/python/ml_preproc/pipeline/beam_classes/extract.py
  examples/dataflow-production-ready/python/ml_preproc/pipeline/beam_classes/parse_csv.py
  examples/dataflow-production-ready/python/ml_preproc/pipeline/beam_classes/preprocess.py
  examples/dataflow-production-ready/python/ml_preproc/pipeline/beam_classes/similarities.py
  examples/dataflow-production-ready/python/ml_preproc/pipeline/features/__init__.py
  examples/dataflow-production-ready/python/ml_preproc/pipeline/features/clean_input.py
  examples/dataflow-production-ready/python/ml_preproc/pipeline/model/__init__.py
  examples/dataflow-production-ready/python/ml_preproc/pipeline/model/data_classes.py
  examples/dataflow-production-ready/python/ml_preproc/pipeline/utils/__init__.py
  examples/dataflow-production-ready/python/ml_preproc/pipeline/utils/utils.py
  examples/dataflow-production-ready/python/ml_preproc/setup.py
  examples/dataflow-production-ready/python/requirements.txt
  examples/dataflow-production-ready/python/resources/abbreviations.txt
  examples/dataflow-production-ready/python/resources/training_data.csv
  examples/dataflow-production-ready/python/run_dataflow_runner.sh
  examples/dataflow-production-ready/python/run_dataflow_template.sh
  examples/dataflow-production-ready/python/run_direct_runner.sh
  examples/dataflow-production-ready/python/run_unit_tests.sh
  examples/dataflow-production-ready/python/template_spec/metadata.json
  examples/dataflow-production-ready/python/tests/__init__.py
  examples/dataflow-production-ready/python/tests/test_clean_input.py
  examples/dataflow-production-ready/python/tests/test_parse_csv.py
  examples/dataflow-production-ready/python/tests/test_transform.py
  examples/dataflow-production-ready/run_system_integration_test.sh
  examples/dataflow-production-ready/schema/ml_preproc_errors.json
  examples/dataflow-production-ready/schema/ml_preproc_results.json
  examples/dataflow-production-ready/terraform/README.MD
  examples/dataflow-production-ready/terraform/backend.tf
  examples/dataflow-production-ready/terraform/main.tf
  examples/dataflow-production-ready/terraform/modules/bigquery/main.tf
  examples/dataflow-production-ready/terraform/modules/bigquery/output.tf
  examples/dataflow-production-ready/terraform/modules/bigquery/variables.tf
  examples/dataflow-production-ready/terraform/variables.tf
Labels: cla: yes
