Repository GoogleCloudPlatform/professional-services, pull requests merged in 2021-08, with the labels that each got.

#677 Updated Ansible code for Anthos on Bare Metal installation for version 1.8.2
  tools/anthosbm-ansible-module/README.md
  tools/anthosbm-ansible-module/create_anthos_cluster.yml
  tools/anthosbm-ansible-module/reset_anthos_cluster.yml
  tools/anthosbm-ansible-module/roles/reset-cluster/tasks/main.yml
  tools/anthosbm-ansible-module/vars/anthos_vars.yml
Labels: cla: yes, size/M

#674 gcpohv - add support for static discovery in discovery API; fixes #621
  tools/gcp-org-hierarchy-viewer/gcpohv_cli.py
  tools/gcp-org-hierarchy-viewer/setup.py
Labels: cla: yes, size/S

#678 Updating examples and spelling
  README.md
  examples/bigquery-table-access-pattern-analysis/README.md
  examples/bigtable-change-key/README.md
  examples/bq_benchmarks/README.md
  examples/cloud-composer-examples/README.md
  examples/cloudml-bank-marketing/README.md
  examples/cloudml-churn-prediction/README.md
  examples/cloudml-collaborative-filtering/README.md
  examples/cloudml-energy-price-forecasting/README.md
  examples/cloudml-sklearn-pipeline/README.md
  examples/cloudml-support-routing/README.md
  examples/cloudsql-custom-metric/README.md
  examples/cost-optimization-dashboard/README.md
  examples/cryptorealtime/README.md
  examples/dataflow-data-generator/README.md
  examples/dataflow-elasticsearch-indexer/README.md
  examples/dataproc-persistent-history-server/README.md
  examples/dialogflow-entities-example/README.md
  examples/dialogflow-webhook-example/README.md
  examples/direct-upload-to-gcs/README.md
  examples/e2e-test-dataflow/Readme.md
  examples/gcf-pubsub-vm-delete-event-handler/README.md
  examples/iot-nirvana/README.md
  examples/kerberized_data_lake/README.md
  examples/kubeflow-fairing-example/README.md
  examples/python-cicd-with-cloudbuilder/README.md
  examples/tf-load-testing/README.md
  tools/agile-machine-learning-api/README.md
  tools/asset-inventory/README.md
  tools/bigquery-hive-external-table-loader/README.md
  tools/bigquery_user_info_updater_tool/README.md
  tools/bq-visualizer/README.md
  tools/cuds-prioritized-attribution/README.md
  tools/dataproc-edge-node/README.md
  tools/dns-sync/README.md
  tools/gcs-usage-recommender/README.md
  tools/gsuite-grant-analyzer/README.md
  tools/ml-dataprep/README.md
  tools/netblock-monitor/README.md
  tools/quota-monitoring-alerting/java/README.md
  tools/quota-monitoring-alerting/python/README.md
  tools/site-verification-group-sync/README.md
  tools/snowflake2bq/README.md
  tools/sts-job-manager/README.md
  tools/vm-migrator/Readme.md
  tools/vpc-flowlogs-enforcer/README.md
  tools/vpc-flowlogs-toptalkers/README.md
  tools/webhook-ingestion-pipeline/README.md
Labels: cla: yes, size/L

#679 refactor: better README in bigquery table access pattern analysis
  examples/bigquery-table-access-pattern-analysis/README.md
  examples/bigquery-table-access-pattern-analysis/assets/pipeline-information-example.png
  examples/bigquery-table-access-pattern-analysis/pipeline.ipynb
  examples/bigquery-table-access-pattern-analysis/requirements.txt
  examples/bigquery-table-access-pattern-analysis/var.env
Labels: cla: yes, size/L

#673 Google Cloud Support Slackbot
  README.md
  tools/google-cloud-support-slackbot/.env
  tools/google-cloud-support-slackbot/README.md
  tools/google-cloud-support-slackbot/archive/README.md
  tools/google-cloud-support-slackbot/default
  tools/google-cloud-support-slackbot/google_cloud_support_slackbot.py
  tools/google-cloud-support-slackbot/google_cloud_support_slackbot_icon.svg
  tools/google-cloud-support-slackbot/google_cloud_support_slackbot_icon_big.png
  tools/google-cloud-support-slackbot/google_cloud_support_slackbot_icon_small.png
  tools/google-cloud-support-slackbot/requirements.txt
Labels: cla: yes, size/XXL

#626 API Keys Rotation Checker Tool
  README.md
  tools/api-key-rotation/.gitignore
  tools/api-key-rotation/Makefile
  tools/api-key-rotation/README.md
  tools/api-key-rotation/api_key_rotation_checker/__init__.py
  tools/api-key-rotation/api_key_rotation_checker/main.py
  tools/api-key-rotation/api_key_rotation_checker/test.py
  tools/api-key-rotation/requirements-dev.txt
  tools/api-key-rotation/requirements.txt
  tools/api-key-rotation/tests/__init__.py
  tools/api-key-rotation/tests/test_compare_dates.py
  tools/api-key-rotation/tests/test_time_convert.py
Labels: cla: yes, size/XL

#680 api_check bug fix
  tools/api-key-rotation/api_key_rotation_checker/main.py
Labels: cla: yes, size/XS

#683 Adding google-cloud-support-slackbot to the exclusion list
  helpers/exclusion_list.txt
Labels: cla: yes, size/XS

#681 New add_load_date_suffix import option.
  tools/asset-inventory/asset_inventory/import_pipeline.py
  tools/asset-inventory/asset_inventory/import_pipeline_metadata
  tools/asset-inventory/asset_inventory/pipeline_runner.py
  tools/asset-inventory/gae/config.yaml
  tools/asset-inventory/gae/main.py
Labels: cla: yes, size/M

#682 Pubsub2Inbox: Cloud Identity Groups processor and Pub/Sub output
  tools/pubsub2inbox/README.md
  tools/pubsub2inbox/examples/groups-example-2.yaml
  tools/pubsub2inbox/examples/groups-example.yaml
  tools/pubsub2inbox/filters/__init__.py
  tools/pubsub2inbox/filters/strings.py
  tools/pubsub2inbox/main.py
  tools/pubsub2inbox/output/pubsub.py
  tools/pubsub2inbox/processors/base.py
  tools/pubsub2inbox/processors/groups.py
  tools/pubsub2inbox/requirements.txt
  tools/pubsub2inbox/test/fixtures/groups.json
  tools/pubsub2inbox/test/fixtures/pubsub.json
Labels: cla: yes, size/L

#685 Cleaning up linter errors from the Google Cloud Support Slackbot tool
  tools/google-cloud-support-slackbot/google_cloud_support_slackbot.py
Labels: cla: yes, size/XS

#686 remove cloud support slackbot tool from exclusion list
  helpers/exclusion_list.txt
  tools/google-cloud-support-slackbot/google_cloud_support_slackbot.py
Labels: cla: yes, size/L

#688 QMS: Update README, deployment guide etc for python version
  tools/quota-monitoring-alerting/python/README.md
  tools/quota-monitoring-alerting/python/docs/add_to_report.png
  tools/quota-monitoring-alerting/python/docs/bigquery_connector.png
  tools/quota-monitoring-alerting/python/docs/connectors.png
  tools/quota-monitoring-alerting/python/docs/copy_report.png
  tools/quota-monitoring-alerting/python/docs/copy_report_end_state.png
  tools/quota-monitoring-alerting/python/docs/dashboard_setup.README.md
  tools/quota-monitoring-alerting/python/docs/make_a_copy.png
  tools/quota-monitoring-alerting/python/docs/manual_deploy.README.md
  tools/quota-monitoring-alerting/python/docs/release_notes.README.md
  tools/quota-monitoring-alerting/python/docs/terraform_deploy.README.md
  tools/quota-monitoring-alerting/python/docs/testing_guide.README.md
Labels: cla: yes, size/L

#687 Bring example to Beam 2.31
  examples/bigtable-change-key/.gitignore
  examples/bigtable-change-key/pom.xml
  examples/bigtable-change-key/src/test/java/com/google/cloud/pso/dofns/UpdateKeyTest.java
Labels: cla: yes, size/M

#689 Remove f string for strings with no params
  tools/google-cloud-support-slackbot/google_cloud_support_slackbot.py
Labels: cla: yes, size/XS
