Repository GoogleCloudPlatform/professional-services, pull requests merged in 2022-10, with the labels that each got.

#860 fix(sts-job-manager): Logging Configuration
  tools/sts-job-manager/lib/table_util.py
  tools/sts-job-manager/pause_all_jobs.py
  tools/sts-job-manager/prepare_tables.py
  tools/sts-job-manager/remove_successful_one_time_jobs.py
  tools/sts-job-manager/sts_job_manager.py
Labels: size/M

#895 adding zetasql-helper code
  tools/zetasql-helper/.gitignore
  tools/zetasql-helper/README.md
  tools/zetasql-helper/pom.xml
  tools/zetasql-helper/src/main/java/com/google/zetasql/ZetaSQLStrings.java
  tools/zetasql-helper/src/main/java/com/pso/bigquery/optimization/BuildCatalogBasedOnQueryAndAnalyzeJoins.java
  tools/zetasql-helper/src/main/java/com/pso/bigquery/optimization/BuildCatalogForProjectAndAnalyzeJoins.java
  tools/zetasql-helper/src/main/java/com/pso/bigquery/optimization/analysis/QueryAnalysisResult.java
  tools/zetasql-helper/src/main/java/com/pso/bigquery/optimization/analysis/QueryAnalyzer.java
  tools/zetasql-helper/src/main/java/com/pso/bigquery/optimization/analysis/visitors/BaseAnalyzerVisitor.java
  tools/zetasql-helper/src/main/java/com/pso/bigquery/optimization/analysis/visitors/CreateJsonQueryStructureVisitor.java
  tools/zetasql-helper/src/main/java/com/pso/bigquery/optimization/analysis/visitors/ExtractScansVisitor.java
  tools/zetasql-helper/src/main/java/com/pso/bigquery/optimization/catalog/BigQuerySchemaConverter.java
  tools/zetasql-helper/src/main/java/com/pso/bigquery/optimization/catalog/BigQueryTableParser.java
  tools/zetasql-helper/src/main/java/com/pso/bigquery/optimization/catalog/BigQueryTableService.java
  tools/zetasql-helper/src/main/java/com/pso/bigquery/optimization/catalog/CatalogUtils.java
  tools/zetasql-helper/src/main/java/com/pso/bigquery/optimization/exceptions/CatalogDuplicateDatasetNameException.java
  tools/zetasql-helper/src/main/java/com/pso/bigquery/optimization/exceptions/InvalidTableReference.java
  tools/zetasql-helper/src/main/java/com/pso/bigquery/optimization/exceptions/QueryPatternAnalyzerException.java
  tools/zetasql-helper/src/main/java/com/pso/bigquery/optimization/exceptions/TableNotFound.java
Labels: size/XXL

#901 Mainframe Connector: user-specified charset
  tools/bigquery-zos-mainframe-connector/gszutil/build.sbt
  tools/bigquery-zos-mainframe-connector/gszutil/src/main/scala/com/google/cloud/bqsh/ExportConfig.scala
  tools/bigquery-zos-mainframe-connector/gszutil/src/main/scala/com/google/cloud/bqsh/ExportOptionParser.scala
  tools/bigquery-zos-mainframe-connector/gszutil/src/main/scala/com/google/cloud/bqsh/GsUtilConfig.scala
  tools/bigquery-zos-mainframe-connector/gszutil/src/main/scala/com/google/cloud/bqsh/GsUtilOptionParser.scala
  tools/bigquery-zos-mainframe-connector/gszutil/src/main/scala/com/google/cloud/bqsh/GsZUtilConfig.scala
  tools/bigquery-zos-mainframe-connector/gszutil/src/main/scala/com/google/cloud/bqsh/GsZUtilOptionParser.scala
  tools/bigquery-zos-mainframe-connector/gszutil/src/main/scala/com/google/cloud/bqsh/cmd/Cp.scala
  tools/bigquery-zos-mainframe-connector/gszutil/src/main/scala/com/google/cloud/bqsh/cmd/Export.scala
  tools/bigquery-zos-mainframe-connector/gszutil/src/main/scala/com/google/cloud/bqsh/cmd/GsZUtil.scala
  tools/bigquery-zos-mainframe-connector/gszutil/src/main/scala/com/google/cloud/imf/gzos/CharsetTranscoder.scala
  tools/bigquery-zos-mainframe-connector/gszutil/src/main/scala/com/google/cloud/imf/gzos/Ebcdic.scala
  tools/bigquery-zos-mainframe-connector/gszutil/src/main/scala/com/google/cloud/imf/gzos/IBM.scala
  tools/bigquery-zos-mainframe-connector/gszutil/src/main/scala/com/google/cloud/imf/gzos/Linux.scala
  tools/bigquery-zos-mainframe-connector/gszutil/src/main/scala/com/google/cloud/imf/gzos/MVS.scala
Labels: size/M

#894 Update requirements.txt
  tools/gcs-bucket-mover/requirements.txt
Labels: size/L

#897 Add example of cloudbuild with docker-compose running tcp proxy in th…
  README.md
  examples/cloudbuild-with-tcp-proxy/.env
  examples/cloudbuild-with-tcp-proxy/Dockerfile
  examples/cloudbuild-with-tcp-proxy/README.md
  examples/cloudbuild-with-tcp-proxy/cloudbuild.yaml
  examples/cloudbuild-with-tcp-proxy/docker-compose-cloudbuild.yaml
  examples/cloudbuild-with-tcp-proxy/docker-compose-local.yaml
  examples/cloudbuild-with-tcp-proxy/gssh_proxy.sh
Labels: size/XL

#906 Update Dataflow Custom Template Example with Go
  examples/dataflow-custom-templates/README.md
  examples/dataflow-custom-templates/go/Dockerfile
  examples/dataflow-custom-templates/go/README.md
  examples/dataflow-custom-templates/go/cmd/wordcount.go
  examples/dataflow-custom-templates/go/go.mod
  examples/dataflow-custom-templates/go/go.sum
  examples/dataflow-custom-templates/go/internal/wordcount/display.go
  examples/dataflow-custom-templates/go/internal/wordcount/filters.go
  examples/dataflow-custom-templates/go/internal/wordcount/strings.go
  examples/dataflow-custom-templates/go/testdata/catsum.txt
  examples/dataflow-custom-templates/infrastructure/04.template/build.tf
  examples/dataflow-custom-templates/infrastructure/04.template/variables.tf
Labels: size/L

#880 pubsub2inbox: version 1.3.0
  tools/pubsub2inbox/Dockerfile
  tools/pubsub2inbox/PROCESSORS.md
  tools/pubsub2inbox/README.md
  tools/pubsub2inbox/examples/scc-cloud-ids.yaml
  tools/pubsub2inbox/filters/__init__.py
  tools/pubsub2inbox/filters/gcp.py
  tools/pubsub2inbox/helpers/base.py
  tools/pubsub2inbox/main.py
  tools/pubsub2inbox/main.tf
  tools/pubsub2inbox/output/scc.py
  tools/pubsub2inbox/requirements.txt
  tools/pubsub2inbox/test/fixtures/cloud-ids.json
  tools/pubsub2inbox/variables.tf
Labels: size/XL

#843 Fix project directory
  examples/ml-audio-content-profiling/README.md
Labels: size/XS

#915 Patch Go version in go.mod
  examples/dataflow-custom-templates/go/go.mod
Labels: size/XS

#898 Added a flowchart and some text to explain how ranges are allocated.
  tools/ipam-autopilot/README.md
  tools/ipam-autopilot/container/migrations/1632132109_populate_sample_data.up.sql
  tools/ipam-autopilot/img/flow.png
Labels: size/S

#914 add tools/dataproc-event-driven-spark-recommendations
  README.md
  tools/dataproc-event-driven-spark-recommendations/README.md
  tools/dataproc-event-driven-spark-recommendations/images/architecture.png
  tools/dataproc-event-driven-spark-recommendations/scripts/setup.sh
  tools/dataproc-event-driven-spark-recommendations/scripts/test.sh
  tools/dataproc-event-driven-spark-recommendations/src/main.py
  tools/dataproc-event-driven-spark-recommendations/src/requirements.txt
  tools/dataproc-event-driven-spark-recommendations/terraform/main.tf
  tools/dataproc-event-driven-spark-recommendations/terraform/variables.tf
Labels: size/XL

#855 Hotfix: QMS Alerting
  tools/quota-monitoring-alerting/java/terraform/main.tf
Labels: size/XS
