Repository GoogleCloudPlatform/professional-services, pull requests merged in 2022-04, with the labels that each got.

#800 grpc example that connect to redis
  README.md
  examples/grpc_redis_example/README.md
  examples/grpc_redis_example/pom.xml
  examples/grpc_redis_example/src/main/java/com/example/grpc/client/ConnectClient.java
  examples/grpc_redis_example/src/main/java/com/example/grpc/server/ConnectServer.java
  examples/grpc_redis_example/src/main/java/com/example/grpc/service/ConnectServiceImpl.java
  examples/grpc_redis_example/src/main/java/com/example/grpc/service/RedisUtil.java
  examples/grpc_redis_example/src/main/proto/connect_service.proto
Labels: size/L

#802 Bugfix/deployment error fix
  tools/quota-monitoring-alerting/java/README.md
  tools/quota-monitoring-alerting/java/img/terraform-updated.png
  tools/quota-monitoring-alerting/java/quota-scan/src/main/java/functions/ScanProject.java
  tools/quota-monitoring-alerting/java/quota-scan/src/main/java/functions/ScanProjectHelper.java
Labels: size/L

#801 Added creating private connection logic
  tools/datastream-deployment-python-automation/README.md
  tools/datastream-deployment-python-automation/create_connection_profiles_and_datastream.py
  tools/datastream-deployment-python-automation/variables.py
Labels: size/L

#797 Billboard - mandatory checks and location check
  examples/billboard/README.md
  examples/billboard/billboard-walkthrough.md
  examples/billboard/billboard.py
  tools/google-cloud-support-slackbot/list_tracked_cases.py
  tools/google-cloud-support-slackbot/list_tracked_cases_all.py
  tools/gsnapshot/obj/Debug/netcoreapp5.0/.NETCoreApp,Version=v5.0.AssemblyAttributes.cs
  tools/gsnapshot/obj/Debug/netcoreapp5.0/gsnapshot.AssemblyInfo.cs
  tools/gsnapshot/obj/Debug/netcoreapp5.0/gsnapshot.AssemblyInfoInputs.cache
  tools/gsnapshot/obj/Debug/netcoreapp5.0/gsnapshot.GeneratedMSBuildEditorConfig.editorconfig
Labels: size/L

#803 Support API Python example (supplemental to recent Google Cloud Blog Post: https://cloud.google.com/blog/topics/developers-practitioners/cloud-support-api-building-red-button-creating-critical-cases)
  examples/cloud-support/appengine_python_example/.gcloudignore
  examples/cloud-support/appengine_python_example/README.md
  examples/cloud-support/appengine_python_example/app.yaml
  examples/cloud-support/appengine_python_example/main.py
  examples/cloud-support/appengine_python_example/requirements.txt
  examples/cloud-support/appengine_python_example/templates/created_support_case.html
  examples/cloud-support/appengine_python_example/templates/index.html
  tools/gsnapshot/obj/Debug/netcoreapp5.0/gsnapshot.GeneratedMSBuildEditorConfig.editorconfig
  tools/gsnapshot/obj/Debug/netcoreapp5.0/gsnapshot.csproj.AssemblyReference.cache
Labels: size/XL

#805 Updated Monitoring source code location
  tools/quota-monitoring-alerting/java/terraform/terraform.tfvars
Labels: size/XS

#804 A SPIFFE GCP Proxy
  README.md
  tools/spiffe-gcp-proxy/README.md
  tools/spiffe-gcp-proxy/go.mod
  tools/spiffe-gcp-proxy/go.sum
  tools/spiffe-gcp-proxy/img/spiffe_gcp_proxy_overview.png
  tools/spiffe-gcp-proxy/main.go
Labels: size/L

#809 Fix for issue: 808
  tools/custom-roles-analyzer/src/main/java/com/google/cloud/pso/security/asset/AssetServiceUtil.java
Labels: size/S

#807 Change disk-type on VM instance
  README.md
  tools/gce-change-disktype/README.md
  tools/gce-change-disktype/main.py
  tools/gce-change-disktype/requirements.txt
Labels: size/L

#813 readme and walkthrough document
  examples/billboard/README.md
  examples/billboard/billboard-walkthrough.md
  examples/billboard/billboard.py
  tools/gsnapshot/obj/Debug/netcoreapp5.0/gsnapshot.GeneratedMSBuildEditorConfig.editorconfig
Labels: size/M
