Repository GoogleCloudPlatform/professional-services, pull requests merged in 2022-08, with the labels that each got.

#857 Nstrelkova feature vm migrator backup
  tools/vm-migrator/Makefile
  tools/vm-migrator/Readme.md
  tools/vm-migrator/rollback.csv
  tools/vm-migrator/src/migrator/fields.py
  tools/vm-migrator/src/migrator/instance.py
  tools/vm-migrator/src/migrator/subnet.py
  tools/vm-migrator/src/migrator/subnet_region_migrator.py
Labels: size/XL

#842 NetAPP CVS nfs terraform sample code
  README.md
  examples/tf-netapp-cvs/Enable-Network-Peering-popup.png
  examples/tf-netapp-cvs/README.md
  examples/tf-netapp-cvs/main.tf
  examples/tf-netapp-cvs/netapp.tf
  examples/tf-netapp-cvs/provider.tf
  examples/tf-netapp-cvs/terraform.tfvars
  examples/tf-netapp-cvs/variables.tf
Labels: size/L

#810 [DBT on Cloud Composer Example] Updated documentation and added Terraform example configuration
  examples/dbt-on-cloud-composer/README.md
  examples/dbt-on-cloud-composer/terraform/README.md
  examples/dbt-on-cloud-composer/terraform/main.tf
  examples/dbt-on-cloud-composer/terraform/variables.tf
  examples/dbt-on-cloud-composer/terraform/versions.tf
Labels: size/L

#851 Fixing paths in readme
  tools/bigquery-zos-mainframe-connector/README.md
Labels: size/S

#859 GCP AWS HA VPN terraform setup in tools
  README.md
  tools/gcp-aws-ha-vpn/.terraform.lock.hcl
  tools/gcp-aws-ha-vpn/README.md
  tools/gcp-aws-ha-vpn/aws_vpn.tf
  tools/gcp-aws-ha-vpn/gcp_vpn.tf
  tools/gcp-aws-ha-vpn/outputs.tf
  tools/gcp-aws-ha-vpn/provider.tf
  tools/gcp-aws-ha-vpn/terraform.tfvars
  tools/gcp-aws-ha-vpn/variables.tf
Labels: size/L

#874 Add an example for workload identity federation
  examples/workload_identity_federation/.gitlab-ci.yml
  examples/workload_identity_federation/1-create-wif/main.tf
  examples/workload_identity_federation/1-create-wif/outputs.tf
  examples/workload_identity_federation/1-create-wif/variables.tf
  examples/workload_identity_federation/1-create-wif/versions.tf
  examples/workload_identity_federation/2-use-wif/main.tf
  examples/workload_identity_federation/2-use-wif/outputs.tf
  examples/workload_identity_federation/2-use-wif/variables.tf
  examples/workload_identity_federation/2-use-wif/versions.tf
  examples/workload_identity_federation/2-use-wif/vpc.tf
  examples/workload_identity_federation/README.md
  examples/workload_identity_federation/modules/vpc/main.tf
  examples/workload_identity_federation/modules/vpc/outputs.tf
  examples/workload_identity_federation/modules/vpc/variables.tf
  examples/workload_identity_federation/modules/vpc/versions.tf
  examples/workload_identity_federation/modules/workload/main.tf
  examples/workload_identity_federation/modules/workload/outputs.tf
  examples/workload_identity_federation/modules/workload/variables.tf
  examples/workload_identity_federation/modules/workload/versions.tf
  examples/workload_identity_federation/run_wif_gcp.sh
Labels: size/XL

#867 Assume AWS ARN Role from a GCP Service Account
  tools/gcp-sa-to-assume-aws-arn-role/README.md
  tools/gcp-sa-to-assume-aws-arn-role/gcp-auth/go.mod
  tools/gcp-sa-to-assume-aws-arn-role/gcp-auth/go.sum
  tools/gcp-sa-to-assume-aws-arn-role/gcp-auth/main.go
Labels: size/L

#873 An example illustrating Dataflow Custom templates provisioned within a terraform context
  README.md
  examples/dataflow-custom-templates/.gitignore
  examples/dataflow-custom-templates/README.md
  examples/dataflow-custom-templates/cloud_shell_tutorial.md
  examples/dataflow-custom-templates/infrastructure/01.setup/README.md
  examples/dataflow-custom-templates/infrastructure/01.setup/iam.tf
  examples/dataflow-custom-templates/infrastructure/01.setup/provider.tf
  examples/dataflow-custom-templates/infrastructure/01.setup/registry.tf
  examples/dataflow-custom-templates/infrastructure/01.setup/services.tf
  examples/dataflow-custom-templates/infrastructure/01.setup/variables.tf
  examples/dataflow-custom-templates/infrastructure/02.network/README.md
  examples/dataflow-custom-templates/infrastructure/02.network/nat.tf
  examples/dataflow-custom-templates/infrastructure/02.network/network.tf
  examples/dataflow-custom-templates/infrastructure/02.network/provider.tf
  examples/dataflow-custom-templates/infrastructure/02.network/variables.tf
  examples/dataflow-custom-templates/infrastructure/03.io/README.md
  examples/dataflow-custom-templates/infrastructure/03.io/provider.tf
  examples/dataflow-custom-templates/infrastructure/03.io/storage.tf
  examples/dataflow-custom-templates/infrastructure/03.io/variables.tf
  examples/dataflow-custom-templates/infrastructure/04.template/README.md
  examples/dataflow-custom-templates/infrastructure/04.template/build.tf
  examples/dataflow-custom-templates/infrastructure/04.template/dataflow-template.json
  examples/dataflow-custom-templates/infrastructure/04.template/provider.tf
  examples/dataflow-custom-templates/infrastructure/04.template/storage.tf
  examples/dataflow-custom-templates/infrastructure/04.template/variables.tf
  examples/dataflow-custom-templates/infrastructure/README.md
  examples/dataflow-custom-templates/java/README.md
  examples/dataflow-custom-templates/java/build.gradle.kts
  examples/dataflow-custom-templates/java/gradle.properties
  examples/dataflow-custom-templates/java/gradle/wrapper/gradle-wrapper.jar
  examples/dataflow-custom-templates/java/gradle/wrapper/gradle-wrapper.properties
  examples/dataflow-custom-templates/java/gradlew
  examples/dataflow-custom-templates/java/gradlew.bat
  examples/dataflow-custom-templates/java/settings.gradle.kts
  examples/dataflow-custom-templates/java/src/main/java/com/google/example/DisplayCounts.java
  examples/dataflow-custom-templates/java/src/main/java/com/google/example/FilterNonEmpty.java
  examples/dataflow-custom-templates/java/src/main/java/com/google/example/SplitString.java
  examples/dataflow-custom-templates/java/src/main/java/com/google/example/ToLowerCase.java
  examples/dataflow-custom-templates/java/src/main/java/com/google/example/WordCount.java
  examples/dataflow-custom-templates/java/src/main/java/com/google/example/WordCountOptions.java
  examples/dataflow-custom-templates/java/src/main/resources/catsum.txt
  examples/dataflow-custom-templates/python/Dockerfile
  examples/dataflow-custom-templates/python/README.md
  examples/dataflow-custom-templates/python/gradle/wrapper/gradle-wrapper.jar
  examples/dataflow-custom-templates/python/gradle/wrapper/gradle-wrapper.properties
  examples/dataflow-custom-templates/python/main.py
  examples/dataflow-custom-templates/python/requirements.txt
  examples/dataflow-custom-templates/python/resources/catsum.txt
  examples/dataflow-custom-templates/python/setup.py
  examples/dataflow-custom-templates/python/wordcount/__init__.py
  examples/dataflow-custom-templates/python/wordcount/split_string.py
  examples/dataflow-custom-templates/python/wordcount/word_count_options.py
Labels: size/XXL

#870 uploading the ccm service kit asset
  tools/ccm-service-kit/ccm-arch-eph.png
  tools/ccm-service-kit/ccm-arch-pers.png
  tools/ccm-service-kit/ccm-image.png
  tools/ccm-service-kit/cloudbuild-create.yml
  tools/ccm-service-kit/cloudbuild-delete.yml
  tools/ccm-service-kit/composer/__init__.py
  tools/ccm-service-kit/composer/ccm-airflow-tasks.png
  tools/ccm-service-kit/composer/dags/__init__.py
  tools/ccm-service-kit/composer/dags/dag-ccm-pipeline.py
  tools/ccm-service-kit/composer/dags/dependencies/__init__.py
  tools/ccm-service-kit/composer/dags/dependencies/operators/__init__.py
  tools/ccm-service-kit/composer/dags/dependencies/operators/api_request.py
  tools/ccm-service-kit/composer/dags/dependencies/queries/__init__.py
  tools/ccm-service-kit/composer/dags/dependencies/queries/ccm_queries.py
  tools/ccm-service-kit/composer/dags/dependencies/queries/schemas.py
  tools/ccm-service-kit/composer/dags/dependencies/scripts/__init__.py
  tools/ccm-service-kit/composer/dags/dependencies/scripts/run_sts.py
  tools/ccm-service-kit/composer/dags/dependencies/scripts/variable_reader.py
  tools/ccm-service-kit/composer/dags/dependencies/variables/__init__.py
  tools/ccm-service-kit/composer/dags/dependencies/variables/variables.json
  tools/ccm-service-kit/composer/readme.md
  tools/ccm-service-kit/ddls/ccm-cloud-cost-final-ddl.sql
  tools/ccm-service-kit/ddls/ccm-cloud-cost-staging-ddl.sql
  tools/ccm-service-kit/infra-as-code/environment-deploy/.gitignore
  tools/ccm-service-kit/infra-as-code/environment-deploy/input.tfvars
  tools/ccm-service-kit/infra-as-code/environment-deploy/main.tf
  tools/ccm-service-kit/infra-as-code/environment-deploy/variables.tf
  tools/ccm-service-kit/infra-as-code/environment-setup/.gitignore
  tools/ccm-service-kit/infra-as-code/environment-setup/input.tfvars
  tools/ccm-service-kit/infra-as-code/environment-setup/main.tf
  tools/ccm-service-kit/infra-as-code/environment-setup/variables.tf
  tools/ccm-service-kit/infra-as-code/environment-setup/versions.tf
  tools/ccm-service-kit/infra-as-code/modules/ccm-base/README.md
  tools/ccm-service-kit/infra-as-code/modules/ccm-base/db.tf
  tools/ccm-service-kit/infra-as-code/modules/ccm-base/iam.tf
  tools/ccm-service-kit/infra-as-code/modules/ccm-base/main.tf
  tools/ccm-service-kit/infra-as-code/modules/ccm-base/output.tf
  tools/ccm-service-kit/infra-as-code/modules/ccm-base/pubsub.tf
  tools/ccm-service-kit/infra-as-code/modules/ccm-base/scheduler.tf
  tools/ccm-service-kit/infra-as-code/modules/ccm-base/service_account.tf
  tools/ccm-service-kit/infra-as-code/modules/ccm-base/services.tf
  tools/ccm-service-kit/infra-as-code/modules/ccm-base/storage.tf
  tools/ccm-service-kit/infra-as-code/modules/ccm-base/variables.tf
  tools/ccm-service-kit/infra-as-code/modules/ccm-composer/main.tf
  tools/ccm-service-kit/infra-as-code/modules/ccm-composer/output.tf
  tools/ccm-service-kit/infra-as-code/modules/ccm-composer/variables.tf
  tools/ccm-service-kit/infra-as-code/readme.md
  tools/ccm-service-kit/infra-as-code/storage-transfer-service/aws-to-gcp.tf
  tools/ccm-service-kit/infra-as-code/storage-transfer-service/azure-to-gcp.tf
  tools/ccm-service-kit/infra-as-code/storage-transfer-service/variables.tf
  tools/ccm-service-kit/product-mapping/product_mapping.py
  tools/ccm-service-kit/product-mapping/service_compare.csv
  tools/ccm-service-kit/readme.md
Labels: size/XXL

#879 Inherit Coder from coders.
  examples/dataflow-python-examples/batch-examples/cookbook-examples/pipelines/data_ingestion_configurable.py
Labels: size/XS
