Repository GoogleCloudPlatform/professional-services, pull requests merged in 2022-12, with the labels that each got.

#902 Mainframe Connector: bq extract
  tools/bigquery-zos-mainframe-connector/gszutil/src/main/scala/com/google/cloud/bqsh/ExtractOptionParser.scala
Labels: size/M

#945 Limit the user-settable job count max
  tools/sts-job-manager/lib/options.py
Labels: size/S

#939 Mainframe Connector: add pubsub topics publish command
  tools/bigquery-zos-mainframe-connector/gszutil/build.sbt
  tools/bigquery-zos-mainframe-connector/gszutil/src/main/scala/com/google/cloud/bqsh/Bqsh.scala
  tools/bigquery-zos-mainframe-connector/gszutil/src/main/scala/com/google/cloud/bqsh/PublishConfig.scala
  tools/bigquery-zos-mainframe-connector/gszutil/src/main/scala/com/google/cloud/bqsh/PublishOptionParser.scala
  tools/bigquery-zos-mainframe-connector/gszutil/src/main/scala/com/google/cloud/bqsh/cmd/Publish.scala
  tools/bigquery-zos-mainframe-connector/gszutil/src/main/scala/com/google/cloud/imf/gzos/Util.scala
  tools/bigquery-zos-mainframe-connector/mainframe-util/build.sbt
  tools/bigquery-zos-mainframe-connector/mainframe-util/src/main/scala/com/google/cloud/imf/util/Services.scala
Labels: size/L

#940 Mainframe Connector: add dataflow flex-template run
  tools/bigquery-zos-mainframe-connector/gszutil/build.sbt
  tools/bigquery-zos-mainframe-connector/gszutil/src/main/scala/com/google/cloud/bqsh/Bqsh.scala
  tools/bigquery-zos-mainframe-connector/gszutil/src/main/scala/com/google/cloud/bqsh/DataflowFlexTemplateRunConfig.scala
  tools/bigquery-zos-mainframe-connector/gszutil/src/main/scala/com/google/cloud/bqsh/DataflowFlexTemplateRunOptionParser.scala
  tools/bigquery-zos-mainframe-connector/gszutil/src/main/scala/com/google/cloud/bqsh/cmd/DataflowFlexTemplateRun.scala
  tools/bigquery-zos-mainframe-connector/gszutil/src/main/scala/com/google/cloud/bqsh/cmd/Publish.scala
  tools/bigquery-zos-mainframe-connector/mainframe-util/build.sbt
  tools/bigquery-zos-mainframe-connector/mainframe-util/src/main/scala/com/google/cloud/imf/util/Services.scala
Labels: size/L

#946 Oracle DDL Migration Utility
  examples/bigquery-oracle-ddl-migration-utility/BQ_Table_Creator/BQ Table Creator.md
  examples/bigquery-oracle-ddl-migration-utility/BQ_Table_Creator/bq_table_creator.py
  examples/bigquery-oracle-ddl-migration-utility/DDL_Archiver/Archive DDL.md
  examples/bigquery-oracle-ddl-migration-utility/DDL_Archiver/archive_ddl.py
  examples/bigquery-oracle-ddl-migration-utility/DDL_Converter/Oracle BQ Converter.md
  examples/bigquery-oracle-ddl-migration-utility/DDL_Converter/oracle_bq_converter.py
  examples/bigquery-oracle-ddl-migration-utility/DDL_Extractor/Oracle DDL Extraction.md
  examples/bigquery-oracle-ddl-migration-utility/README.md
  examples/bigquery-oracle-ddl-migration-utility/config/metadata_columns.json
  examples/bigquery-oracle-ddl-migration-utility/config/object_name_mapping.json
  examples/bigquery-oracle-ddl-migration-utility/config/oracle_ddl_extraction.py
  examples/bigquery-oracle-ddl-migration-utility/config/orcl-ddl-extraction-config.json
  examples/bigquery-oracle-ddl-migration-utility/requirements.txt
Labels: size/XXL

#950 DDL Oracle to BigQuery Migration Utility
  README.md
  examples/bigquery-oracle-ddl-migration-utility/DDL_Extractor/oracle_ddl_extraction.py
  examples/bigquery-oracle-ddl-migration-utility/README.md
  examples/bigquery-oracle-ddl-migration-utility/config/metadata_columns.json
  examples/bigquery-oracle-ddl-migration-utility/config/object_name_mapping.json
  examples/bigquery-oracle-ddl-migration-utility/config/orcl-ddl-extraction-config.json
Labels: size/M

#949 Mainframe Connector: update dependency versions
  tools/bigquery-zos-mainframe-connector/gszutil/build.sbt
  tools/bigquery-zos-mainframe-connector/gszutil/src/main/scala/com/google/cloud/bqsh/ExtractOptionParser.scala
  tools/bigquery-zos-mainframe-connector/gszutil/src/main/scala/com/google/cloud/bqsh/cmd/DataflowFlexTemplateRun.scala
  tools/bigquery-zos-mainframe-connector/gszutil/src/main/scala/com/google/cloud/bqsh/cmd/Publish.scala
  tools/bigquery-zos-mainframe-connector/gszutil/src/main/scala/com/google/cloud/bqsh/cmd/Scp.scala
  tools/bigquery-zos-mainframe-connector/gszutil/src/main/scala/com/google/cloud/imf/gzos/Util.scala
  tools/bigquery-zos-mainframe-connector/mainframe-util/build.sbt
  tools/bigquery-zos-mainframe-connector/mainframe-util/src/main/scala/com/google/api/gax/grpc/ChannelUtil.scala
  tools/bigquery-zos-mainframe-connector/mainframe-util/src/main/scala/com/google/cloud/imf/util/BigQueryWithRetries.scala
  tools/bigquery-zos-mainframe-connector/mainframe-util/src/main/scala/com/google/cloud/imf/util/Services.scala
  tools/bigquery-zos-mainframe-connector/mainframe-util/src/main/scala/com/google/cloud/imf/util/StorageWithRetries.scala
Labels: size/M
