Repository GoogleCloudPlatform/professional-services, pull requests merged in 2022-03, with the labels that each got.

#781 Improved exception handling, documentation and logging
  tools/custom-roles-analyzer/README.md
  tools/custom-roles-analyzer/src/main/java/com/google/cloud/pso/security/CustomRoleAnalyzer.java
  tools/custom-roles-analyzer/src/main/java/com/google/cloud/pso/security/constants/GenericConstants.java
  tools/custom-roles-analyzer/src/main/java/com/google/cloud/pso/security/util/CustomRoleAnalyzerHelper.java
  tools/custom-roles-analyzer/src/main/java/com/google/cloud/pso/security/util/CustomRoleAnalyzerResult.java
Labels: size/L

#783 fix(sts-job-manager): Fix accessing `objectConditions`
  tools/sts-job-manager/sts_job_manager.py
Labels: size/XS

#782 Added Cloud Support API Sample Code
  README.md
  examples/cloud-support/cloud-client/README.md
  examples/cloud-support/cloud-client/data/case.json
  examples/cloud-support/cloud-client/data/updateCase.json
  examples/cloud-support/cloud-client/pom.xml
  examples/cloud-support/cloud-client/src/main/java/com/example/gcpsupport/CreateCase.java
  examples/cloud-support/cloud-client/src/main/java/com/example/gcpsupport/GetCase.java
  examples/cloud-support/cloud-client/src/main/java/com/example/gcpsupport/ListCases.java
  examples/cloud-support/cloud-client/src/main/java/com/example/gcpsupport/Starter.java
  examples/cloud-support/cloud-client/src/main/java/com/example/gcpsupport/UpdateCase.java
  examples/cloud-support/cloud-client/src/test/java/com/example/gcpsupport/CreateCaseTest.java
  examples/cloud-support/cloud-client/src/test/java/com/example/gcpsupport/GetCaseTest.java
  examples/cloud-support/cloud-client/src/test/java/com/example/gcpsupport/ListCasesTest.java
  examples/cloud-support/cloud-client/src/test/java/com/example/gcpsupport/StarterTest.java
  examples/cloud-support/cloud-client/src/test/java/com/example/gcpsupport/UpdateCaseTest.java
Labels: size/XXL

#784 Role bindings analysis feature
  tools/custom-roles-analyzer/README.md
  tools/custom-roles-analyzer/analyze.sh
  tools/custom-roles-analyzer/pom.xml
  tools/custom-roles-analyzer/src/main/java/com/google/cloud/pso/security/CustomRoleAnalyzer.java
  tools/custom-roles-analyzer/src/main/java/com/google/cloud/pso/security/asset/AssetServiceUtil.java
  tools/custom-roles-analyzer/src/main/java/com/google/cloud/pso/security/constants/GenericConstants.java
Labels: size/L

#785 Adding missing documentation for new feature
  tools/custom-roles-analyzer/README.md
  tools/custom-roles-analyzer/src/main/java/com/google/cloud/pso/security/constants/GenericConstants.java
Labels: size/M

#788 fix(sts-job-manager): Support Fast Operations and Ignore Deleted Jobs
  tools/sts-job-manager/README.md
  tools/sts-job-manager/sts_job_manager.py
Labels: size/M

#786 Merge Tools QMS python new changes into Main
  tools/quota-monitoring-alerting/python/.gcloudignore
  tools/quota-monitoring-alerting/python/README.md
  tools/quota-monitoring-alerting/python/cloudbuild.yaml
  tools/quota-monitoring-alerting/python/terraform/common/main.tf
Labels: size/L

#791 Add Dialogflow CX Private webhook example
  README.md
  examples/dialogflowcx-private-webhook-example/.gitignore
  examples/dialogflowcx-private-webhook-example/Dockerfile
  examples/dialogflowcx-private-webhook-example/README.md
  examples/dialogflowcx-private-webhook-example/certificates/certificates.toml
  examples/dialogflowcx-private-webhook-example/docker-compose.yaml
  examples/dialogflowcx-private-webhook-example/modules/request.py
  examples/dialogflowcx-private-webhook-example/modules/response.py
  examples/dialogflowcx-private-webhook-example/requirements.txt
  examples/dialogflowcx-private-webhook-example/webhook.py
  examples/dialogflowcx-private-webhook-example/webhook_test.py
Labels: size/XL

#789 Deployment automation for Cloud Datastream
  README.md
  tools/datastream-deployment-python-automation/README.md
  tools/datastream-deployment-python-automation/create_connection_profiles_and_datastream.py
  tools/datastream-deployment-python-automation/requirements.txt
  tools/datastream-deployment-python-automation/variables.py
Labels: size/L

#794 Added Instance Mapper tool
  README.md
  tools/instance_mapper/README.md
  tools/instance_mapper/cmd/instance_mapper/gpu-mapping.yaml
  tools/instance_mapper/cmd/instance_mapper/main.go
  tools/instance_mapper/cmd/instance_mapper/sql-mapping.yaml
  tools/instance_mapper/go.mod
  tools/instance_mapper/go.sum
  tools/instance_mapper/instance_mapper.go
  tools/instance_mapper/matcherlib.go
Labels: size/XXL

#795 Add EXPOSE 8081 to dockerfile
  examples/dialogflowcx-private-webhook-example/Dockerfile
Labels: size/XS

#799 Minor fixes in DFDL Bigtable PubSub Example
  examples/dfdl-bigtable-pubsub-example/README.md
  examples/dfdl-bigtable-pubsub-example/pom.xml
  examples/dfdl-bigtable-pubsub-example/src/main/java/com/example/dfdl/DfdlDef.java
Labels: size/S

#798 grpc spanner example
  README.md
  examples/grpc_spanner_example/README.md
  examples/grpc_spanner_example/pom.xml
  examples/grpc_spanner_example/src/main/java/com/example/grpc/client/ConnectClient.java
  examples/grpc_spanner_example/src/main/java/com/example/grpc/server/ConnectServer.java
  examples/grpc_spanner_example/src/main/java/com/example/grpc/service/ConnectServiceImpl.java
  examples/grpc_spanner_example/src/main/java/com/example/grpc/service/SpannerUtil.java
  examples/grpc_spanner_example/src/main/proto/connect_service.proto
Labels: size/L
