Repository GoogleCloudPlatform/professional-services, pull requests merged in 2022-06, with the labels that each got.

#839 Bug fixes for the vm-migrator and troubleshooting info for vpc-flowlogs-toptalkers
  tools/vm-migrator/src/migrator/instance.py
  tools/vm-migrator/src/migrator/subnet.py
  tools/vm-migrator/src/migrator/subnet_region_migrator.py
  tools/vpc-flowlogs-toptalkers/README.md
  tools/vpc-flowlogs-toptalkers/routines.tf
  tools/vpc-flowlogs-toptalkers/vpc_flows_schema.json
Labels: size/XL

#834 automation for cloud function workflow
  tools/cloud-function-automation/README.md
  tools/cloud-function-automation/cloud_function_automation.py
  tools/cloud-function-automation/img.png
  tools/cloud-function-automation/requirements.txt
  tools/cloud-function-automation/variables.py
Labels: size/L

#840 Pubsub2Inbox: add Twilio SMS
  tools/pubsub2inbox/README.md
  tools/pubsub2inbox/examples/twilio-example.yaml
  tools/pubsub2inbox/output/twilio.py
  tools/pubsub2inbox/requirements.txt
  tools/pubsub2inbox/test/fixtures/twilio.json
Labels: size/L

#841 Disclaimer for java version and copyright updates
  tools/quota-monitoring-alerting/README.md
  tools/quota-monitoring-alerting/java/quota-notification/src/main/java/functions/SendNotification.java
  tools/quota-monitoring-alerting/java/quota-notification/src/main/java/functions/eventpojos/PubSubMessage.java
  tools/quota-monitoring-alerting/java/quota-notification/src/test/java/functions/SendNotificationTest.java
  tools/quota-monitoring-alerting/java/quota-scan/pom.xml
  tools/quota-monitoring-alerting/java/quota-scan/src/main/java/functions/ListProjects.java
  tools/quota-monitoring-alerting/java/quota-scan/src/main/java/functions/ScanProjectQuotas.java
  tools/quota-monitoring-alerting/java/quota-scan/src/main/java/functions/ScanProjectQuotasHelper.java
  tools/quota-monitoring-alerting/java/quota-scan/src/main/java/functions/eventpojos/GCPProject.java
  tools/quota-monitoring-alerting/java/quota-scan/src/main/java/functions/eventpojos/GCPResourceClient.java
  tools/quota-monitoring-alerting/java/quota-scan/src/main/java/functions/eventpojos/ProjectQuota.java
  tools/quota-monitoring-alerting/java/quota-scan/src/main/java/functions/eventpojos/PubSubMessage.java
  tools/quota-monitoring-alerting/java/quota-scan/src/main/java/functions/eventpojos/TimeSeriesQuery.java
  tools/quota-monitoring-alerting/java/terraform/example.tfvars
  tools/quota-monitoring-alerting/java/terraform/main.tf
  tools/quota-monitoring-alerting/java/terraform/terraform.tfvars
  tools/quota-monitoring-alerting/java/terraform/variables.tf
Labels: size/M

#844 pubsub2inbox: fix typo in SCC output
  tools/pubsub2inbox/examples/scc-finding-config.yaml
Labels: size/XS

#845 BigQuery Tink Toolkit
  README.md
  tools/bigquery-tink-toolkit/README.md
  tools/bigquery-tink-toolkit/crypto_util.py
  tools/bigquery-tink-toolkit/spark_aead_example.py
  tools/bigquery-tink-toolkit/tink_key_gen_and_upload.py
Labels: size/XL

#849 Updated to current debian base image
  tools/ipam-autopilot/Dockerfile
Labels: size/XS
