Repository GoogleCloudPlatform/professional-services, pull requests merged in 2022-01, with the labels that each got.

#743 OpenAPI to Cloud Armor
  README.md
  tools/openapi-to-cloud-armor/README.md
  tools/openapi-to-cloud-armor/go.mod
  tools/openapi-to-cloud-armor/go.sum
  tools/openapi-to-cloud-armor/main.go
  tools/openapi-to-cloud-armor/main_test.go
Labels: size/XL

#745 Selective deployment code for multi-folder repo code changes
  examples/cloudbuild-selective-deployment/README.md
  examples/cloudbuild-selective-deployment/build-files/delta-changes.sh
  examples/cloudbuild-selective-deployment/build-files/tf-wrapper.sh
  examples/cloudbuild-selective-deployment/cloudbuild.yaml
  examples/cloudbuild-selective-deployment/modules/vm/main.tf
  examples/cloudbuild-selective-deployment/modules/vm/outputs.tf
  examples/cloudbuild-selective-deployment/modules/vm/variables.tf
  examples/cloudbuild-selective-deployment/user-resources/business-unit1/dev-env/main.tf
  examples/cloudbuild-selective-deployment/user-resources/business-unit1/dev-env/outputs.tf
  examples/cloudbuild-selective-deployment/user-resources/business-unit1/dev-env/terraform.tfvars
  examples/cloudbuild-selective-deployment/user-resources/business-unit1/dev-env/variables.tf
  examples/cloudbuild-selective-deployment/user-resources/business-unit1/env-test/main.tf
  examples/cloudbuild-selective-deployment/user-resources/business-unit1/env-test/outputs.tf
  examples/cloudbuild-selective-deployment/user-resources/business-unit1/env-test/terraform.tfvars
  examples/cloudbuild-selective-deployment/user-resources/business-unit1/env-test/variables.tf
  examples/cloudbuild-selective-deployment/user-resources/business-unit1/prod-env/main.tf
  examples/cloudbuild-selective-deployment/user-resources/business-unit1/prod-env/outputs.tf
  examples/cloudbuild-selective-deployment/user-resources/business-unit1/prod-env/terraform.tfvars
  examples/cloudbuild-selective-deployment/user-resources/business-unit1/prod-env/variables.tf
  examples/cloudbuild-selective-deployment/user-resources/business-unit1/qa-env/main.tf
  examples/cloudbuild-selective-deployment/user-resources/business-unit1/qa-env/outputs.tf
  examples/cloudbuild-selective-deployment/user-resources/business-unit1/qa-env/terraform.tfvars
  examples/cloudbuild-selective-deployment/user-resources/business-unit1/qa-env/variables.tf
  examples/cloudbuild-selective-deployment/user-resources/business-unit2/dev-env/main.tf
  examples/cloudbuild-selective-deployment/user-resources/business-unit2/dev-env/outputs.tf
  examples/cloudbuild-selective-deployment/user-resources/business-unit2/dev-env/terraform.tfvars
  examples/cloudbuild-selective-deployment/user-resources/business-unit2/dev-env/variables.tf
  examples/cloudbuild-selective-deployment/user-resources/business-unit2/env-test/main.tf
  examples/cloudbuild-selective-deployment/user-resources/business-unit2/env-test/outputs.tf
  examples/cloudbuild-selective-deployment/user-resources/business-unit2/env-test/terraform.tfvars
  examples/cloudbuild-selective-deployment/user-resources/business-unit2/env-test/variables.tf
  examples/cloudbuild-selective-deployment/user-resources/business-unit2/prod-env/main.tf
  examples/cloudbuild-selective-deployment/user-resources/business-unit2/prod-env/outputs.tf
  examples/cloudbuild-selective-deployment/user-resources/business-unit2/prod-env/terraform.tfvars
  examples/cloudbuild-selective-deployment/user-resources/business-unit2/prod-env/variables.tf
  examples/cloudbuild-selective-deployment/user-resources/business-unit2/qa-env/main.tf
  examples/cloudbuild-selective-deployment/user-resources/business-unit2/qa-env/outputs.tf
  examples/cloudbuild-selective-deployment/user-resources/business-unit2/qa-env/terraform.tfvars
  examples/cloudbuild-selective-deployment/user-resources/business-unit2/qa-env/variables.tf
Labels: size/XXL

#746 Added top 10 usage consumption table
  tools/quota-monitoring-alerting/java/README.md
  tools/quota-monitoring-alerting/java/img/bigquery-orderby-consumption.png
  tools/quota-monitoring-alerting/java/img/datastudio_schedule_email.png
  tools/quota-monitoring-alerting/java/img/ds-copy-report-fixed-new-data-source.png
  tools/quota-monitoring-alerting/java/img/ds-dropdown-copy.png
  tools/quota-monitoring-alerting/java/img/ds-edit-mode-updated.png
  tools/quota-monitoring-alerting/java/img/ds-region-middle.png
  tools/quota-monitoring-alerting/java/img/ds-schedule-email-button.png
  tools/quota-monitoring-alerting/java/img/ds-switch-to-view-mode.png
  tools/quota-monitoring-alerting/java/img/ds-updated-quotas-dashboard.png
  tools/quota-monitoring-alerting/java/img/ds_copy.png
  tools/quota-monitoring-alerting/java/img/ds_copy_report.png
  tools/quota-monitoring-alerting/java/img/ds_edit_data_source_big_query.png
  tools/quota-monitoring-alerting/java/img/ds_region_datasource_config.png
  tools/quota-monitoring-alerting/java/img/ds_switch_view_mode.png
  tools/quota-monitoring-alerting/java/img/ds_template.png
  tools/quota-monitoring-alerting/java/img/ds_template_copy.png
  tools/quota-monitoring-alerting/java/img/edit_terraform_variables.png
  tools/quota-monitoring-alerting/java/img/terraform-updated.png
  tools/quota-monitoring-alerting/java/quota-scan/src/main/java/functions/ScanProjectQuotas.java
  tools/quota-monitoring-alerting/java/quota-scan/src/main/java/functions/ScanProjectQuotasHelper.java
  tools/quota-monitoring-alerting/java/terraform/terraform.tfvars
Labels: size/M

#749 Only refresh the yum index.
  tools/hive-bigquery/prerequisites/prerequisites.sh
Labels: size/XS

#753 Update BigQuery code to only return latest row
  tools/quota-monitoring-alerting/java/README.md
  tools/quota-monitoring-alerting/java/img/updated-bq-only-latest-row.png
Labels: size/M

#751 Service Account Provider - Workload Identity Federation workaround for Gitlab CI
  README.md
  tools/service-account-provider/.gitattributes
  tools/service-account-provider/Dockerfile
  tools/service-account-provider/README.md
  tools/service-account-provider/example_gitlab_pipeline/.gitlab-ci.yml
  tools/service-account-provider/example_gitlab_pipeline/main.tf
  tools/service-account-provider/example_gitlab_pipeline/provider.tf
  tools/service-account-provider/example_gitlab_pipeline/terraform-apply.sh
  tools/service-account-provider/example_gitlab_pipeline/terraform-init.sh
  tools/service-account-provider/example_gitlab_pipeline/terraform-plan.sh
  tools/service-account-provider/example_gitlab_pipeline/terraform-validate.sh
  tools/service-account-provider/go.mod
  tools/service-account-provider/go.sum
  tools/service-account-provider/infrastructure/config.yaml
  tools/service-account-provider/infrastructure/main.tf
  tools/service-account-provider/infrastructure/provider.tf
  tools/service-account-provider/infrastructure/variables.tf
  tools/service-account-provider/main.go
  tools/service-account-provider/main_test.go
  tools/service-account-provider/sapro.png
  tools/service-account-provider/test_config/config.yaml
Labels: size/XL
