Repository GoogleCloudPlatform/professional-services, pull requests merged in 2022-02, with the labels that each got.

#752 Added the possibility to provide an identity token via Environment Va…
  tools/ipam-autopilot/README.md
  tools/ipam-autopilot/container/main.go
  tools/ipam-autopilot/infrastructure/main.tf
  tools/ipam-autopilot/infrastructure/variables.tf
  tools/ipam-autopilot/provider/ipam/resources/resource_ip_range.go
Labels: size/S

#754 Added Cloud Run Lambda compatibility utility
  tools/lambda-compat/README.md
  tools/lambda-compat/cmd/lambda-build/main.go
  tools/lambda-compat/cmd/lambda-build/templates/common.tpl
  tools/lambda-compat/cmd/lambda-build/templates/dotnetcore.tpl
  tools/lambda-compat/cmd/lambda-build/templates/go.tpl
  tools/lambda-compat/cmd/lambda-build/templates/java.tpl
  tools/lambda-compat/cmd/lambda-build/templates/nodejs.tpl
  tools/lambda-compat/cmd/lambda-build/templates/python.tpl
  tools/lambda-compat/cmd/lambda-build/templates/ruby.tpl
  tools/lambda-compat/cmd/lambda-build/templates/terraform_main.tf.tpl
  tools/lambda-compat/cmd/lambda-build/templates/terraform_outputs.tf.tpl
  tools/lambda-compat/cmd/lambda-build/templates/terraform_variables.tf.tpl
  tools/lambda-compat/cmd/lambda-build/templates/terraform_versions.tf.tpl
  tools/lambda-compat/cmd/lambda-compat/main.go
  tools/lambda-compat/go.mod
  tools/lambda-compat/go.sum
  tools/lambda-compat/main.go
Labels: size/XXL

#755 Add gsnapshot utility
  tools/gsnapshot/.gitlab-ci.yml
  tools/gsnapshot/AutoCompletionHandler.cs
  tools/gsnapshot/Disks.cs
  tools/gsnapshot/Instances.cs
  tools/gsnapshot/Makefile
  tools/gsnapshot/Menu.cs
  tools/gsnapshot/Operations.cs
  tools/gsnapshot/Options.cs
  tools/gsnapshot/Program.cs
  tools/gsnapshot/README.md
  tools/gsnapshot/Resources.cs
  tools/gsnapshot/Runner.cs
  tools/gsnapshot/Snapshots.cs
  tools/gsnapshot/Utils.cs
  tools/gsnapshot/cloudbuild.yaml
  tools/gsnapshot/gsnapshot.csproj
  tools/gsnapshot/gsnapshot.wsx
  tools/gsnapshot/img/logo.png
Labels: size/XXL

#757 pubsub2inbox: added MS Graph API mail transport + few minor fixes
  tools/pubsub2inbox/README.md
  tools/pubsub2inbox/examples/mail-msgraphapi.yaml
  tools/pubsub2inbox/main.tf
  tools/pubsub2inbox/output/mail.py
  tools/pubsub2inbox/requirements.txt
  tools/pubsub2inbox/test/test_mail_msgraphapi.py
  tools/pubsub2inbox/variables.tf
Labels: size/L

#756 Feature - Cloud Composer backup and recovery tool
  README.md
  tools/cloud-composer-backup-restore/.gitignore
  tools/cloud-composer-backup-restore/.pylintrc
  tools/cloud-composer-backup-restore/README.md
  tools/cloud-composer-backup-restore/composer_br/__init__.py
  tools/cloud-composer-backup-restore/composer_br/__main__.py
  tools/cloud-composer-backup-restore/composer_br/app.py
  tools/cloud-composer-backup-restore/composer_br/command_utils.py
  tools/cloud-composer-backup-restore/composer_br/composer_env.py
  tools/cloud-composer-backup-restore/composer_br/db_utils.py
  tools/cloud-composer-backup-restore/composer_br/gke_utils.py
  tools/cloud-composer-backup-restore/composer_br/postgres.py
  tools/cloud-composer-backup-restore/requirements.txt
Labels: size/XXL

#758 gcs2bq updates (embed schema, logging improvements)
  tools/gcs2bq/README.md
  tools/gcs2bq/gcs2bq-custom-role.yaml
  tools/gcs2bq/gcs2bq.yaml
  tools/gcs2bq/go.mod
  tools/gcs2bq/go.sum
  tools/gcs2bq/main.go
Labels: size/M

#760 Rotate service accout keys in secret manager
  examples/rotate-service-account-keys/Readme.md
  examples/rotate-service-account-keys/main.py
  examples/rotate-service-account-keys/requirements.txt
Labels: size/L

#761 Billboard - Cost Usage Dashboard
  examples/billboard/README.md
  examples/billboard/billboard-walkthrough.md
  examples/billboard/billboard.py
  examples/billboard/requirements.txt
  examples/dbt-on-cloud-composer/basic/dag/dbt_with_kubernetes.py
  examples/dbt-on-cloud-composer/optimized/dag/dbt_with_kubernetes_optimized.py
  helpers/check_format.sh
  helpers/format.sh
Labels: size/L

#763 Fix: Sanitize arrays of primitive values in asset-inventory
  .shellcheckrc
  examples/dbt-on-cloud-composer/optimized/dag/dbt_with_kubernetes_optimized.py
  tools/asset-inventory/asset_inventory/bigquery_schema.py
Labels: size/S

#762 Modified wording to explicitly mention assigning roles
  tools/quota-monitoring-alerting/python/README.md
Labels: size/XS

#773 [New tool] XSD to BigQuery schema generator
  README.md
  tools/xsd-to-bigquery-schema/.gitignore
  tools/xsd-to-bigquery-schema/README.md
  tools/xsd-to-bigquery-schema/setup.py
  tools/xsd-to-bigquery-schema/tests/sample_data/customer_orders.xsd
  tools/xsd-to-bigquery-schema/tests/sample_data/invalid.xsd
  tools/xsd-to-bigquery-schema/tests/sample_data/nested.xsd
  tools/xsd-to-bigquery-schema/tests/sample_data/no-elements.xsd
  tools/xsd-to-bigquery-schema/tests/sample_data/simple.xsd
  tools/xsd-to-bigquery-schema/tests/sample_data/types.xsd
  tools/xsd-to-bigquery-schema/tests/test_xsd2bq.py
  tools/xsd-to-bigquery-schema/xsd2bq/__init__.py
  tools/xsd-to-bigquery-schema/xsd2bq/__main__.py
  tools/xsd-to-bigquery-schema/xsd2bq/xsd2bq.py
Labels: size/XL

#769 GCS to BQ using server-less services
  README.md
  examples/gcs-to-bq-serverless-services/Readme.md
  examples/gcs-to-bq-serverless-services/docs/gcs2bq_serverless_spark.jpg
  examples/gcs-to-bq-serverless-services/gcs2bq-spark/pom.xml
  examples/gcs-to-bq-serverless-services/gcs2bq-spark/src/main/java/com/example/GCS2BQ.java
  examples/gcs-to-bq-serverless-services/schema/schema.json
  examples/gcs-to-bq-serverless-services/trigger-serverless-spark-fxn/main.py
  examples/gcs-to-bq-serverless-services/trigger-serverless-spark-fxn/requirements.txt
Labels: size/XL

#775 pubsub2inbox: avoid compatibility issues caused by jinja2 and markupsafe
  tools/pubsub2inbox/requirements.txt
Labels: size/XS

#776 Bring PR #771 to main branch
  README.md
  examples/dfdl-firestore-pubsub-example/README.md
  examples/dfdl-firestore-pubsub-example/examples/binary_example_payload.txt
  examples/dfdl-firestore-pubsub-example/examples/bynary_example.dfdl.xsd
  examples/dfdl-firestore-pubsub-example/pom.xml
  examples/dfdl-firestore-pubsub-example/src/main/java/com/example/dfdl/DfdlDef.java
  examples/dfdl-firestore-pubsub-example/src/main/java/com/example/dfdl/DfdlDefRepository.java
  examples/dfdl-firestore-pubsub-example/src/main/java/com/example/dfdl/DfdlService.java
  examples/dfdl-firestore-pubsub-example/src/main/java/com/example/dfdl/FirestoreService.java
  examples/dfdl-firestore-pubsub-example/src/main/java/com/example/dfdl/MessageController.java
  examples/dfdl-firestore-pubsub-example/src/main/java/com/example/dfdl/ProcessorService.java
  examples/dfdl-firestore-pubsub-example/src/main/java/com/example/dfdl/PubSubServer.java
  examples/dfdl-firestore-pubsub-example/src/main/resources/application.properties
Labels: size/XL

#778 Fix gsnapshot user agent
  tools/gsnapshot/Utils.cs
Labels: size/XS

#777 Custom Role Analyzer
  README.md
  code-of-conduct.md
  tools/custom-roles-analyzer/README.md
  tools/custom-roles-analyzer/analyze.sh
  tools/custom-roles-analyzer/pom.xml
  tools/custom-roles-analyzer/src/main/java/com/google/cloud/pso/security/CustomRoleAnalyzer.java
  tools/custom-roles-analyzer/src/main/java/com/google/cloud/pso/security/constants/GenericConstants.java
  tools/custom-roles-analyzer/src/main/java/com/google/cloud/pso/security/iam/IamClient.java
  tools/custom-roles-analyzer/src/main/java/com/google/cloud/pso/security/iam/permission/PermissionUtil.java
  tools/custom-roles-analyzer/src/main/java/com/google/cloud/pso/security/iam/role/RoleUtil.java
  tools/custom-roles-analyzer/src/main/java/com/google/cloud/pso/security/resourcemanager/ResourceManagerClient.java
  tools/custom-roles-analyzer/src/main/java/com/google/cloud/pso/security/util/CustomRoleAnalyzerHelper.java
  tools/custom-roles-analyzer/src/main/java/com/google/cloud/pso/security/util/CustomRoleAnalyzerResult.java
Labels: size/XXL

#772 Google Cloud Support Slackbot rearchitecture for Cloud Run
  tools/google-cloud-support-slackbot/.dockerignore
  tools/google-cloud-support-slackbot/Dockerfile
  tools/google-cloud-support-slackbot/README.md
  tools/google-cloud-support-slackbot/archive/standalone/default
  tools/google-cloud-support-slackbot/archive/standalone/google_cloud_support_slackbot.py
  tools/google-cloud-support-slackbot/archive/standalone/requirements.txt
  tools/google-cloud-support-slackbot/case_details.py
  tools/google-cloud-support-slackbot/case_not_found.py
  tools/google-cloud-support-slackbot/case_updates.py
  tools/google-cloud-support-slackbot/env.list
  tools/google-cloud-support-slackbot/firestore_delete_cases.py
  tools/google-cloud-support-slackbot/firestore_write.py
  tools/google-cloud-support-slackbot/get_firestore_cases.py
  tools/google-cloud-support-slackbot/get_firestore_first_in.py
  tools/google-cloud-support-slackbot/get_firestore_tracked_cases.py
  tools/google-cloud-support-slackbot/get_parent.py
  tools/google-cloud-support-slackbot/list_tracked_cases.py
  tools/google-cloud-support-slackbot/list_tracked_cases_all.py
  tools/google-cloud-support-slackbot/main.py
  tools/google-cloud-support-slackbot/notify_slack.py
  tools/google-cloud-support-slackbot/post_help_message.py
  tools/google-cloud-support-slackbot/requirements.txt
  tools/google-cloud-support-slackbot/sitrep.py
  tools/google-cloud-support-slackbot/slackbot_integration_test.py
  tools/google-cloud-support-slackbot/stop_tracking.py
  tools/google-cloud-support-slackbot/support_add_comment.py
  tools/google-cloud-support-slackbot/support_case.py
  tools/google-cloud-support-slackbot/support_change_priority.py
  tools/google-cloud-support-slackbot/support_close_case.py
  tools/google-cloud-support-slackbot/support_create_case.py
  tools/google-cloud-support-slackbot/support_escalate.py
  tools/google-cloud-support-slackbot/support_subscribe_email.py
  tools/google-cloud-support-slackbot/track_case.py
Labels: size/XXL

#780 Add ability to specify folders and other filters when deploying the solution.
  tools/quota-monitoring-alerting/python/config.yaml
  tools/quota-monitoring-alerting/python/docs/release_notes.README.md
  tools/quota-monitoring-alerting/python/src/common/lib/projects_lib.py
  tools/quota-monitoring-alerting/python/src/quota/handlers/projects_handler.py
Labels: size/L
