Repository GoogleCloudPlatform/professional-services, pull requests merged in 2022-09, with the labels that each got.

#882 Update README.md
  examples/dialogflowcx-private-webhook-example/README.md
Labels: size/XS

#878 Implement metadata copy for create time
  tools/gcs-bucket-mover/README.md
  tools/gcs-bucket-mover/config.yaml
  tools/gcs-bucket-mover/gcs_bucket_mover/bucket_details.py
  tools/gcs-bucket-mover/gcs_bucket_mover/bucket_mover_service.py
  tools/gcs-bucket-mover/gcs_bucket_mover/cli.py
  tools/gcs-bucket-mover/gcs_bucket_mover/configuration.py
  tools/gcs-bucket-mover/requirements.txt
  tools/gcs-bucket-mover/tests/common.py
  tools/gcs-bucket-mover/tests/test_bucket_details.py
  tools/gcs-bucket-mover/tests/test_bucket_mover_service.py
Labels: size/L

#884 Mainframe Connector: remove inlining compiler options
  tools/bigquery-zos-mainframe-connector/gszutil/build.sbt
Labels: size/XS

#885 Upgrade apache beam SDK version.
  tools/asset-inventory/asset_inventory/api_schema.py
  tools/asset-inventory/asset_inventory/import_pipeline.py
  tools/asset-inventory/setup.py
Labels: size/S

#883 Add logging support
  tools/gcs-bucket-mover/README.md
  tools/gcs-bucket-mover/gcs_bucket_mover/bucket_mover_service.py
  tools/gcs-bucket-mover/gcs_bucket_mover/cli.py
  tools/gcs-bucket-mover/gcs_bucket_mover/configuration.py
Labels: size/L

#889 Update setup instructions to reflect current CAI asset creation mode
  tools/vpc-flowlogs-enforcer/README.md
Labels: size/XS

#890 Tutorials added to run SDF and TF Studio tool in ephemeral cloud shell using link
  tools/run-tool-using-cloud-shell/README.md
  tools/run-tool-using-cloud-shell/sdf/tutorial.md
  tools/run-tool-using-cloud-shell/tfstudio/tutorial.md
Labels: size/M

#887 Add Dataflow Example on streaming analytic to handle schema changes
  README.md
  examples/dataflow-streaming-schema-handler/.gitignore
  examples/dataflow-streaming-schema-handler/README.md
  examples/dataflow-streaming-schema-handler/img/architecture.png
  examples/dataflow-streaming-schema-handler/pom.xml
  examples/dataflow-streaming-schema-handler/src/license/license-header-style.xml
  examples/dataflow-streaming-schema-handler/src/license/license-header.txt
  examples/dataflow-streaming-schema-handler/src/main/java/com/google/cloud/pso/pipeline/PubsubToBigQueryJSON.java
  examples/dataflow-streaming-schema-handler/src/main/java/com/google/cloud/pso/transforms/JsonEventMatcher.java
  examples/dataflow-streaming-schema-handler/src/main/java/com/google/cloud/pso/transforms/JsonSchemaExist.java
  examples/dataflow-streaming-schema-handler/src/main/java/com/google/cloud/pso/transforms/ReadPubSub.java
  examples/dataflow-streaming-schema-handler/src/main/java/com/google/cloud/pso/util/BQDatasetSchemas.java
  examples/dataflow-streaming-schema-handler/src/main/java/com/google/cloud/pso/util/BigQueryConverters.java
  examples/dataflow-streaming-schema-handler/src/main/java/com/google/cloud/pso/util/Constants.java
  examples/dataflow-streaming-schema-handler/src/main/java/com/google/cloud/pso/util/ConvertEventToGenericFailureRow.java
  examples/dataflow-streaming-schema-handler/src/resources/person.json
  examples/dataflow-streaming-schema-handler/src/test/java/com/google/cloud/pso/transforms/JsonEventMatcherTest.java
  examples/dataflow-streaming-schema-handler/src/test/java/com/google/cloud/pso/transforms/JsonSchemaExistTest.java
Labels: size/XXL

#896 Update go.mod
  tools/spiffe-gcp-proxy/go.mod
Labels: size/XS
