Repository GoogleCloudPlatform/professional-services, pull requests merged in 2022-05, with the labels that each got.

#817 Sync Dashboard changes to qms-dev branch
  tools/quota-monitoring-alerting/python/README.md
  tools/quota-monitoring-alerting/python/docs/add_to_report.png
  tools/quota-monitoring-alerting/python/docs/change_title.png
  tools/quota-monitoring-alerting/python/docs/edit_and_share.png
  tools/quota-monitoring-alerting/python/terraform/common/main.tf
Labels: size/M

#818 Service Account Provider Refactoring
  tools/service-account-provider/example_gitlab_pipeline/terraform-apply.sh
  tools/service-account-provider/example_gitlab_pipeline/terraform-init.sh
  tools/service-account-provider/example_gitlab_pipeline/terraform-plan.sh
  tools/service-account-provider/infrastructure/main.tf
  tools/service-account-provider/infrastructure/variables.tf
Labels: size/L

#819 Added example GKE HA setup using spot VMs
  README.md
  examples/gke-ha-setup-using-spot-vms/.gitignore
  examples/gke-ha-setup-using-spot-vms/README.md
  examples/gke-ha-setup-using-spot-vms/drain-job.sh
  examples/gke-ha-setup-using-spot-vms/gke-cluster.tf
  examples/gke-ha-setup-using-spot-vms/k8s-deployment.tf
  examples/gke-ha-setup-using-spot-vms/k8s-drain-job.tf
  examples/gke-ha-setup-using-spot-vms/main.tf
  examples/gke-ha-setup-using-spot-vms/providers.tf
  examples/gke-ha-setup-using-spot-vms/variables.tf
Labels: size/XL

#821 Sync QMS Dashboard changes in python version
  tools/quota-monitoring-alerting/python/README.md
  tools/quota-monitoring-alerting/python/docs/add_to_report.png
  tools/quota-monitoring-alerting/python/docs/change_title.png
  tools/quota-monitoring-alerting/python/docs/edit_and_share.png
  tools/quota-monitoring-alerting/python/terraform/common/main.tf
Labels: size/M

#820 Apigee bundle to convert JSON post to GET params
  examples/apigee-json-to-queryparam/LICENSE
  examples/apigee-json-to-queryparam/README.md
  examples/apigee-json-to-queryparam/apiproxy/json-to-queryparam.xml
  examples/apigee-json-to-queryparam/apiproxy/policies/impose-quota.xml
  examples/apigee-json-to-queryparam/apiproxy/policies/json2queryparam.xml
  examples/apigee-json-to-queryparam/apiproxy/policies/remove-query-param-apikey.xml
  examples/apigee-json-to-queryparam/apiproxy/policies/verify-api-key.xml
  examples/apigee-json-to-queryparam/apiproxy/proxies/default.xml
  examples/apigee-json-to-queryparam/apiproxy/resources/jsc/json2queryparam.js
  examples/apigee-json-to-queryparam/apiproxy/targets/default.xml
Labels: size/XL

#816 Add cloud-functions-act-as example
  README.md
  examples/cloud-functions-act-as/.github/workflows/call-function.yml
  examples/cloud-functions-act-as/.gitignore
  examples/cloud-functions-act-as/README.md
  examples/cloud-functions-act-as/function.tf
  examples/cloud-functions-act-as/function/main.py
  examples/cloud-functions-act-as/function/requirements.txt
  examples/cloud-functions-act-as/iam.tf
  examples/cloud-functions-act-as/images/cf-act-as0.png
  examples/cloud-functions-act-as/images/cf-act-as1.png
  examples/cloud-functions-act-as/images/cf-act-as2.png
  examples/cloud-functions-act-as/images/cf-act-as3.png
  examples/cloud-functions-act-as/images/wif-authentication.png
  examples/cloud-functions-act-as/output.tf
  examples/cloud-functions-act-as/providers.tf
  examples/cloud-functions-act-as/secret.tf
  examples/cloud-functions-act-as/service-accounts.tf
  examples/cloud-functions-act-as/services.tf
  examples/cloud-functions-act-as/terraform.tfvars.sample
  examples/cloud-functions-act-as/variables.tf
  examples/cloud-functions-act-as/wip.tf
Labels: size/XL

#812 Add code to deploy composer in shared VPC environments
  examples/composer-shared-vpc/README.md
  examples/composer-shared-vpc/backend.tf.sample
  examples/composer-shared-vpc/composer_v1_pvt_shared_vpc/README.md
  examples/composer-shared-vpc/composer_v1_pvt_shared_vpc/firewall.tf
  examples/composer-shared-vpc/composer_v1_pvt_shared_vpc/iam.tf
  examples/composer-shared-vpc/composer_v1_pvt_shared_vpc/main.tf
  examples/composer-shared-vpc/composer_v1_pvt_shared_vpc/variables.tf
  examples/composer-shared-vpc/main.tf
  examples/composer-shared-vpc/provider.tf
  examples/composer-shared-vpc/shared/README.md
  examples/composer-shared-vpc/shared/firewall.tf
  examples/composer-shared-vpc/shared/iam.tf
  examples/composer-shared-vpc/shared/networks.tf
  examples/composer-shared-vpc/shared/outputs.tf
  examples/composer-shared-vpc/shared/projects.tf
  examples/composer-shared-vpc/shared/variables.tf
  examples/composer-shared-vpc/terraform.tfvars.sample
  examples/composer-shared-vpc/variables.tf
Labels: size/XXL

#822 WIF CF Act As review and add functions-framework example
  examples/cloud-functions-act-as/README.md
  examples/cloud-functions-act-as/function.tf
  examples/cloud-functions-act-as/function/main.py
  examples/cloud-functions-act-as/function/requirements.txt
Labels: size/L

#825 Insert received data at CloudRun Endpoint into BQ
  README.md
  examples/cloudrun-to-bq/Dockerfile
  examples/cloudrun-to-bq/README.md
  examples/cloudrun-to-bq/cloudbuild.yaml
  examples/cloudrun-to-bq/main.py
  examples/cloudrun-to-bq/main_test.py
  examples/cloudrun-to-bq/requirements-test.txt
  examples/cloudrun-to-bq/requirements.txt
  examples/composer-shared-vpc/README.md
Labels: size/L

#828 Fix method of obtaining service account token
  tools/anthosbm-ansible-module/roles/anthos/tasks/main.yml
Labels: size/S

#830 Update to spot
  examples/gke-ha-setup-using-spot-vms/drain-job.sh
Labels: size/S

#831 Projects recursion added to gcpohv-cli.py to fetch all projects instead of limited projects
  tools/gcp-org-hierarchy-viewer/gcpohv_cli.py
Labels: size/S

#832 gcpviz improvements (data access, performance, security)
  tools/gcpviz/Dockerfile
  tools/gcpviz/README.md
  tools/gcpviz/cmd/gcpviz/main.go
  tools/gcpviz/gcpviz.sh
  tools/gcpviz/gitlab-ci.yml
  tools/gcpviz/go.mod
  tools/gcpviz/go.sum
  tools/gcpviz/labels.yaml
  tools/gcpviz/main.go
  tools/gcpviz/queries/data.js
  tools/gcpviz/queries/everything.js
  tools/gcpviz/queries/gke.js
  tools/gcpviz/queries/instances.js
  tools/gcpviz/queries/load-balancing.js
  tools/gcpviz/queries/network-basic.js
  tools/gcpviz/queries/one-project-example.js
  tools/gcpviz/queries/security.js
  tools/gcpviz/queries/shared-vpc.js
  tools/gcpviz/queries/standalone-projects.js
  tools/gcpviz/queries/vpc-security.js
  tools/gcpviz/queries/vpns.js
  tools/gcpviz/redactor.py
  tools/gcpviz/relations.yaml
  tools/gcpviz/style.yaml
  tools/gcpviz/wait_for_export.sh
Labels: size/L
