Repository GoogleCloudPlatform/professional-services, pull requests merged in 2023-08, with the labels that each got.

#1054 New Version for tool/bq-visualiser
  .gitignore
  tools/bq-visualizer/.eslintrc.json
  tools/bq-visualizer/.gcloudignore
  tools/bq-visualizer/README.md
  tools/bq-visualizer/angular.json
  tools/bq-visualizer/app.yaml
  tools/bq-visualizer/cloudbuild.yaml
  tools/bq-visualizer/package-lock.json
  tools/bq-visualizer/package.json
  tools/bq-visualizer/src/app/app.component.html
  tools/bq-visualizer/src/app/app.component.ts
  tools/bq-visualizer/src/app/app.module.ts
  tools/bq-visualizer/src/app/big-query.service.spec.ts
  tools/bq-visualizer/src/app/big-query.service.ts
  tools/bq-visualizer/src/app/bq_job.ts
  tools/bq-visualizer/src/app/bq_query_plan.ts
  tools/bq-visualizer/src/app/google-auth.service.ts
  tools/bq-visualizer/src/app/job/job.component.css
  tools/bq-visualizer/src/app/job/job.component.html
  tools/bq-visualizer/src/app/job/job.component.ts
  tools/bq-visualizer/src/app/log-display/log-display.component.css
  tools/bq-visualizer/src/app/log-display/log-display.component.html
  tools/bq-visualizer/src/app/log.service.ts
  tools/bq-visualizer/src/app/log_message.ts
  tools/bq-visualizer/src/app/main/main.component.css
  tools/bq-visualizer/src/app/plan-side-display/plan-side-display.component.ts
  tools/bq-visualizer/src/app/plan-status-card/plan-status-card.component.css
  tools/bq-visualizer/src/app/plan-status-card/plan-status-card.component.html
  tools/bq-visualizer/src/app/plan-status-card/plan-status-card.component.ts
  tools/bq-visualizer/src/app/progress-display/progress-display.component.html
  tools/bq-visualizer/src/app/progress-display/progress-display.component.ts
  tools/bq-visualizer/src/app/projects/projects.component.css
  tools/bq-visualizer/src/app/projects/projects.component.html
  tools/bq-visualizer/src/app/projects/projects.component.ts
  tools/bq-visualizer/src/app/query-plan.service.ts
  tools/bq-visualizer/src/app/rest_interfaces.ts
  tools/bq-visualizer/src/app/stage-details/stage-details.component.css
  tools/bq-visualizer/src/app/stage-details/stage-details.component.html
  tools/bq-visualizer/src/app/stage-details/stage-details.component.ts
  tools/bq-visualizer/src/app/step-details/step-details.component.html
  tools/bq-visualizer/src/app/timing-display/timing-display.component.ts
  tools/bq-visualizer/src/app/vis-display/vis-display.component.ts
  tools/bq-visualizer/src/environments/environment.prod.ts
  tools/bq-visualizer/src/environments/environment.test.ts
  tools/bq-visualizer/src/environments/environment.ts
  tools/bq-visualizer/src/index.html
  tools/bq-visualizer/src/styles.css
  tools/bq-visualizer/src/tsconfig.app.json
  tools/bq-visualizer/tsconfig.json
Labels: size/XXL

#1059 Generic Metadata DDL Utility
  README.md
  examples/bigquery-generic-ddl-migration-utility/BQ_Table_Creator/bq_table_creator.py
  examples/bigquery-generic-ddl-migration-utility/BQ_Table_Creator/generic_bq_table_creator.md
  examples/bigquery-generic-ddl-migration-utility/DDL_Archiver/archive_ddl.py
  examples/bigquery-generic-ddl-migration-utility/DDL_Archiver/generic_archive_ddl.md
  examples/bigquery-generic-ddl-migration-utility/DDL_Converter/generic_bq_converter.md
  examples/bigquery-generic-ddl-migration-utility/DDL_Converter/generic_bq_converter.py
  examples/bigquery-generic-ddl-migration-utility/DDL_Extractor/generic_ddl_extraction.md
  examples/bigquery-generic-ddl-migration-utility/DDL_Extractor/generic_ddl_extractions.py
  examples/bigquery-generic-ddl-migration-utility/DDL_Extractor/mssql_metadata_extraction.py
  examples/bigquery-generic-ddl-migration-utility/DDL_Extractor/netezza_metadata_extraction.py
  examples/bigquery-generic-ddl-migration-utility/DDL_Extractor/oracle_metadata_extraction.py
  examples/bigquery-generic-ddl-migration-utility/DDL_Extractor/snowflake_metadata_extraction.py
  examples/bigquery-generic-ddl-migration-utility/DDL_Extractor/utils/__init__.py
  examples/bigquery-generic-ddl-migration-utility/DDL_Extractor/utils/setup_logger.py
  examples/bigquery-generic-ddl-migration-utility/DDL_Extractor/utils/utilities.py
  examples/bigquery-generic-ddl-migration-utility/DDL_Extractor/vertica_metadata_extraction.py
  examples/bigquery-generic-ddl-migration-utility/README.md
  examples/bigquery-generic-ddl-migration-utility/config/generic-ddl-extraction-config.json
  examples/bigquery-generic-ddl-migration-utility/config/metadata_columns.json
  examples/bigquery-generic-ddl-migration-utility/config/object_name_mapping.json
  examples/bigquery-generic-ddl-migration-utility/requirements.txt
  examples/bigquery-oracle-ddl-migration-utility/DDL_Extractor/oracle_ddl_extraction.py
Labels: size/XXL

#1077 Ephemeral Projects Example
  README.md
  examples/ephemeral-projects/README.md
  examples/ephemeral-projects/python/bindings.json
  examples/ephemeral-projects/python/init.json
  examples/ephemeral-projects/python/main.py
  examples/ephemeral-projects/python/project_deletion_example.py
  examples/ephemeral-projects/python/project_deployment_example.py
  examples/ephemeral-projects/python/project_iam_example.py
  examples/ephemeral-projects/python/requirements.txt
Labels: size/L

#1080 Update shellcheck to look for external bash file binding
  helpers/check_format.sh
Labels: size/XS
