Repository GoogleCloudPlatform/professional-services, pull requests merged in 2023-06, with the labels that each got.

#1039 Personal Workbench Notebooks Deployer Terraform Modules
  examples/personal-workbench-notebooks-deployer/README.md
  examples/personal-workbench-notebooks-deployer/dataproc_master_templates/per-auth-cluster.yaml
  examples/personal-workbench-notebooks-deployer/images/managed_notebooks.png
  examples/personal-workbench-notebooks-deployer/images/user_managed_notebooks.png
  examples/personal-workbench-notebooks-deployer/modules/personal-managed-notebook/README.md
  examples/personal-workbench-notebooks-deployer/modules/personal-managed-notebook/main.tf
  examples/personal-workbench-notebooks-deployer/modules/personal-managed-notebook/managed-notebook.tf
  examples/personal-workbench-notebooks-deployer/modules/personal-managed-notebook/outputs.tf
  examples/personal-workbench-notebooks-deployer/modules/personal-managed-notebook/providers.tf
  examples/personal-workbench-notebooks-deployer/modules/personal-managed-notebook/variables.tf
  examples/personal-workbench-notebooks-deployer/modules/personal-managed-notebook/versions.tf
  examples/personal-workbench-notebooks-deployer/modules/personal-user-managed-notebook/README.md
  examples/personal-workbench-notebooks-deployer/modules/personal-user-managed-notebook/enable_spark_bq.sh
  examples/personal-workbench-notebooks-deployer/modules/personal-user-managed-notebook/main.tf
  examples/personal-workbench-notebooks-deployer/modules/personal-user-managed-notebook/outputs.tf
  examples/personal-workbench-notebooks-deployer/modules/personal-user-managed-notebook/providers.tf
  examples/personal-workbench-notebooks-deployer/modules/personal-user-managed-notebook/template_generator.sh
  examples/personal-workbench-notebooks-deployer/modules/personal-user-managed-notebook/user_managed-notebook.tf
  examples/personal-workbench-notebooks-deployer/modules/personal-user-managed-notebook/variables.tf
  examples/personal-workbench-notebooks-deployer/modules/personal-user-managed-notebook/versions.tf
  examples/personal-workbench-notebooks-deployer/sample_modules_usage.tf
Labels: size/XL

#1042 Readme update, new example listed
  README.md
Labels: size/XS

#1040 Request for PR approval | Config generator for BQMS
  tools/bqms-config-generator/README.md
  tools/bqms-config-generator/config_generator/__init__.py
  tools/bqms-config-generator/config_generator/main.py
  tools/bqms-config-generator/config_generator/schema/json_schema.json
  tools/bqms-config-generator/config_generator/schema/yaml_schema.json
  tools/bqms-config-generator/config_generator/test/__init__.py
  tools/bqms-config-generator/config_generator/test/conftest.py
  tools/bqms-config-generator/config_generator/test/test_constants.py
  tools/bqms-config-generator/config_generator/test/test_csv_json_parser.py
  tools/bqms-config-generator/config_generator/test/test_csv_yaml_parser.py
  tools/bqms-config-generator/config_generator/test/test_utils.py
  tools/bqms-config-generator/config_generator/util/__init__.py
  tools/bqms-config-generator/config_generator/util/constants.py
  tools/bqms-config-generator/config_generator/util/csv_json_parser.py
  tools/bqms-config-generator/config_generator/util/csv_yaml_parser.py
  tools/bqms-config-generator/config_generator/util/model.py
  tools/bqms-config-generator/config_generator/util/utils.py
  tools/bqms-config-generator/config_generator/util/validator.py
  tools/bqms-config-generator/input/conf_prep_path.yaml
  tools/bqms-config-generator/input/hive_bq_datatype_map.csv
  tools/bqms-config-generator/input/object_mapv2.csv
  tools/bqms-config-generator/output/ATR_mapping.yaml
  tools/bqms-config-generator/output/object_mapping.json
  tools/bqms-config-generator/pyproject.toml
  tools/bqms-config-generator/run.sh
Labels: size/XXL
