Repository GoogleCloudPlatform/professional-services, pull requests merged in 2023-10, with the labels that each got.

#1088 add cloud-composer-migration-terraform-generator
  README.md
  tools/cloud-composer-migration-terraform-generator/README.md
  tools/cloud-composer-migration-terraform-generator/query_task_template.json
  tools/cloud-composer-migration-terraform-generator/terraform-generate.sh
  tools/cloud-composer-migration-terraform-generator/terraform/main.tf
  tools/cloud-composer-migration-terraform-generator/terraform/sample.tfvars
  tools/cloud-composer-migration-terraform-generator/terraform/variables.tf
Labels: size/L

#1089 add cloud-composer-migration-complexity-assessment
  README.md
  tools/cloud-composer-migration-complexity-assessment/README.md
  tools/cloud-composer-migration-complexity-assessment/airflow-v1-to-v2-migration/.airflowignore
  tools/cloud-composer-migration-complexity-assessment/airflow-v1-to-v2-migration/README.md
  tools/cloud-composer-migration-complexity-assessment/airflow-v1-to-v2-migration/__init__.py
  tools/cloud-composer-migration-complexity-assessment/airflow-v1-to-v2-migration/airflow_migration/__init__.py
  tools/cloud-composer-migration-complexity-assessment/airflow-v1-to-v2-migration/airflow_migration/migration.py
  tools/cloud-composer-migration-complexity-assessment/airflow-v1-to-v2-migration/migration_rules/rules.csv
  tools/cloud-composer-migration-complexity-assessment/airflow-v1-to-v2-migration/misc/migration.py
  tools/cloud-composer-migration-complexity-assessment/airflow-v1-to-v2-migration/requirements.txt
  tools/cloud-composer-migration-complexity-assessment/airflow-v1-to-v2-migration/run_mig.py
  tools/cloud-composer-migration-complexity-assessment/dags/complexity-assess.sql
  tools/cloud-composer-migration-complexity-assessment/dags/migration_assessment.py
Labels: size/XXL

#1114 Adding code for IAP IDP Connect
  examples/iap-idp-connect/README.md
  examples/iap-idp-connect/connect.py
  examples/iap-idp-connect/connect_test.py
  examples/iap-idp-connect/exceptions/connector_exception.py
  examples/iap-idp-connect/requirements.txt
  examples/iap-idp-connect/setup_dependencies.sh
  examples/iap-idp-connect/utils/validator.py
Labels: size/XL

#1112 add: Cloud dns dashboard for public zones monitoring
  README.md
  examples/cloud-dns-public-zone-dashboard/README.md
  examples/cloud-dns-public-zone-dashboard/config.yaml
  examples/cloud-dns-public-zone-dashboard/dashboard.json
  examples/cloud-dns-public-zone-dashboard/latency-config.yaml
Labels: size/XL

#1091 data load from gcs to bq using cloud composer DAG
  examples/gcs-to-bq/README.md
  examples/gcs-to-bq/data-ingestion/asset/config.png
  examples/gcs-to-bq/data-ingestion/asset/dag_image.png
  examples/gcs-to-bq/data-ingestion/cloudbuild.yaml
  examples/gcs-to-bq/data-ingestion/dags/common_layer.py
  examples/gcs-to-bq/data-ingestion/data/common_layer/config/common_layer_config_defaults.yml
  examples/gcs-to-bq/data-ingestion/data/common_layer/config/common_layer_config_ingestion_demo.yml
  examples/gcs-to-bq/data-ingestion/plugins/includes/entities.py
  examples/gcs-to-bq/data-ingestion/plugins/includes/exceptions.py
  examples/gcs-to-bq/data-ingestion/plugins/includes/loggers.py
  examples/gcs-to-bq/data-ingestion/plugins/includes/utils.py
Labels: size/XL

#1118 feat: modified teradata connection for bigquery-ddl-validator
  examples/bigquery-ddl-validator/plugin/teradata/teradata.py
Labels: size/M

#1035 Example: Dataflow BigQuery to AlloyDB
  README.md
  examples/dataflow-bigquery-to-alloydb/.gitignore
  examples/dataflow-bigquery-to-alloydb/README.md
  examples/dataflow-bigquery-to-alloydb/main.py
  examples/dataflow-bigquery-to-alloydb/requirements.txt
Labels: size/L

#1119 fix: use full resource name for spiffe proxy audience claim
  tools/spiffe-gcp-proxy/main.go
Labels: size/XS

#1041 GKE autopsc controller
  README.md
  tools/gke-autopsc-controller/Dockerfile
  tools/gke-autopsc-controller/README.md
  tools/gke-autopsc-controller/controllers/gateway_controller.go
  tools/gke-autopsc-controller/controllers/long_running_operations.go
  tools/gke-autopsc-controller/controllers/types.go
  tools/gke-autopsc-controller/deploy/autopsc.yaml
  tools/gke-autopsc-controller/deploy/workload_identity.sh
  tools/gke-autopsc-controller/example/README.md
  tools/gke-autopsc-controller/example/app.yaml
  tools/gke-autopsc-controller/example/gateway.yaml
  tools/gke-autopsc-controller/go.mod
  tools/gke-autopsc-controller/go.sum
  tools/gke-autopsc-controller/main.go
Labels: size/XXL

#1132 Add certificate-authority-service-hierarchy example
  README.md
  examples/certificate-authority-service-hierarchy/.gitignore
  examples/certificate-authority-service-hierarchy/README.md
  examples/certificate-authority-service-hierarchy/apis.tf
  examples/certificate-authority-service-hierarchy/cas-scaling.tf.sample
  examples/certificate-authority-service-hierarchy/cas-template.tf
  examples/certificate-authority-service-hierarchy/certificates.tf
  examples/certificate-authority-service-hierarchy/common.tf
  examples/certificate-authority-service-hierarchy/images/deployment.png
  examples/certificate-authority-service-hierarchy/load-cas.sh
  examples/certificate-authority-service-hierarchy/modules/cas-ca/apis.tf
  examples/certificate-authority-service-hierarchy/modules/cas-ca/ca.tf
  examples/certificate-authority-service-hierarchy/modules/cas-ca/iam-policies.tf
  examples/certificate-authority-service-hierarchy/modules/cas-ca/kms-key.tf
  examples/certificate-authority-service-hierarchy/modules/cas-ca/outputs.tf
  examples/certificate-authority-service-hierarchy/modules/cas-ca/variables.tf
  examples/certificate-authority-service-hierarchy/modules/cas-pool/ca-pool.tf
  examples/certificate-authority-service-hierarchy/modules/cas-pool/iam-policies.tf
  examples/certificate-authority-service-hierarchy/modules/cas-pool/outputs.tf
  examples/certificate-authority-service-hierarchy/modules/cas-pool/variables.tf
  examples/certificate-authority-service-hierarchy/providers.tf
  examples/certificate-authority-service-hierarchy/root-ca.tf
  examples/certificate-authority-service-hierarchy/root-pool.tf
  examples/certificate-authority-service-hierarchy/sub-activation.tf.sample
  examples/certificate-authority-service-hierarchy/sub-ca.tf
  examples/certificate-authority-service-hierarchy/sub-pool.tf
  examples/certificate-authority-service-hierarchy/terraform.tfvars.sample
  examples/certificate-authority-service-hierarchy/variables.tf
Labels: size/XXL

#1142 Update Migration Assessment tooling to not include converted code in output
  tools/cloud-composer-migration-complexity-assessment/dags/migration_assessment.py
Labels: size/XS

#1143 Update Cloud Composer Example Tests with new DAG Quality test
  examples/cloud-composer-examples/tests/test_dags_quality.py
Labels: size/L

#1127 IPAM Autopilot: Adapt subnet overlap check
  tools/ipam-autopilot/container/data_access.go
  tools/ipam-autopilot/container/ipam_test.go
Labels: size/M

#1144 Fixes in MLOPs enterprise
  examples/vertex_mlops_enterprise/doc/01-ENVIRONMENTS.md
  examples/vertex_mlops_enterprise/src/kfp_pipelines/Dockerfile.modelcard
  examples/vertex_mlops_enterprise/src/kfp_pipelines/src/eval.py
  examples/vertex_mlops_enterprise/src/kfp_pipelines/src/load.py
  examples/vertex_mlops_enterprise/terraform/01-dev/main.tf
  examples/vertex_mlops_enterprise/terraform/01-dev/outputs.tf
Labels: size/S

#1151 Add cloud-composer-dag-validation folder
  README.md
  tools/cloud-composer-dag-validation/Dockerfile
  tools/cloud-composer-dag-validation/README.md
  tools/cloud-composer-dag-validation/cloudbuild.yaml
  tools/cloud-composer-dag-validation/dag_validation.py
  tools/cloud-composer-dag-validation/dags/test_dag.py
  tools/cloud-composer-dag-validation/requirements.txt
Labels: size/L

#1162 Fix requirements.txt after dependabot broke compatibility
  examples/vertex_mlops_enterprise/requirements.txt
Labels: size/XS

#1164 Update model-deployment.yaml.TEMPLATE
  examples/vertex_mlops_enterprise/build/model-deployment.yaml.TEMPLATE
Labels: size/XS

#1145 Content for tool gcve2bq
  README.md
  tools/gcve2bq/Dockerfile
  tools/gcve2bq/Readme.md
  tools/gcve2bq/cloudbuild.yaml
  tools/gcve2bq/get-gcve-util.ps1
  tools/gcve2bq/terraform/README.md
  tools/gcve2bq/terraform/artifact-registry.tf
  tools/gcve2bq/terraform/bq.tf
  tools/gcve2bq/terraform/cloudrun.tf
  tools/gcve2bq/terraform/scheduler.tf
  tools/gcve2bq/terraform/terraform.tfvars.example
  tools/gcve2bq/terraform/variables.tf
  tools/gcve2bq/terraform/version.tf
Labels: size/XL

#1165 Memorystore Cluster Ops Utility
  tools/memorystore-cluster-ops-framework/README.md
  tools/memorystore-cluster-ops-framework/backup-mrc.py
  tools/memorystore-cluster-ops-framework/config.json
  tools/memorystore-cluster-ops-framework/migrate-validate-mrc.py
  tools/memorystore-cluster-ops-framework/mrc_framework.py
  tools/memorystore-cluster-ops-framework/requirements.txt
  tools/memorystore-cluster-ops-framework/restore-mrc.py
Labels: size/XL

#1146 Initial code for Amazon S3 to BigQuery Migration tool
  README.md
  tools/bigquery-s3tobq/.gitignore
  tools/bigquery-s3tobq/README.md
  tools/bigquery-s3tobq/core/Dockerfile
  tools/bigquery-s3tobq/core/bq.py
  tools/bigquery-s3tobq/core/composer.py
  tools/bigquery-s3tobq/core/config.yaml
  tools/bigquery-s3tobq/core/gcs.py
  tools/bigquery-s3tobq/core/main.py
  tools/bigquery-s3tobq/core/main_test.py
  tools/bigquery-s3tobq/core/requirements-test.txt
  tools/bigquery-s3tobq/core/requirements.txt
  tools/bigquery-s3tobq/core/trigger.py
  tools/bigquery-s3tobq/dags/bq_dag.py
  tools/bigquery-s3tobq/sts.py
Labels: size/XL

#1166 2nd Review: BigQuery data consolidator
  README.md
  tools/bigquery-data-consolidator/Dockerfile
  tools/bigquery-data-consolidator/README.md
  tools/bigquery-data-consolidator/requirements.txt
  tools/bigquery-data-consolidator/src/copy_bq_table.py
  tools/bigquery-data-consolidator/src/list_all_projects.py
  tools/bigquery-data-consolidator/src/list_datasets.py
  tools/bigquery-data-consolidator/src/list_tables_in_dataset.py
  tools/bigquery-data-consolidator/src/main.py
Labels: size/XL

#1167 Jgpuga/mlops
  examples/vertex_mlops_enterprise/.github/workflows/containers.yml.TEMPLATE
  examples/vertex_mlops_enterprise/.github/workflows/deploy.yml.TEMPLATE
  examples/vertex_mlops_enterprise/.gitignore
  examples/vertex_mlops_enterprise/README.md
  examples/vertex_mlops_enterprise/build/model-deployment-tfx.yaml.TEMPLATE
  examples/vertex_mlops_enterprise/build/pipeline-deployment-bqml.yaml.TEMPLATE
  examples/vertex_mlops_enterprise/doc/01-ENVIRONMENTS.md
  examples/vertex_mlops_enterprise/src/bqml_pipeline/Dockerfile
  examples/vertex_mlops_enterprise/src/bqml_pipeline/README.md
  examples/vertex_mlops_enterprise/src/bqml_pipeline/requirements.txt
  examples/vertex_mlops_enterprise/src/bqml_pipeline/src/config.py
  examples/vertex_mlops_enterprise/src/bqml_pipeline/src/pipeline.py
  examples/vertex_mlops_enterprise/src/bqml_pipeline/src/xgb-creditcards.json
  examples/vertex_mlops_enterprise/terraform/01-dev/outputs.tf
  examples/vertex_mlops_enterprise/terraform/02-staging/main.tf
  examples/vertex_mlops_enterprise/terraform/02-staging/outputs.tf
  examples/vertex_mlops_enterprise/terraform/02-staging/terraform.tfvars.sample
  examples/vertex_mlops_enterprise/terraform/02-staging/variables.tf
  examples/vertex_mlops_enterprise/terraform/03-prod/main.tf
  examples/vertex_mlops_enterprise/terraform/03-prod/outputs.tf
  examples/vertex_mlops_enterprise/terraform/03-prod/terraform.tfvars.sample
  examples/vertex_mlops_enterprise/terraform/03-prod/variables.tf
Labels: size/XXL
