Repository GoogleCloudPlatform/professional-services, pull requests merged in 2023-03, with the labels that each got.

#998 Adding Dataflow xml pubsub to gcs example
  CONTRIBUTING.md
  README.md
  examples/dataflow-xml-pubsub-to-gcs/README.md
  examples/dataflow-xml-pubsub-to-gcs/img/Dataflow PubSub XML to GCS.png
  examples/dataflow-xml-pubsub-to-gcs/python/.vscode/launch.json
  examples/dataflow-xml-pubsub-to-gcs/python/README.md
  examples/dataflow-xml-pubsub-to-gcs/python/beamPubSubXml2Gcs.py
  examples/dataflow-xml-pubsub-to-gcs/python/publish2PubSub.py
  examples/dataflow-xml-pubsub-to-gcs/python/requirements.txt
Labels: size/XL

#994 Standalone service on bq
  README.md
  examples/bq-remote-function/README.md
  examples/bq-remote-function/string_formatter/pom.xml
  examples/bq-remote-function/string_formatter/src/main/java/com/google/cloud/pso/bqremotefunc/StringFormat.java
  examples/bq-remote-function/string_formatter/src/main/java/com/google/cloud/pso/bqremotefunc/util/FunctionResponseObj.java
  examples/bq-remote-function/string_formatter/src/main/java/com/google/cloud/pso/bqremotefunc/util/UserDefinedContext.java
  examples/bq-remote-function/string_formatter/src/main/java/com/google/cloud/pso/bqremotefunc/util/remoteFunctionObject.java
Labels: size/L

#996 Updates the URL to the new Billing dashboard
  examples/billboard/billboard.py
Labels: size/XS

#999 Example of Orchestrating Notebook Executions on Dataproc via Cloud Composer
  README.md
  examples/dataproc-running-notebooks/README.md
  examples/dataproc-running-notebooks/composer_input/DAGs/composer_pyspark_notebook.py
  examples/dataproc-running-notebooks/composer_input/initialization_scripts/init_pip_gcsfuse.sh
  examples/dataproc-running-notebooks/composer_input/jobs/wrapper_papermill.py
  examples/dataproc-running-notebooks/notebooks/jupyter/sample_notebook.ipynb
  examples/dataproc-running-notebooks/notebooks/python/sample.py
Labels: size/L

#997 Add GDCE Terraform Example
  README.md
  examples/gdce-terraform-example/README.md
  examples/gdce-terraform-example/cloudbuild-destroy.yaml
  examples/gdce-terraform-example/cloudbuild.yaml
  examples/gdce-terraform-example/terraform/backend.tf.sample
  examples/gdce-terraform-example/terraform/main.tf
  examples/gdce-terraform-example/terraform/modules/google_gdce_cluster/main.tf
  examples/gdce-terraform-example/terraform/modules/google_gdce_cluster/output.tf
  examples/gdce-terraform-example/terraform/modules/google_gdce_cluster/providers.tf
  examples/gdce-terraform-example/terraform/modules/google_gdce_cluster/scripts/create.sh
  examples/gdce-terraform-example/terraform/modules/google_gdce_cluster/scripts/delete.sh
  examples/gdce-terraform-example/terraform/modules/google_gdce_cluster/scripts/read.sh
  examples/gdce-terraform-example/terraform/modules/google_gdce_cluster/scripts/update.sh
  examples/gdce-terraform-example/terraform/modules/google_gdce_cluster/variables.tf
  examples/gdce-terraform-example/terraform/modules/google_gdce_node_pool/main.tf
  examples/gdce-terraform-example/terraform/modules/google_gdce_node_pool/providers.tf
  examples/gdce-terraform-example/terraform/modules/google_gdce_node_pool/scripts/create.sh
  examples/gdce-terraform-example/terraform/modules/google_gdce_node_pool/scripts/delete.sh
  examples/gdce-terraform-example/terraform/modules/google_gdce_node_pool/scripts/read.sh
  examples/gdce-terraform-example/terraform/modules/google_gdce_node_pool/scripts/update.sh
  examples/gdce-terraform-example/terraform/modules/google_gdce_node_pool/variables.tf
  examples/gdce-terraform-example/terraform/modules/google_gdce_vpn_connection/main.tf
  examples/gdce-terraform-example/terraform/modules/google_gdce_vpn_connection/providers.tf
  examples/gdce-terraform-example/terraform/modules/google_gdce_vpn_connection/scripts/create.sh
  examples/gdce-terraform-example/terraform/modules/google_gdce_vpn_connection/scripts/delete.sh
  examples/gdce-terraform-example/terraform/modules/google_gdce_vpn_connection/scripts/read.sh
  examples/gdce-terraform-example/terraform/modules/google_gdce_vpn_connection/scripts/update.sh
  examples/gdce-terraform-example/terraform/modules/google_gdce_vpn_connection/variables.tf
  examples/gdce-terraform-example/terraform/terraform.tfvars.sample
  examples/gdce-terraform-example/terraform/variables.tf
Labels: size/XL

#995 New Dashboard Template and Permission checks
  examples/billboard/billboard.py
  examples/billboard/requirements.txt
Labels: size/M

#1001 bigquery-translation-validator-utility added
  examples/bigquery-translation-validator-utility/.gitignore
  examples/bigquery-translation-validator-utility/README.md
  examples/bigquery-translation-validator-utility/config/functions.csv
  examples/bigquery-translation-validator-utility/main.py
  examples/bigquery-translation-validator-utility/requirements.txt
  examples/bigquery-translation-validator-utility/utils/utils.py
  examples/bigquery-translation-validator-utility/validations/column_validation/column_validation.md
  examples/bigquery-translation-validator-utility/validations/column_validation/column_validation.py
  examples/bigquery-translation-validator-utility/validations/functions_validation/functions_validation.md
  examples/bigquery-translation-validator-utility/validations/functions_validation/functions_validation.py
  examples/bigquery-translation-validator-utility/validations/join_validation/join_validation.md
  examples/bigquery-translation-validator-utility/validations/join_validation/join_validation.py
  examples/bigquery-translation-validator-utility/validations/line_count/line_count.md
  examples/bigquery-translation-validator-utility/validations/line_count/line_count.py
  examples/bigquery-translation-validator-utility/validations/object_validation/object_validation.md
  examples/bigquery-translation-validator-utility/validations/object_validation/object_validation.py
Labels: size/XL

#1002 replace default estimate CCU parameters and demo image
  tools/capacity-planner-sheets-extension/images/capacity_planner_planning_sheet.png
  tools/capacity-planner-sheets-extension/main.js
Labels: size/XS
