Repository GoogleCloudPlatform/professional-services, pull requests merged in 2023-04, with the labels that each got.

#1016 ZetaSQL Toolkit library - Version 0.2.1
  tools/zetasql-helper/zetasql-toolkit-core/pom.xml
  tools/zetasql-helper/zetasql-toolkit-core/src/main/java/com/google/zetasql/toolkit/catalog/CatalogWrapper.java
  tools/zetasql-helper/zetasql-toolkit-core/src/main/java/com/google/zetasql/toolkit/catalog/bigquery/BigQueryCatalog.java
  tools/zetasql-helper/zetasql-toolkit-core/src/main/java/com/google/zetasql/toolkit/catalog/spanner/SpannerCatalog.java
  tools/zetasql-helper/zetasql-toolkit-examples/pom.xml
Labels: size/M

#1009 bigquery-long-running-optimization added
  README.md
  examples/bigquery-long-running-optimizer/.gitignore
  examples/bigquery-long-running-optimizer/Readme.md
  examples/bigquery-long-running-optimizer/airflow_long_optimization.py
  examples/bigquery-long-running-optimizer/main_dag.py
  examples/bigquery-long-running-optimizer/optimization/cross_join/cross_join.md
  examples/bigquery-long-running-optimizer/optimization/cross_join/cross_join.py
  examples/bigquery-long-running-optimizer/optimization/custom_table_expression/custom_table_expression.md
  examples/bigquery-long-running-optimizer/optimization/custom_table_expression/custom_table_expression.py
  examples/bigquery-long-running-optimizer/optimization/distinct/distinct.md
  examples/bigquery-long-running-optimizer/optimization/distinct/distinct.py
  examples/bigquery-long-running-optimizer/optimization/filter_data_before_join/filter_data_before_join.md
  examples/bigquery-long-running-optimizer/optimization/filter_data_before_join/filter_data_before_join.py
  examples/bigquery-long-running-optimizer/optimization/ntile_to_appprox_quant/ntile_to_appprox_quant.py
  examples/bigquery-long-running-optimizer/optimization/ntile_to_appprox_quant/ntile_to_approx_quant.md
  examples/bigquery-long-running-optimizer/optimization/reduce_to_tmp_tables/reduce_to_tmp_tables.md
  examples/bigquery-long-running-optimizer/optimization/reduce_to_tmp_tables/reduce_to_tmp_tables.py
  examples/bigquery-long-running-optimizer/optimization/regex_contains/regex_contains.md
  examples/bigquery-long-running-optimizer/optimization/regex_contains/regex_contains.py
  examples/bigquery-long-running-optimizer/optimization/select_wildcard/select_wildcard.md
  examples/bigquery-long-running-optimizer/optimization/select_wildcard/select_wildcard.py
  examples/bigquery-long-running-optimizer/optimization/self_join/self_join.md
  examples/bigquery-long-running-optimizer/optimization/self_join/self_join.py
  examples/bigquery-long-running-optimizer/requirements.txt
  examples/bigquery-long-running-optimizer/utils_optimization/utils_optimization.py
Labels: size/XXL

#1011 BigQuery Translation Validator : V2
  README.md
  examples/bigquery-translation-validator-utility/README.md
  examples/bigquery-translation-validator-utility/composer_dag/bq-datavalidator.py
  examples/bigquery-translation-validator-utility/main_dag.py
  examples/bigquery-translation-validator-utility/requirements.txt
  examples/bigquery-translation-validator-utility/utils/utils.py
  examples/bigquery-translation-validator-utility/validations/dry_run/dry_run.md
  examples/bigquery-translation-validator-utility/validations/dry_run/dry_run.py
  examples/bigquery-translation-validator-utility/validations/isnull_validation/isnull_validation.md
  examples/bigquery-translation-validator-utility/validations/isnull_validation/isnull_validation.py
  examples/bigquery-translation-validator-utility/validations/line_count/line_count.py
Labels: size/XL

#1017 Added Terraform code to create HA VPN Tunnels between GCP and Azure
  README.md
  tools/gcp-azure-ha-vpn/README.md
  tools/gcp-azure-ha-vpn/azure.tf
  tools/gcp-azure-ha-vpn/gcp.tf
  tools/gcp-azure-ha-vpn/outputs.tf
  tools/gcp-azure-ha-vpn/provider.tf
  tools/gcp-azure-ha-vpn/terraform.tfvars
  tools/gcp-azure-ha-vpn/variables.tf
Labels: size/XL

#1010 Add a link to migrate_instance function in README
  tools/gce-google-keys-to-cmek/README.md
Labels: size/XS

#1019 Fix ORA-06502 error caused by overflowing the customSchema variable
  tools/numeric-family-recommender-oracle/Oracle_Number_Recommender_GCP.sql
  tools/numeric-family-recommender-oracle/Oracle_Number_Recommender_GCP_11g.sql
Labels: size/XS

#1018 Added support for mixed case and special characters in schema and tab…
  tools/numeric-family-recommender-oracle/Oracle_Number_Recommender_GCP.sql
  tools/numeric-family-recommender-oracle/Oracle_Number_Recommender_GCP_11g.sql
Labels: size/S

#1020 Dialogflow Middlware Sample Code
  README.md
  examples/ccai-dialogflow-middleware/README.md
  examples/ccai-dialogflow-middleware/pom.xml
  examples/ccai-dialogflow-middleware/src/main/java/com/middleware/controller/cache/MapperCache.java
  examples/ccai-dialogflow-middleware/src/main/java/com/middleware/controller/cache/RedisUtil.java
  examples/ccai-dialogflow-middleware/src/main/java/com/middleware/controller/dialogflow/DialogflowConversationHandler.java
  examples/ccai-dialogflow-middleware/src/main/java/com/middleware/controller/dialogflow/WebhookHandler.java
  examples/ccai-dialogflow-middleware/src/main/java/com/middleware/controller/rest/Controller.java
  examples/ccai-dialogflow-middleware/src/main/java/com/middleware/controller/rest/ProcessorService.java
  examples/ccai-dialogflow-middleware/src/main/java/com/middleware/controller/twilio/MarketplaceAddOn.java
  examples/ccai-dialogflow-middleware/src/main/java/com/middleware/controller/twilio/TwilioConversation.java
  examples/ccai-dialogflow-middleware/src/main/java/com/middleware/controller/util/ConversationInitializer.java
  examples/ccai-dialogflow-middleware/src/main/java/com/middleware/controller/wehbook/NewMessage.java
  examples/ccai-dialogflow-middleware/src/main/java/com/middleware/controller/wehbook/NewParticipant.java
  examples/ccai-dialogflow-middleware/src/main/proto/dialogflow.proto
  examples/ccai-dialogflow-middleware/src/main/resources/application.properties
Labels: size/XXL
