Repository GoogleCloudPlatform/professional-services, pull requests merged in 2023-05, with the labels that each got.

#1026 bigquery-ddl-validator added
  README.md
  examples/bigquery-ddl-validator/.gitignore
  examples/bigquery-ddl-validator/Readme.md
  examples/bigquery-ddl-validator/airflow_ddl_validator.py
  examples/bigquery-ddl-validator/audit_operation.py
  examples/bigquery-ddl-validator/iac/Readme.md
  examples/bigquery-ddl-validator/iac/create_cloudsql_instance.tf
  examples/bigquery-ddl-validator/iac/providers.tf
  examples/bigquery-ddl-validator/iac/terraform.tfvars
  examples/bigquery-ddl-validator/iac/variables.tf
  examples/bigquery-ddl-validator/main.py
  examples/bigquery-ddl-validator/main_dag.py
  examples/bigquery-ddl-validator/plugin/hive/hive.md
  examples/bigquery-ddl-validator/plugin/hive/hive.py
  examples/bigquery-ddl-validator/plugin/oracle/oracle.md
  examples/bigquery-ddl-validator/plugin/oracle/oracle.py
  examples/bigquery-ddl-validator/plugin/snowflake/snowflake.md
  examples/bigquery-ddl-validator/plugin/snowflake/snowflake.py
  examples/bigquery-ddl-validator/plugin/teradata/teradata.md
  examples/bigquery-ddl-validator/plugin/teradata/teradata.py
  examples/bigquery-ddl-validator/requirements.txt
  examples/bigquery-ddl-validator/utils.py
Labels: size/XXL

#1025 Google Cloud Support Slackbot - Updated Dockerfile and README.md
  tools/google-cloud-support-slackbot/Dockerfile
  tools/google-cloud-support-slackbot/README.md
Labels: size/M

#1008 Bigdata Generator
  README.md
  tools/bigdata-generator/.gitignore
  tools/bigdata-generator/Dockerfile
  tools/bigdata-generator/README.md
  tools/bigdata-generator/config_file_samples/full_sample.json
  tools/bigdata-generator/config_file_samples/sales_sample_bigquery.json
  tools/bigdata-generator/doc/config-fields.md
  tools/bigdata-generator/doc/config-sinks.md
  tools/bigdata-generator/doc/config.md
  tools/bigdata-generator/doc/example.md
  tools/bigdata-generator/doc/media/example_autoscaling.png
  tools/bigdata-generator/doc/media/example_data.png
  tools/bigdata-generator/doc/media/example_dataflow.png
  tools/bigdata-generator/lib.py
  tools/bigdata-generator/main.py
  tools/bigdata-generator/requirements.txt
  tools/bigdata-generator/test/README.md
  tools/bigdata-generator/test/config.json
  tools/bigdata-generator/test/test.py
Labels: size/XXL

#1032 Cloud Composer Test Dag Generator
  README.md
  tools/cloud-composer-dag-generator/README.md
  tools/cloud-composer-dag-generator/config.json
  tools/cloud-composer-dag-generator/dag_generator/__init__.py
  tools/cloud-composer-dag-generator/dag_generator/__main__.py
  tools/cloud-composer-dag-generator/dag_generator/modules/__init__.py
  tools/cloud-composer-dag-generator/dag_generator/modules/initDag.py
  tools/cloud-composer-dag-generator/dag_generator/modules/operators.py
  tools/cloud-composer-dag-generator/out/.gitkeep
  tools/cloud-composer-dag-generator/pause_dags.sh
  tools/cloud-composer-dag-generator/run_dags.sh
Labels: size/L
