Repository GoogleCloudPlatform/professional-services, pull requests merged in 2023-01, with the labels that each got.

#968 add support for signed numeric character fields
  tools/bigquery-zos-mainframe-connector/gszutil/build.sbt
  tools/bigquery-zos-mainframe-connector/gszutil/src/main/scala/com/google/cloud/gszutil/CopyBookDecoderAndEncoderOps.scala
  tools/bigquery-zos-mainframe-connector/gszutil/src/main/scala/com/google/cloud/gszutil/Decoding.scala
  tools/bigquery-zos-mainframe-connector/gszutil/src/main/scala/com/google/cloud/gszutil/Encoding.scala
  tools/bigquery-zos-mainframe-connector/gszutil/src/test/scala/com/google/cloud/bqsh/CopyBookSpec.scala
  tools/bigquery-zos-mainframe-connector/mainframe-util/build.sbt
  tools/bigquery-zos-mainframe-connector/mainframe-util/src/main/scala/com/google/cloud/imf/util/CCASSLSocketFactory.scala
  tools/bigquery-zos-mainframe-connector/mainframe-util/src/main/scala/com/google/cloud/imf/util/CCATransportFactory.scala
Labels: size/L

#973 Mainframe Connector: add support for alternate form of precision and scale
  tools/bigquery-zos-mainframe-connector/gszutil/src/main/scala/com/google/cloud/gszutil/CopyBookDecoderAndEncoderOps.scala
  tools/bigquery-zos-mainframe-connector/gszutil/src/main/scala/com/google/cloud/gszutil/Decoding.scala
  tools/bigquery-zos-mainframe-connector/gszutil/src/main/scala/com/google/cloud/gszutil/Encoding.scala
  tools/bigquery-zos-mainframe-connector/gszutil/src/test/scala/com/google/cloud/bqsh/CopyBookSpec.scala
Labels: size/M

#905 Bmenasha/cai fix issue 900
  tools/asset-inventory/asset_inventory/bigquery_schema.py
  tools/asset-inventory/asset_inventory/import_pipeline.py
Labels: size/L

#965 [BigQuery Snowflake Table Migration Tool]
  README.md
  examples/bigquery-snowflake-tables-migration-utility/BQ_Table_Creator/BQ Table Creator.md
  examples/bigquery-snowflake-tables-migration-utility/BQ_Table_Creator/bq_table_creator.py
  examples/bigquery-snowflake-tables-migration-utility/DDL_Archiver/Archive DDL.md
  examples/bigquery-snowflake-tables-migration-utility/DDL_Archiver/archive_ddl.py
  examples/bigquery-snowflake-tables-migration-utility/DDL_Converter/Snowflake BQ Converter.md
  examples/bigquery-snowflake-tables-migration-utility/DDL_Converter/snowflake_bq_converter.py
  examples/bigquery-snowflake-tables-migration-utility/DDL_Extractor/Snowflake DDL Extraction.md
  examples/bigquery-snowflake-tables-migration-utility/DDL_Extractor/snowflake_ddl_extraction.py
  examples/bigquery-snowflake-tables-migration-utility/README.md
  examples/bigquery-snowflake-tables-migration-utility/config/metadata_columns.json
  examples/bigquery-snowflake-tables-migration-utility/config/object_name_mapping.json
  examples/bigquery-snowflake-tables-migration-utility/config/sf-ddl-extraction-config.json
  examples/bigquery-snowflake-tables-migration-utility/requirements.txt
  tools/gsnapshot/obj/Debug/netcoreapp5.0/gsnapshot.GeneratedMSBuildEditorConfig.editorconfig
Labels: size/XXL

#958 bqVisualizer | FIX | Read me | instructions | command to generate BQ Query Plan
  tools/bq-visualizer/README.md
Labels: size/XS

#942 Adding a shoutout to tools/k8s-2-gsm README.md
  tools/k8s-2-gsm/README.md
Labels: size/XS

#927 Fix minor typos
  tools/bq-visualizer/README.md
Labels: size/S

#967 Feature/cloudsql demo
  examples/data-ingestion-cloudsql-demo/.gitignore
  examples/data-ingestion-cloudsql-demo/README.md
  examples/data-ingestion-cloudsql-demo/terraform/cloudsql/main.tf
  examples/data-ingestion-cloudsql-demo/terraform/cloudsql/output.tf
  examples/data-ingestion-cloudsql-demo/terraform/cloudsql/variables.tf
Labels: size/L

#861 IaC Template for Spanner CDC Load to BigQuery for analytical use-cases
  README.md
  examples/spanner-changestreams-bigquery/README.md
  examples/spanner-changestreams-bigquery/backend.tf.sample
  examples/spanner-changestreams-bigquery/main.tf
  examples/spanner-changestreams-bigquery/provider.tf
  examples/spanner-changestreams-bigquery/spanner_cs_bq_dataflow/bigquery.tf
  examples/spanner-changestreams-bigquery/spanner_cs_bq_dataflow/dataflow.tf
  examples/spanner-changestreams-bigquery/spanner_cs_bq_dataflow/spanner.tf
  examples/spanner-changestreams-bigquery/spanner_cs_bq_dataflow/variables.tf
  examples/spanner-changestreams-bigquery/terraform.tf
  examples/spanner-changestreams-bigquery/terraform.tfvars.sample
  examples/spanner-changestreams-bigquery/variables.tf
Labels: size/L

#955 Add TSOP Object Transfer Log Processor
  README.md
  examples/tsop-log-processor/README.md
  examples/tsop-log-processor/main.py
  examples/tsop-log-processor/requirements.txt
Labels: size/M

#976 Update README.md for Cost Optimization dashboard
  examples/cost-optimization-dashboard/README.md
Labels: size/XS

#975 Add Capacity Planner CLI
  README.md
  tools/capacity-planner-cli/.gitignore
  tools/capacity-planner-cli/README.md
  tools/capacity-planner-cli/capacity_planner.py
  tools/capacity-planner-cli/logs/.gitignore
  tools/capacity-planner-cli/queries.toml
  tools/capacity-planner-cli/requirements.txt
  tools/capacity-planner-cli/test_requirements.txt
  tools/capacity-planner-cli/tests/__init__.py
  tools/capacity-planner-cli/tests/dump.json
  tools/capacity-planner-cli/tests/test_capacity_planner.py
  tools/capacity-planner-cli/tools/dump_query_result.py
Labels: size/XXL

#956 Example for generating metrics from STS notification
  README.md
  examples/sts-metrics/README.md
  examples/sts-metrics/pom.xml
  examples/sts-metrics/script/watch.sh
  examples/sts-metrics/src/main/java/com/google/cloud/pso/sts/EventHandler.java
  examples/sts-metrics/src/main/java/com/google/cloud/pso/sts/Metrics.java
  examples/sts-metrics/src/main/java/com/google/cloud/pso/sts/PubSubSubscriber.java
  examples/sts-metrics/src/main/java/com/google/cloud/pso/sts/RetryHttpInitializerWrapper.java
  examples/sts-metrics/src/main/java/com/google/cloud/pso/sts/StsJobGenerationWorker.java
  examples/sts-metrics/src/main/java/com/google/cloud/pso/sts/StsJobHelper.java
  examples/sts-metrics/src/main/java/com/google/cloud/pso/sts/StsJobNotificationHandler.java
  examples/sts-metrics/src/main/java/com/google/cloud/pso/sts/StsMetricsMain.java
  examples/sts-metrics/src/main/resources/config.properties
  examples/sts-metrics/src/main/resources/log4j2.xml
Labels: size/XXL

#978 adds ranger security rule assessment for BigQuery/BigLake IAM conversion
  README.md
  tools/ranger-to-bigquery-biglake-assessment/README.md
  tools/ranger-to-bigquery-biglake-assessment/comparison.html
  tools/ranger-to-bigquery-biglake-assessment/lookerstudio.png
  tools/ranger-to-bigquery-biglake-assessment/ranger_export.png
  tools/ranger-to-bigquery-biglake-assessment/terraform/main.tf
  tools/ranger-to-bigquery-biglake-assessment/terraform/ranger_schema.json
  tools/ranger-to-bigquery-biglake-assessment/terraform/terraform.tfvars
  tools/ranger-to-bigquery-biglake-assessment/terraform/variables.tf
Labels: size/XXL

#952 numeric-family-recommender-oracle
  README.md
  tools/numeric-family-recommender-oracle/Oracle_Number_Recommender_GCP.sql
  tools/numeric-family-recommender-oracle/Oracle_Number_Recommender_GCP_11g.sql
  tools/numeric-family-recommender-oracle/README.md
  tools/numeric-family-recommender-oracle/images/ora2pg-transform.jpeg
  tools/numeric-family-recommender-oracle/images/oracle-sample-ddl.jpg
  tools/numeric-family-recommender-oracle/images/spark-custom-schema.jpeg
  tools/numeric-family-recommender-oracle/images/sqldev.jpeg
  tools/numeric-family-recommender-oracle/images/sqlplus.jpeg
Labels: size/XXL
