Repository GoogleCloudPlatform/professional-services, pull requests merged in 2023-02, with the labels that each got.

#983 add_examples/carbon_footprint_dashboards
  README.md
  examples/carbon-footprint-dashboard/README.md
  examples/carbon-footprint-dashboard/images/demo_full_page.png
Labels: size/M

#981 Add Capacity Planner Sheets Extension
  README.md
  tools/capacity-planner-cli/queries.toml
  tools/capacity-planner-sheets-extension/README.md
  tools/capacity-planner-sheets-extension/capacity_planner_sheet.xlsx
  tools/capacity-planner-sheets-extension/images/capacity_planner_menu.png
  tools/capacity-planner-sheets-extension/images/capacity_planner_planning_sheet.png
  tools/capacity-planner-sheets-extension/images/error_details.png
  tools/capacity-planner-sheets-extension/main.js
  tools/capacity-planner-sheets-extension/queries.js
  tools/capacity-planner-sheets-extension/sheets.js
  tools/capacity-planner-sheets-extension/toml_to_queries_js.py
Labels: size/XL

#871 Removing role-binding code and documentation to separate out the tool…
  tools/custom-roles-analyzer/README.md
  tools/custom-roles-analyzer/src/main/java/com/google/cloud/pso/security/CustomRoleAnalyzer.java
  tools/custom-roles-analyzer/src/main/java/com/google/cloud/pso/security/asset/AssetServiceUtil.java
  tools/custom-roles-analyzer/src/main/java/com/google/cloud/pso/security/constants/GenericConstants.java
Labels: size/L

#854 Ccai insights export composer
  examples/ccai-insight-export-composer/Readme.md
  examples/ccai-insight-export-composer/dag/ccai_bq_export.py
  examples/ccai-insight-export-composer/images/airflow_ccai_config.jpg
  examples/ccai-insight-export-composer/images/connection-insights.jpg
  examples/ccai-insight-export-composer/images/export_dag.jpg
Labels: size/L

#985 add examples/cloud-composer-examples/airflow-metadata-export
  examples/cloud-composer-examples/airflow_metadata_export/README.md
  examples/cloud-composer-examples/airflow_metadata_export/__init__.py
  examples/cloud-composer-examples/airflow_metadata_export/export_dag_factory.py
Labels: size/L

#904 GCS bucket mover: modernize/update to py3
  tools/gcs-bucket-mover/build_requirements.sh
  tools/gcs-bucket-mover/gcs_bucket_mover/bucket_details.py
  tools/gcs-bucket-mover/gcs_bucket_mover/bucket_mover_service.py
  tools/gcs-bucket-mover/gcs_bucket_mover/bucket_mover_tester.py
  tools/gcs-bucket-mover/gcs_bucket_mover/cli.py
  tools/gcs-bucket-mover/gcs_bucket_mover/configuration.py
  tools/gcs-bucket-mover/gcs_bucket_mover/sts_job_status.py
  tools/gcs-bucket-mover/requirements.txt
  tools/gcs-bucket-mover/setup.py
Labels: size/XXL

#917 add examples/gcs-hive-external-table-file-optimization
  README.md
  examples/gcs-hive-external-table-file-optimization/README.md
  examples/gcs-hive-external-table-file-optimization/images/architecture.png
  examples/gcs-hive-external-table-file-optimization/images/comments.png
  examples/gcs-hive-external-table-file-optimization/images/comments_avro.png
  examples/gcs-hive-external-table-file-optimization/images/comments_avro_deflate.png
  examples/gcs-hive-external-table-file-optimization/images/comments_avro_snappy.png
  examples/gcs-hive-external-table-file-optimization/images/comments_json.png
  examples/gcs-hive-external-table-file-optimization/images/comments_json_gz.png
  examples/gcs-hive-external-table-file-optimization/images/comments_parquet.png
  examples/gcs-hive-external-table-file-optimization/images/comments_parquet_gzip.png
  examples/gcs-hive-external-table-file-optimization/images/comments_parquet_snappy.png
  examples/gcs-hive-external-table-file-optimization/scripts/setup.sh
  examples/gcs-hive-external-table-file-optimization/scripts/table-create.hql.template
Labels: size/XL

#925 add tools/dataproc-scheduled-cluster-sizing
  README.md
  tools/dataproc-scheduled-cluster-sizing/README.md
  tools/dataproc-scheduled-cluster-sizing/images/architecture.png
  tools/dataproc-scheduled-cluster-sizing/scripts/setup.sh
  tools/dataproc-scheduled-cluster-sizing/src/main.py
  tools/dataproc-scheduled-cluster-sizing/src/requirements.txt
  tools/dataproc-scheduled-cluster-sizing/terraform/input.template.tfvars
  tools/dataproc-scheduled-cluster-sizing/terraform/main.tf
  tools/dataproc-scheduled-cluster-sizing/terraform/modules/scheduled-cluster-sizing/main.tf
  tools/dataproc-scheduled-cluster-sizing/terraform/modules/scheduled-cluster-sizing/variables.tf
  tools/dataproc-scheduled-cluster-sizing/terraform/variables.tf
Labels: size/XL

#933 add examples/dataproc-job-optimization-guide
  README.md
  examples/dataproc-job-optimization-guide/README.md
  examples/dataproc-job-optimization-guide/images/monitoring-cpu.png
  examples/dataproc-job-optimization-guide/images/monitoring-hdfs.png
  examples/dataproc-job-optimization-guide/images/monitoring-job-progress.png
  examples/dataproc-job-optimization-guide/images/monitoring-jobs.png
  examples/dataproc-job-optimization-guide/images/monitoring-nodemanagers.png
  examples/dataproc-job-optimization-guide/images/monitoring-yarn-memory.png
  examples/dataproc-job-optimization-guide/scripts/setup.sh
  examples/dataproc-job-optimization-guide/scripts/spark_average_speed.py
  examples/dataproc-job-optimization-guide/templates/final-cluster-autoscaling-policy.yml
  examples/dataproc-job-optimization-guide/templates/final-cluster-wft.yml
  examples/dataproc-job-optimization-guide/templates/sizing-cluster-autoscaling-policy.yml
  examples/dataproc-job-optimization/README.md
  examples/dataproc-job-optimization/images/monitoring-cpu.png
  examples/dataproc-job-optimization/images/monitoring-hdfs.png
  examples/dataproc-job-optimization/images/monitoring-job-progress.png
  examples/dataproc-job-optimization/images/monitoring-jobs.png
  examples/dataproc-job-optimization/images/monitoring-nodemanagers.png
  examples/dataproc-job-optimization/images/monitoring-yarn-memory.png
  examples/dataproc-job-optimization/scripts/setup.sh
  examples/dataproc-job-optimization/scripts/spark_average_speed.py
  examples/dataproc-job-optimization/templates/final-cluster-autoscaling-policy.yml
  examples/dataproc-job-optimization/templates/final-cluster-wft.yml
  examples/dataproc-job-optimization/templates/sizing-cluster-autoscaling-policy.yml
Labels: size/XXL

#989 Fixing Bash Linter Errors
  examples/left-shift-validation-pre-commit-hook/setup.sh
Labels: size/M

#971 Ipam-autopilot | Fix routing domain update
  tools/ipam-autopilot/container/api.go
  tools/ipam-autopilot/container/data_access.go
Labels: size/S

#990 Update README to reflect Dataflow no public IP parameter (examples/dataflow-data-generator)
  examples/dataflow-data-generator/README.md
Labels: size/XS

#951 README formatting fixes
  README.md
  tools/bqman/README.md
Labels: size/L

#991 Delete examples/dataproc-job-optimization directory
  examples/dataproc-job-optimization/README.md
  examples/dataproc-job-optimization/images/monitoring-cpu.png
  examples/dataproc-job-optimization/images/monitoring-hdfs.png
  examples/dataproc-job-optimization/images/monitoring-job-progress.png
  examples/dataproc-job-optimization/images/monitoring-jobs.png
  examples/dataproc-job-optimization/images/monitoring-nodemanagers.png
  examples/dataproc-job-optimization/images/monitoring-yarn-memory.png
  examples/dataproc-job-optimization/scripts/setup.sh
  examples/dataproc-job-optimization/scripts/spark_average_speed.py
  examples/dataproc-job-optimization/templates/final-cluster-autoscaling-policy.yml
  examples/dataproc-job-optimization/templates/final-cluster-wft.yml
  examples/dataproc-job-optimization/templates/sizing-cluster-autoscaling-policy.yml
Labels: size/XL

#987 add examples/terragrunt-project-factory-gcp
  README.md
  examples/terragrunt-project-factory-gcp/.gitignore
  examples/terragrunt-project-factory-gcp/CODEOWNERS
  examples/terragrunt-project-factory-gcp/README.md
  examples/terragrunt-project-factory-gcp/data/team1/defaults.yaml.sample
  examples/terragrunt-project-factory-gcp/data/team1/projects/team1-project1.yaml.sample
  examples/terragrunt-project-factory-gcp/data/team1/terragrunt.hcl
  examples/terragrunt-project-factory-gcp/data/team2/defaults.yaml.sample
  examples/terragrunt-project-factory-gcp/data/team2/projects/team2-project1.yaml.sample
  examples/terragrunt-project-factory-gcp/data/team2/terragrunt.hcl
  examples/terragrunt-project-factory-gcp/docs/images/image2.png
  examples/terragrunt-project-factory-gcp/root.yaml.sample
  examples/terragrunt-project-factory-gcp/setup/defaults.yaml.tpl
  examples/terragrunt-project-factory-gcp/setup/main.tf
  examples/terragrunt-project-factory-gcp/setup/root.yaml.tpl
  examples/terragrunt-project-factory-gcp/setup/terraform.tfvars.sample
  examples/terragrunt-project-factory-gcp/setup/variables.tf
  examples/terragrunt-project-factory-gcp/src/README.md
  examples/terragrunt-project-factory-gcp/src/main.tf
  examples/terragrunt-project-factory-gcp/src/outputs.tf
  examples/terragrunt-project-factory-gcp/src/provider.tf
  examples/terragrunt-project-factory-gcp/src/variables.tf
  examples/terragrunt-project-factory-gcp/terragrunt.hcl
Labels: size/XL

#993 add examples/gitlab-kas-gke
  README.md
  examples/gitlab-kas-gke/.gitignore
  examples/gitlab-kas-gke/CODEOWNERS
  examples/gitlab-kas-gke/README.md
  examples/gitlab-kas-gke/docs/gitlab-kas-flow-diag.png
  examples/gitlab-kas-gke/docs/kas-agent-connection.png
  examples/gitlab-kas-gke/k8s_namespace.tf
  examples/gitlab-kas-gke/main.tf
  examples/gitlab-kas-gke/outputs.tf
  examples/gitlab-kas-gke/providers.tf
  examples/gitlab-kas-gke/templates/agent-config.yaml.tpl
  examples/gitlab-kas-gke/terraform-docs.md
  examples/gitlab-kas-gke/terraform.tfvars.sample
  examples/gitlab-kas-gke/variables.tf
  examples/gitlab-kas-gke/versions.tf
Labels: size/XL
