Repository GoogleCloudPlatform/professional-services, pull requests merged in 2024-12, with the labels that each got.

#1399 Python version bump and minor fixes
  examples/vertex_mlops_enterprise/.github/workflows/containers.yml.TEMPLATE
  examples/vertex_mlops_enterprise/.github/workflows/deploy.yml.TEMPLATE
  examples/vertex_mlops_enterprise/.github/workflows/main.yml.TEMPLATE
  examples/vertex_mlops_enterprise/.github/workflows/run.yml.TEMPLATE
  examples/vertex_mlops_enterprise/build/model-deployment-tfx.yaml.TEMPLATE
  examples/vertex_mlops_enterprise/build/pipeline-deployment-bqml.yaml.TEMPLATE
  examples/vertex_mlops_enterprise/build/pipeline-deployment-kfp.yaml.TEMPLATE
  examples/vertex_mlops_enterprise/build/pipeline-deployment-tfx.yaml.TEMPLATE
  examples/vertex_mlops_enterprise/build/pipeline-run.yaml.TEMPLATE
  examples/vertex_mlops_enterprise/build/pipeline-test.yaml.TEMPLATE
  examples/vertex_mlops_enterprise/doc/01-ENVIRONMENTS.md
  examples/vertex_mlops_enterprise/src/kfp_pipelines/Dockerfile
  examples/vertex_mlops_enterprise/terraform/00-shielded-folder/data/firewall-policies/cidrs.yaml
  examples/vertex_mlops_enterprise/terraform/00-shielded-folder/data/firewall-policies/hierarchical-policy-rules.yaml
  examples/vertex_mlops_enterprise/terraform/00-shielded-folder/data/org-policies/compute.yaml
  examples/vertex_mlops_enterprise/terraform/00-shielded-folder/data/org-policies/iam.yaml
  examples/vertex_mlops_enterprise/terraform/00-shielded-folder/data/org-policies/serverless.yaml
  examples/vertex_mlops_enterprise/terraform/00-shielded-folder/data/org-policies/sql.yaml
  examples/vertex_mlops_enterprise/terraform/00-shielded-folder/data/org-policies/storage.yaml
  examples/vertex_mlops_enterprise/terraform/00-shielded-folder/data/vpc-sc/accessible-services.yaml
  examples/vertex_mlops_enterprise/terraform/00-shielded-folder/data/vpc-sc/restricted-services.yaml
  examples/vertex_mlops_enterprise/terraform/00-shielded-folder/main.tf
  examples/vertex_mlops_enterprise/terraform/00-shielded-folder/providers.tf
  examples/vertex_mlops_enterprise/terraform/00-shielded-folder/terraform.tfvars
  examples/vertex_mlops_enterprise/terraform/00-shielded-folder/variables.tf
  examples/vertex_mlops_enterprise/terraform/01-dev/main.tf
  examples/vertex_mlops_enterprise/terraform/01-dev/outputs.tf
  examples/vertex_mlops_enterprise/terraform/02-staging/providers.tf
  examples/vertex_mlops_enterprise/terraform/03-prod/providers.tf
Labels: size/XL

#1398 Solution for Hybrid DLP & MongoDB
  README.md
  tools/mongodb-hybrid-dlp/README.md
  tools/mongodb-hybrid-dlp/cmd/dlpfunction/main.go
  tools/mongodb-hybrid-dlp/dlpfunction.go
  tools/mongodb-hybrid-dlp/go.mod
  tools/mongodb-hybrid-dlp/go.sum
  tools/mongodb-hybrid-dlp/main.tf
  tools/mongodb-hybrid-dlp/variables.tf
Labels: size/XXL

#1402 Added Werkzeug dependency to requirement.txt in risk-analysis-asset
  examples/risk-analysis-asset/backend/requirements.txt
Labels: size/XS

#1403 Add dlp-deid-pipeline example
  examples/dlp-deid-pipeline/DOC.md
  examples/dlp-deid-pipeline/README.md
  examples/dlp-deid-pipeline/config.yaml
  examples/dlp-deid-pipeline/diagrams/design_diagram_bq.png
  examples/dlp-deid-pipeline/diagrams/design_diagram_gcs.png
  examples/dlp-deid-pipeline/launcher.py
  examples/dlp-deid-pipeline/setup.py
  examples/dlp-deid-pipeline/src/__init__.py
  examples/dlp-deid-pipeline/src/bq/__init__.py
  examples/dlp-deid-pipeline/src/bq/helpers.py
  examples/dlp-deid-pipeline/src/bq/pipeline.py
  examples/dlp-deid-pipeline/src/common/__init__.py
  examples/dlp-deid-pipeline/src/common/utils.py
  examples/dlp-deid-pipeline/src/dlp/__init__.py
  examples/dlp-deid-pipeline/src/dlp/deidentify.py
  examples/dlp-deid-pipeline/src/dlp/templates/README.md
  examples/dlp-deid-pipeline/src/dlp/templates/deidentify/main.py
  examples/dlp-deid-pipeline/src/dlp/templates/deidentify/requirements.txt
  examples/dlp-deid-pipeline/src/dlp/templates/inspect/main.py
  examples/dlp-deid-pipeline/src/dlp/templates/inspect/requirements.txt
  examples/dlp-deid-pipeline/src/gcs/__init__.py
  examples/dlp-deid-pipeline/src/gcs/helpers.py
  examples/dlp-deid-pipeline/src/gcs/pipeline.py
  examples/dlp-deid-pipeline/src/pipeline.py
  examples/dlp-deid-pipeline/src/run.py
Labels: size/XXL

#1406 Fixed react state issues and automated Risk Theme creation in firestore
  examples/risk-analysis-asset/frontend/src/App.js
  examples/risk-analysis-asset/frontend/src/App.test.js
  examples/risk-analysis-asset/frontend/src/components/DeleteRisk.jsx
  examples/risk-analysis-asset/frontend/src/components/NewApplication.jsx
  examples/risk-analysis-asset/frontend/src/components/NewRisk.jsx
  examples/risk-analysis-asset/frontend/src/components/RiskCatalog.jsx
  examples/risk-analysis-asset/frontend/src/components/UserJourneys.jsx
  examples/risk-analysis-asset/frontend/src/index.js
  examples/risk-analysis-asset/infra/.terraform.lock.hcl
  examples/risk-analysis-asset/infra/dev.tfvars
  examples/risk-analysis-asset/infra/main.tf
  examples/risk-analysis-asset/infra/modules/firestore/main.tf
  examples/risk-analysis-asset/infra/modules/firestore/variables.tf
  examples/risk-analysis-asset/infra/variables.tf
Labels: size/XL

#1407 DynamoDB To Bigtable Migration Tool
  .gitignore
  README.md
  tools/dynamodb-bigtable-migration/.gitignore
  tools/dynamodb-bigtable-migration/README.md
  tools/dynamodb-bigtable-migration/dependency-reduced-pom.xml
  tools/dynamodb-bigtable-migration/docs/sample_bigtable_row.json
  tools/dynamodb-bigtable-migration/docs/sample_dynamodb_row.json
  tools/dynamodb-bigtable-migration/pom.xml
  tools/dynamodb-bigtable-migration/scripts/.env
  tools/dynamodb-bigtable-migration/scripts/env-sample
  tools/dynamodb-bigtable-migration/scripts/flextemplate-build.sh
  tools/dynamodb-bigtable-migration/scripts/flextemplate-metadata.json
  tools/dynamodb-bigtable-migration/scripts/flextemplate-run.sh
  tools/dynamodb-bigtable-migration/src/main/java/com/google/cloud/pso/migration/BaseOptions.java
  tools/dynamodb-bigtable-migration/src/main/java/com/google/cloud/pso/migration/DataLoadOptionsValidator.java
  tools/dynamodb-bigtable-migration/src/main/java/com/google/cloud/pso/migration/DataLoadPipeline.java
  tools/dynamodb-bigtable-migration/src/main/java/com/google/cloud/pso/migration/dofns/BeamRowToBigtableRowFn.java
  tools/dynamodb-bigtable-migration/src/main/java/com/google/cloud/pso/migration/dofns/package-info.java
  tools/dynamodb-bigtable-migration/src/main/java/com/google/cloud/pso/migration/model/InputFormat.java
  tools/dynamodb-bigtable-migration/src/main/java/com/google/cloud/pso/migration/model/package-info.java
  tools/dynamodb-bigtable-migration/src/main/java/com/google/cloud/pso/migration/transforms/ReadFromGCS.java
  tools/dynamodb-bigtable-migration/src/main/java/com/google/cloud/pso/migration/transforms/WriteToBigtable.java
  tools/dynamodb-bigtable-migration/src/main/java/com/google/cloud/pso/migration/transforms/package-info.java
  tools/dynamodb-bigtable-migration/src/main/java/com/google/cloud/pso/migration/utils/BeamRowUtils.java
  tools/dynamodb-bigtable-migration/src/main/java/com/google/cloud/pso/migration/utils/DataLoadConstants.java
  tools/dynamodb-bigtable-migration/src/main/java/com/google/cloud/pso/migration/utils/DynamoRowUtils.java
  tools/dynamodb-bigtable-migration/src/main/resources/logback.xml
  tools/dynamodb-bigtable-migration/src/test/java/com/google/cloud/pso/migration/DataLoadPipelineTest.java
  tools/dynamodb-bigtable-migration/src/test/java/com/google/cloud/pso/migration/dofns/BeamRowToBigtableRowFnTest.java
  tools/dynamodb-bigtable-migration/src/test/java/com/google/cloud/pso/migration/utils/BeamRowUtilsTest.java
  tools/dynamodb-bigtable-migration/src/test/resources/sample-dynamodb-export.json.gz
Labels: size/XXL

#1410 Update the ReadMe link
  tools/dynamodb-bigtable-migration/README.md
Labels: size/S

#1411 Remove the hidden file that has project details.
  tools/dynamodb-bigtable-migration/scripts/.env
Labels: size/S

#1412 Fix typo in Snowflake GCS URL prefix
  tools/snowflake2bq/README.md
Labels: size/XS
