Repository GoogleCloudPlatform/professional-services, pull requests merged in 2024-10, with the labels that each got.

#1355 CDS View Generator for SAP Tables Replication to BigQuery via Datasphere
  examples/sap-bigquery-cds-generator/ABAP Utility_ Automated Mass CDS View Generation for Cortex Data Foundation.pdf
  examples/sap-bigquery-cds-generator/ABAP_Utility_Input_Inventory_Tables_to_CDSviews.txt
  examples/sap-bigquery-cds-generator/K900045.S4S
  examples/sap-bigquery-cds-generator/R900045.S4S
  examples/sap-bigquery-cds-generator/README.md
Labels: size/L

#1361 gcpviz: Fixed Dockerfile building and add helpful message.
  tools/gcpviz/Dockerfile
  tools/gcpviz/gcpviz.sh
Labels: size/S

#1365 Fixing the AND bug in SLO definition converter tool
  tools/slo-definition-converter/slo-backend/src/main/java/com/tools/slo/slotools/utility/TextUtility.java
  tools/slo-definition-converter/slo-frontend/package.json
  tools/slo-definition-converter/slo-frontend/src/index.tsx
Labels: size/S

#1369 Adding Reliability Risk Analysis Asset [expmaples/risk-analysis-asset]
  README.md
  examples/risk-analysis-asset/README.md
  examples/risk-analysis-asset/backend/.env
  examples/risk-analysis-asset/backend/Dockerfile
  examples/risk-analysis-asset/backend/README.md
  examples/risk-analysis-asset/backend/app.py
  examples/risk-analysis-asset/backend/config.json
  examples/risk-analysis-asset/backend/requirements.txt
  examples/risk-analysis-asset/backend/test_app.py
  examples/risk-analysis-asset/cloudbuild.yaml
  examples/risk-analysis-asset/docker-compose.yml
  examples/risk-analysis-asset/frontend/.env
  examples/risk-analysis-asset/frontend/.eslintrc.js
  examples/risk-analysis-asset/frontend/Dockerfile
  examples/risk-analysis-asset/frontend/package-lock.json
  examples/risk-analysis-asset/frontend/package.json
  examples/risk-analysis-asset/frontend/public/favicon.ico
  examples/risk-analysis-asset/frontend/public/index.html
  examples/risk-analysis-asset/frontend/public/logo192.png
  examples/risk-analysis-asset/frontend/public/logo512.png
  examples/risk-analysis-asset/frontend/public/manifest.json
  examples/risk-analysis-asset/frontend/public/robots.txt
  examples/risk-analysis-asset/frontend/src/App.css
  examples/risk-analysis-asset/frontend/src/App.js
  examples/risk-analysis-asset/frontend/src/App.test.js
  examples/risk-analysis-asset/frontend/src/components/DeleteRisk.jsx
  examples/risk-analysis-asset/frontend/src/components/NewApplication.jsx
  examples/risk-analysis-asset/frontend/src/components/NewRisk.jsx
  examples/risk-analysis-asset/frontend/src/components/RiskCatalog.jsx
  examples/risk-analysis-asset/frontend/src/components/UserJourneys.jsx
  examples/risk-analysis-asset/frontend/src/index.css
  examples/risk-analysis-asset/frontend/src/index.js
  examples/risk-analysis-asset/frontend/src/logo.svg
  examples/risk-analysis-asset/frontend/src/reportWebVitals.js
  examples/risk-analysis-asset/frontend/src/setupTests.js
  examples/risk-analysis-asset/frontend/src/style.css
  examples/risk-analysis-asset/frontend/src/tokenHandler.js
  examples/risk-analysis-asset/infra/.terraform.lock.hcl
  examples/risk-analysis-asset/infra/dev.tfvars
  examples/risk-analysis-asset/infra/main.tf
  examples/risk-analysis-asset/infra/modules/cloud_run/main.tf
  examples/risk-analysis-asset/infra/modules/cloud_run/variables.tf
  examples/risk-analysis-asset/infra/modules/firestore/main.tf
  examples/risk-analysis-asset/infra/modules/firestore/variables.tf
  examples/risk-analysis-asset/infra/variables.tf
Labels: size/XXL

#1381 Create Composer Stress Testing tool
  tools/cloud-composer-stress-testing/README.md
  tools/cloud-composer-stress-testing/cloud-composer-dag-generator/README.md
  tools/cloud-composer-stress-testing/cloud-composer-dag-generator/config.json
  tools/cloud-composer-stress-testing/cloud-composer-dag-generator/dag_generator/__init__.py
  tools/cloud-composer-stress-testing/cloud-composer-dag-generator/dag_generator/__main__.py
  tools/cloud-composer-stress-testing/cloud-composer-dag-generator/dag_generator/modules/__init__.py
  tools/cloud-composer-stress-testing/cloud-composer-dag-generator/dag_generator/modules/initDag.py
  tools/cloud-composer-stress-testing/cloud-composer-dag-generator/dag_generator/modules/operators.py
  tools/cloud-composer-stress-testing/cloud-composer-dag-generator/out/.gitkeep
  tools/cloud-composer-stress-testing/cloud-composer-dag-generator/pause_dags.sh
  tools/cloud-composer-stress-testing/cloud-composer-dag-generator/run_dags.sh
  tools/cloud-composer-stress-testing/cloud-composer-workload-simulator/.gitignore
  tools/cloud-composer-stress-testing/cloud-composer-workload-simulator/README.md
  tools/cloud-composer-stress-testing/cloud-composer-workload-simulator/configs/custom.yaml
  tools/cloud-composer-stress-testing/cloud-composer-workload-simulator/configs/sample.yaml
  tools/cloud-composer-stress-testing/cloud-composer-workload-simulator/main.py
  tools/cloud-composer-stress-testing/cloud-composer-workload-simulator/requirements.txt
  tools/cloud-composer-stress-testing/cloud-composer-workload-simulator/taskflow_collections/__init__.py
  tools/cloud-composer-stress-testing/cloud-composer-workload-simulator/taskflow_collections/base_taskflows.py
  tools/cloud-composer-stress-testing/cloud-composer-workload-simulator/taskflow_collections/custom_taskflows.py
  tools/cloud-composer-stress-testing/cloud-composer-workload-simulator/taskflow_collections/google_cloud_taskflows.py
Labels: size/XXL

#1386 Add Cloud Composer Environment Rotator
  README.md
  tools/cloud-composer-environment-rotator/README.md
  tools/cloud-composer-environment-rotator/composer-2-small_us-central1_inventory
  tools/cloud-composer-environment-rotator/dags/pause_all_dags.py
  tools/cloud-composer-environment-rotator/rotate-composer.sh
Labels: size/L
