Repository GoogleCloudPlatform/professional-services, pull requests merged in 2024-03, with the labels that each got.

#1221 added terraform module for provisioning TCPX infrastructure
  examples/gpudirect-tcpx/README.md
  examples/gpudirect-tcpx/data_plane.tf
  examples/gpudirect-tcpx/management_network.tf
  examples/gpudirect-tcpx/outputs.tf
  examples/gpudirect-tcpx/variables.tf
Labels: size/L

#1217 tool: added tool ml-project-generator
  README.md
  tools/ml-project-generator/README.md
  tools/ml-project-generator/cookiecutter.json
  tools/ml-project-generator/{{ cookiecutter.repo_name }}/.gitignore
  tools/ml-project-generator/{{ cookiecutter.repo_name }}/.pre-commit-config.yaml
  tools/ml-project-generator/{{ cookiecutter.repo_name }}/Dockerfile
  tools/ml-project-generator/{{ cookiecutter.repo_name }}/LICENSE
  tools/ml-project-generator/{{ cookiecutter.repo_name }}/README.md
  tools/ml-project-generator/{{ cookiecutter.repo_name }}/config/base.yaml
  tools/ml-project-generator/{{ cookiecutter.repo_name }}/config/predict.yaml
  tools/ml-project-generator/{{ cookiecutter.repo_name }}/config/train.yaml
  tools/ml-project-generator/{{ cookiecutter.repo_name }}/data/sample.csv
  tools/ml-project-generator/{{ cookiecutter.repo_name }}/logging.conf
  tools/ml-project-generator/{{ cookiecutter.repo_name }}/notebooks/init.ipynb
  tools/ml-project-generator/{{ cookiecutter.repo_name }}/pyproject.toml
  tools/ml-project-generator/{{ cookiecutter.repo_name }}/requirements.txt
  tools/ml-project-generator/{{ cookiecutter.repo_name }}/setup.py
  tools/ml-project-generator/{{ cookiecutter.repo_name }}/{{ cookiecutter.repo_name }}/__init__.py
  tools/ml-project-generator/{{ cookiecutter.repo_name }}/{{ cookiecutter.repo_name }}/components/__init__.py
  tools/ml-project-generator/{{ cookiecutter.repo_name }}/{{ cookiecutter.repo_name }}/components/features.py
  tools/ml-project-generator/{{ cookiecutter.repo_name }}/{{ cookiecutter.repo_name }}/components/predict.py
  tools/ml-project-generator/{{ cookiecutter.repo_name }}/{{ cookiecutter.repo_name }}/components/train.py
  tools/ml-project-generator/{{ cookiecutter.repo_name }}/{{ cookiecutter.repo_name }}/components/utils.py
  tools/ml-project-generator/{{ cookiecutter.repo_name }}/{{ cookiecutter.repo_name }}/config.py
  tools/ml-project-generator/{{ cookiecutter.repo_name }}/{{ cookiecutter.repo_name }}/main.py
  tools/ml-project-generator/{{ cookiecutter.repo_name }}/{{ cookiecutter.repo_name }}/pipelines/__init__.py
  tools/ml-project-generator/{{ cookiecutter.repo_name }}/{{ cookiecutter.repo_name }}/pipelines/predict.py
  tools/ml-project-generator/{{ cookiecutter.repo_name }}/{{ cookiecutter.repo_name }}/pipelines/train.py
  tools/ml-project-generator/{{ cookiecutter.repo_name }}/{{ cookiecutter.repo_name }}_tests/model/test_baseline.py
Labels: size/XL

#1222 Update README.md - fix typo
  README.md
Labels: size/XS

#1223 Additional tests for Composer DAG Integrity tooling
  tools/cloud-composer-dag-validation/dag_validation.py
  tools/cloud-composer-dag-validation/dags/test_failure_dag.py
  tools/cloud-composer-dag-validation/dags/test_success_dag.py
Labels: size/L
