Repository GoogleCloudPlatform/professional-services, pull requests merged in 2024-05, with the labels that each got.

#1273 Update README.md
  tools/bigquery-zos-mainframe-connector/README.md
Labels: size/L

#1272 added a new tool called "llm_based_sql_translation_validator"
  tools/llm_based_sql_translation_validator/README.md
  tools/llm_based_sql_translation_validator/call_llm.sql
  tools/llm_based_sql_translation_validator/run_sql_validator.sql
Labels: size/L

#1287 Print the message of PermissionDenied exception
  examples/billboard/billboard.py
Labels: size/XS

#1288 Triton Inference Server and Google JetStream integration tool for Cloud TPU inferencing
  tools/tpu-triton-jetstream/README.md
  tools/tpu-triton-jetstream/docker/Dockerfile
  tools/tpu-triton-jetstream/locust/load_test.py
  tools/tpu-triton-jetstream/samples/model_repository/llama7b/1/model.json
  tools/tpu-triton-jetstream/samples/model_repository/llama7b/config.pbtxt
  tools/tpu-triton-jetstream/src/model.json
  tools/tpu-triton-jetstream/src/model.py
Labels: size/XXL

#1289 Delete mainframe connector
  tools/bigquery-zos-mainframe-connector/USING_WITH_BQ.md
  tools/bigquery-zos-mainframe-connector/USING_WITH_GCS.md
  tools/bigquery-zos-mainframe-connector/gszutil/.gitignore
  tools/bigquery-zos-mainframe-connector/gszutil/README.md
  tools/bigquery-zos-mainframe-connector/gszutil/img/bq_export_rpc_call.png
  tools/bigquery-zos-mainframe-connector/gszutil/img/bqsh_high_level_sequence_diagram.png
Labels: size/XL
