Repository GoogleCloudPlatform/professional-services, pull requests merged in 2024-04, with the labels that each got.

#1243 gcpviz: added export mode for database
  tools/gcpviz/README.md
  tools/gcpviz/cmd/gcpviz/main.go
  tools/gcpviz/main.go
Labels: size/L

#1247 Add Airflow DAG AI Documentation Generator
  README.md
  tools/airflow-dag-ai-documenter/README.md
  tools/airflow-dag-ai-documenter/images/sample.png
  tools/airflow-dag-ai-documenter/run.sh
  tools/airflow-dag-ai-documenter/scripts/generate_docs.py
Labels: size/L

#1248 Update README.md
  tools/airflow-dag-ai-documenter/README.md
Labels: size/XS

#1249 naming convention
  tools/airflow-dag-ai-documenter/run.sh
Labels: size/XS

#1251 Add support for tags, description in metadata generation
  README.md
  tools/airflow-dag-ai-documenter/README.md
  tools/airflow-dag-ai-documenter/images/sample.png
  tools/airflow-dag-ai-documenter/scripts/generate_docs.py
  tools/airflow-dag-metadata-generator/README.md
  tools/airflow-dag-metadata-generator/images/sample-description.png
  tools/airflow-dag-metadata-generator/images/sample-docs.png
  tools/airflow-dag-metadata-generator/images/sample-tags.png
  tools/airflow-dag-metadata-generator/run.sh
  tools/airflow-dag-metadata-generator/scripts/generate_dag_metadata.py
Labels: size/L

#1252 Update README.md
  README.md
Labels: size/XS

#1232 New Python Boilerplate code added for Data Catalog Tagging using Tag Templates
  tools/datacatalog-tagging-using-tag-templates/README.md
  tools/datacatalog-tagging-using-tag-templates/configs/ddl.sql
  tools/datacatalog-tagging-using-tag-templates/configs/sampleJSON.json
  tools/datacatalog-tagging-using-tag-templates/images/figure1.png
  tools/datacatalog-tagging-using-tag-templates/images/figure2.png
  tools/datacatalog-tagging-using-tag-templates/tagging/attach_delete_tag_to_table_column.py
  tools/datacatalog-tagging-using-tag-templates/tagging/insert_landing.py
  tools/datacatalog-tagging-using-tag-templates/tagging/tag_util.py
  tools/datacatalog-tagging-using-tag-templates/tagging/upsert_staging.py
Labels: size/XXL

#1242 Add cloud-dns-load-balancing example
  .gitignore
  README.md
  examples/cloud-dns-load-balancing/.gitignore
  examples/cloud-dns-load-balancing/README.md
  examples/cloud-dns-load-balancing/certificate.tf
  examples/cloud-dns-load-balancing/cr.tf
  examples/cloud-dns-load-balancing/dns-l4-rilb-mig.tf
  examples/cloud-dns-load-balancing/dns-l7-crilb-cr.tf
  examples/cloud-dns-load-balancing/dns-l7-crilb-mig.tf
  examples/cloud-dns-load-balancing/dns-l7-gxlb-cr.tf
  examples/cloud-dns-load-balancing/dns-l7-rilb-cr.tf
  examples/cloud-dns-load-balancing/dns-l7-rilb-mig.tf
  examples/cloud-dns-load-balancing/dns.tf
  examples/cloud-dns-load-balancing/images/l4-rilb-mig.png
  examples/cloud-dns-load-balancing/images/l7-gxlb-cr.png
  examples/cloud-dns-load-balancing/images/l7-rilb-cr.png
  examples/cloud-dns-load-balancing/images/l7-rilb-mig.png
  examples/cloud-dns-load-balancing/l4-rilb-mig.tf
  examples/cloud-dns-load-balancing/l7-crilb-cr.tf
  examples/cloud-dns-load-balancing/l7-crilb-mig.tf
  examples/cloud-dns-load-balancing/l7-gxlb-cr.tf
  examples/cloud-dns-load-balancing/l7-rilb-cr.tf
  examples/cloud-dns-load-balancing/l7-rilb-mig.tf
  examples/cloud-dns-load-balancing/locals.tf
  examples/cloud-dns-load-balancing/mig.tf
  examples/cloud-dns-load-balancing/modules/certificate/certificate.tf
  examples/cloud-dns-load-balancing/modules/certificate/output.tf
  examples/cloud-dns-load-balancing/modules/certificate/variables.tf
  examples/cloud-dns-load-balancing/modules/cr/cr1.tf
  examples/cloud-dns-load-balancing/modules/cr/cr2.tf
  examples/cloud-dns-load-balancing/modules/cr/output.tf
  examples/cloud-dns-load-balancing/modules/cr/variables.tf
  examples/cloud-dns-load-balancing/modules/l4rilb/l4-rilb.tf
  examples/cloud-dns-load-balancing/modules/l4rilb/output.tf
  examples/cloud-dns-load-balancing/modules/l4rilb/variables.tf
  examples/cloud-dns-load-balancing/modules/l7crilb/l7-crilb.tf
  examples/cloud-dns-load-balancing/modules/l7crilb/output.tf
  examples/cloud-dns-load-balancing/modules/l7crilb/variables.tf
  examples/cloud-dns-load-balancing/modules/l7rilb/l7-rilb.tf
  examples/cloud-dns-load-balancing/modules/l7rilb/output.tf
  examples/cloud-dns-load-balancing/modules/l7rilb/variables.tf
  examples/cloud-dns-load-balancing/modules/mig/mig.tf
  examples/cloud-dns-load-balancing/modules/mig/output.tf
  examples/cloud-dns-load-balancing/modules/mig/variables.tf
  examples/cloud-dns-load-balancing/network.tf
  examples/cloud-dns-load-balancing/outputs.tf
  examples/cloud-dns-load-balancing/providers.tf
  examples/cloud-dns-load-balancing/terraform.tfvars.sample
  examples/cloud-dns-load-balancing/variables.tf
Labels: size/XXL
