Repository GoogleCloudPlatform/professional-services, pull requests merged in 2025-04, with the labels that each got.

#1462 Add Vertex AI Vector Search Load Testing Framework
  README.md
  helpers/exclusion_list.txt
  tools/vector-search-load-testing-framework/Dockerfile
  tools/vector-search-load-testing-framework/README.md
  tools/vector-search-load-testing-framework/config.template.sh
  tools/vector-search-load-testing-framework/deploy_vvs_load_testing_framework.sh
  tools/vector-search-load-testing-framework/destroy.sh
  tools/vector-search-load-testing-framework/locust_tests/locust.py
  tools/vector-search-load-testing-framework/terraform/README.md
  tools/vector-search-load-testing-framework/terraform/main.tf
  tools/vector-search-load-testing-framework/terraform/modules/gke-autopilot/README.md
  tools/vector-search-load-testing-framework/terraform/modules/gke-autopilot/app.tf
  tools/vector-search-load-testing-framework/terraform/modules/gke-autopilot/cluster.tf
  tools/vector-search-load-testing-framework/terraform/modules/gke-autopilot/outputs.tf
  tools/vector-search-load-testing-framework/terraform/modules/gke-autopilot/variables.tf
  tools/vector-search-load-testing-framework/terraform/modules/vertex-ai-vector-search/README.md
  tools/vector-search-load-testing-framework/terraform/modules/vertex-ai-vector-search/main.tf
  tools/vector-search-load-testing-framework/terraform/modules/vertex-ai-vector-search/network.tf
  tools/vector-search-load-testing-framework/terraform/modules/vertex-ai-vector-search/outputs.tf
  tools/vector-search-load-testing-framework/terraform/modules/vertex-ai-vector-search/variables.tf
  tools/vector-search-load-testing-framework/terraform/outputs.tf
  tools/vector-search-load-testing-framework/terraform/variables.tf
  tools/vector-search-load-testing-framework/utils/setup_vector_search_psc_network.sh
Labels: size/XXL

#1478 Sample code for agentspace with wif and dwd
  examples/cloud-agentspace-wif-dwd/README.md
  examples/cloud-agentspace-wif-dwd/pom.xml
  examples/cloud-agentspace-wif-dwd/src/main/java/com/google/cloud/pso/OauthApplication.java
  examples/cloud-agentspace-wif-dwd/src/test/java/com/google/cloud/pso/OauthApplicationTest.java
Labels: size/XL

#1483 Format Fix for Agentspace Example
  examples/cloud-agentspace-wif-dwd/src/main/java/com/google/cloud/pso/OauthApplication.java
  examples/cloud-agentspace-wif-dwd/src/test/java/com/google/cloud/pso/OauthApplicationTest.java
  helpers/exclusion_list.txt
Labels: size/L

#1480 latest composer-workload-simulator, and ruff formatting
  tools/cloud-composer-stress-testing/cloud-composer-dag-generator/dag_generator/__main__.py
  tools/cloud-composer-stress-testing/cloud-composer-dag-generator/dag_generator/modules/initDag.py
  tools/cloud-composer-stress-testing/cloud-composer-workload-simulator/.gitignore
  tools/cloud-composer-stress-testing/cloud-composer-workload-simulator/README.md
  tools/cloud-composer-stress-testing/cloud-composer-workload-simulator/configs/custom.yaml
  tools/cloud-composer-stress-testing/cloud-composer-workload-simulator/configs/sample.yaml
  tools/cloud-composer-stress-testing/cloud-composer-workload-simulator/dags/sample/dag_0.py
  tools/cloud-composer-stress-testing/cloud-composer-workload-simulator/local_utils/__init__.py
  tools/cloud-composer-stress-testing/cloud-composer-workload-simulator/local_utils/helper_functions.py
  tools/cloud-composer-stress-testing/cloud-composer-workload-simulator/main.py
  tools/cloud-composer-stress-testing/cloud-composer-workload-simulator/requirements.txt
  tools/cloud-composer-stress-testing/cloud-composer-workload-simulator/taskflow_collections/base_taskflows.py
  tools/cloud-composer-stress-testing/cloud-composer-workload-simulator/taskflow_collections/custom_taskflows.py
  tools/cloud-composer-stress-testing/cloud-composer-workload-simulator/taskflow_collections/google_cloud_taskflows.py
Labels: size/XL

#1489 add gpudirect-webhook
  tools/gpudirect-webhook/Cargo.lock
  tools/gpudirect-webhook/Cargo.toml
  tools/gpudirect-webhook/Dockerfile
  tools/gpudirect-webhook/README.md
  tools/gpudirect-webhook/k8s.yaml
  tools/gpudirect-webhook/src/cluster.rs
  tools/gpudirect-webhook/src/config.rs
  tools/gpudirect-webhook/src/constants.rs
  tools/gpudirect-webhook/src/errors.rs
  tools/gpudirect-webhook/src/gcp_auth.rs
  tools/gpudirect-webhook/src/main.rs
  tools/gpudirect-webhook/src/networks.rs
  tools/gpudirect-webhook/src/utils.rs
  tools/gpudirect-webhook/src/webhook.rs
  tools/gpudirect-webhook/test_tcpx.yaml
  tools/gpudirect-webhook/test_tcpxo.yaml
Labels: size/XXL

#1495 correct contributing and license links in readme
  tools/gpudirect-webhook/README.md
Labels: size/XS
