Repository GoogleCloudPlatform/professional-services, pull requests merged in 2025-01, with the labels that each got.

#1417 Add example of React SPA app with Python backend
  README.md
  examples/react-spa-app/README.md
  examples/react-spa-app/backend/main.py
  examples/react-spa-app/backend/requirements.txt
  examples/react-spa-app/cloud-armor.tf
  examples/react-spa-app/dns.tf
  examples/react-spa-app/global-lb.tf
  examples/react-spa-app/iap.tf
  examples/react-spa-app/main.tf
  examples/react-spa-app/my-app/.gitignore
  examples/react-spa-app/my-app/package-lock.json
  examples/react-spa-app/my-app/package.json
  examples/react-spa-app/my-app/public/404.html
  examples/react-spa-app/my-app/public/favicon.ico
  examples/react-spa-app/my-app/public/index.html
  examples/react-spa-app/my-app/public/logo192.png
  examples/react-spa-app/my-app/public/logo512.png
  examples/react-spa-app/my-app/public/manifest.json
  examples/react-spa-app/my-app/public/robots.txt
  examples/react-spa-app/my-app/src/App.css
  examples/react-spa-app/my-app/src/App.js
  examples/react-spa-app/my-app/src/index.css
  examples/react-spa-app/my-app/src/index.js
  examples/react-spa-app/my-app/src/logo.svg
  examples/react-spa-app/my-app/webpack.config.js
  examples/react-spa-app/outputs.tf
  examples/react-spa-app/regional-lb.tf
  examples/react-spa-app/variables.tf
Labels: size/XXL

#1415 Migrate Kafka to GMK using MM2
  README.md
  examples/mm2-gmk-migration/README.md
  examples/mm2-gmk-migration/deploy.sh
  examples/mm2-gmk-migration/producer.py
  examples/mm2-gmk-migration/static/Kafka Migration using MM2.png
  examples/mm2-gmk-migration/terraform/modules/environments/production/backends.tf
  examples/mm2-gmk-migration/terraform/modules/environments/production/deploy_kafka.tf
  examples/mm2-gmk-migration/terraform/modules/environments/production/deploy_mm2-standalone.tf
  examples/mm2-gmk-migration/terraform/modules/environments/production/deploy_producer.tf
  examples/mm2-gmk-migration/terraform/modules/google-managed-kafka/locals.tf
  examples/mm2-gmk-migration/terraform/modules/google-managed-kafka/managed-kafka.tf
  examples/mm2-gmk-migration/terraform/modules/google-managed-kafka/outputs.tf
  examples/mm2-gmk-migration/terraform/modules/google-managed-kafka/terraform-setup.tf
  examples/mm2-gmk-migration/terraform/modules/google-managed-kafka/variables.tf
  examples/mm2-gmk-migration/terraform/modules/kafka-producer/compute-engine.tf
  examples/mm2-gmk-migration/terraform/modules/kafka-producer/outputs.tf
  examples/mm2-gmk-migration/terraform/modules/kafka-producer/variables.tf
  examples/mm2-gmk-migration/terraform/modules/mirror-maker2-standalone/mm2standalone.tf
  examples/mm2-gmk-migration/terraform/modules/mirror-maker2-standalone/variables.tf
Labels: size/XXL

#1426 [mm2] Update README.md
  examples/mm2-gmk-migration/README.md
Labels: size/XS

#1427 Kafka readme update
  examples/mm2-gmk-migration/README.md
Labels: size/XS

#1430 Delete examples/dataflow-bigquery-transpose directory
  examples/dataflow-bigquery-transpose/.gitignore
  examples/dataflow-bigquery-transpose/README.md
  examples/dataflow-bigquery-transpose/img/example_pivoted_table.png
  examples/dataflow-bigquery-transpose/img/example_raw_table.png
  examples/dataflow-bigquery-transpose/img/pipeline_graph.png
  examples/dataflow-bigquery-transpose/img/simple_sql_based_pivot.png
  examples/dataflow-bigquery-transpose/pom.xml
  examples/dataflow-bigquery-transpose/src/license/license-header-style.xml
  examples/dataflow-bigquery-transpose/src/license/license-header.txt
  examples/dataflow-bigquery-transpose/src/main/java/com/google/cloud/pso/common/PivotInputProvider.java
  examples/dataflow-bigquery-transpose/src/main/java/com/google/cloud/pso/common/PivotUtils.java
  examples/dataflow-bigquery-transpose/src/main/java/com/google/cloud/pso/pipeline/Pivot.java
  examples/dataflow-bigquery-transpose/src/main/java/com/google/cloud/pso/transforms/PivotSchemaExtract.java
  examples/dataflow-bigquery-transpose/src/main/java/com/google/cloud/pso/transforms/TableRowPivot.java
  examples/dataflow-bigquery-transpose/src/main/resources/spotbugs-exclude.xml
  examples/dataflow-bigquery-transpose/src/test/java/com/google/cloud/pso/common/PivotInputProviderTest.java
  examples/dataflow-bigquery-transpose/src/test/java/com/google/cloud/pso/common/PivotUtilsTest.java
  examples/dataflow-bigquery-transpose/src/test/java/com/google/cloud/pso/pipeline/PivotTest.java
  examples/dataflow-bigquery-transpose/src/test/java/com/google/cloud/pso/transforms/PivotSchemaExtractTest.java
  examples/dataflow-bigquery-transpose/src/test/java/com/google/cloud/pso/transforms/TableRowPivotTest.java
Labels: size/XXL

#1437 Cds generator version2
  examples/sap-bigquery-cds-generator/K900071.S4S
  examples/sap-bigquery-cds-generator/R900071.S4S
  examples/sap-bigquery-cds-generator/README.md
  examples/sap-bigquery-cds-generator/RELEASE_NOTES.MD
Labels: size/M

#1438 Documentation changes for cds view generator
  examples/sap-bigquery-cds-generator/ABAP_Utility_Input_Inventory_Tables_to_CDSviews.txt
  examples/sap-bigquery-cds-generator/README.md
  examples/sap-bigquery-cds-generator/sample_input_file.txt
Labels: size/M
