Repository GoogleCloudPlatform/professional-services, pull requests merged in 2025-06, with the labels that each got.

#1516 IAM Deny & Org Policies - Next 2025
  README.md
  examples/iam-deny/.gitignore
  examples/iam-deny/README.md
  examples/iam-deny/terraform/denied_perms.tf
  examples/iam-deny/terraform/main.tf
  examples/iam-deny/terraform/profiles/billing.json
  examples/iam-deny/terraform/profiles/networking.json
  examples/iam-deny/terraform/profiles/securitycenter.json
  examples/iam-deny/terraform/provider.tf
  examples/iam-deny/terraform/terraform.tfvars.example
  examples/iam-deny/terraform/tfplan.out
  examples/iam-deny/terraform/variables.tf
Labels: size/XL

#1522 GenAI Agent for Hotel's Booking (MCP Toolbox, Claude, Slack integration)
  README.md
  examples/mcptoolbox-bq-claude-slack-agent/Dockerfile
  examples/mcptoolbox-bq-claude-slack-agent/README.md
  examples/mcptoolbox-bq-claude-slack-agent/cleanup.sh
  examples/mcptoolbox-bq-claude-slack-agent/cloudbuild.yaml
  examples/mcptoolbox-bq-claude-slack-agent/deploy.sh
  examples/mcptoolbox-bq-claude-slack-agent/images/bq1.png
  examples/mcptoolbox-bq-claude-slack-agent/images/bq2.png
  examples/mcptoolbox-bq-claude-slack-agent/images/chat1.png
  examples/mcptoolbox-bq-claude-slack-agent/infra/README.md
  examples/mcptoolbox-bq-claude-slack-agent/infra/bigquery.tf
  examples/mcptoolbox-bq-claude-slack-agent/infra/bigquery/data.csv
  examples/mcptoolbox-bq-claude-slack-agent/infra/cloudbuild.tf
  examples/mcptoolbox-bq-claude-slack-agent/infra/main.tf
  examples/mcptoolbox-bq-claude-slack-agent/infra/mcptoolbox.tf
  examples/mcptoolbox-bq-claude-slack-agent/infra/mcptoolbox/tools.yaml.tpl
  examples/mcptoolbox-bq-claude-slack-agent/infra/outputs.tf
  examples/mcptoolbox-bq-claude-slack-agent/infra/slackapp_service.tf
  examples/mcptoolbox-bq-claude-slack-agent/infra/terraform.tfvars.example
  examples/mcptoolbox-bq-claude-slack-agent/infra/variables.tf
  examples/mcptoolbox-bq-claude-slack-agent/license-header
  examples/mcptoolbox-bq-claude-slack-agent/pom.xml
  examples/mcptoolbox-bq-claude-slack-agent/src/main/java/org/example/gcp/slack/claude/SlackListenerApp.java
  examples/mcptoolbox-bq-claude-slack-agent/src/main/java/org/example/gcp/slack/claude/common/Utils.java
  examples/mcptoolbox-bq-claude-slack-agent/src/main/java/org/example/gcp/slack/claude/config/Routes.java
  examples/mcptoolbox-bq-claude-slack-agent/src/main/java/org/example/gcp/slack/claude/config/SlackApp.java
  examples/mcptoolbox-bq-claude-slack-agent/src/main/java/org/example/gcp/slack/claude/config/SpringAiConfig.java
  examples/mcptoolbox-bq-claude-slack-agent/src/main/java/org/example/gcp/slack/claude/handlers/ClaudeChat.java
  examples/mcptoolbox-bq-claude-slack-agent/src/main/java/org/example/gcp/slack/claude/handlers/SlackEvent.java
  examples/mcptoolbox-bq-claude-slack-agent/src/main/java/org/example/gcp/slack/claude/handlers/SlackOperations.java
  examples/mcptoolbox-bq-claude-slack-agent/src/main/java/org/example/gcp/slack/claude/handlers/SlackResource.java
  examples/mcptoolbox-bq-claude-slack-agent/src/main/resources/application.yaml
  examples/mcptoolbox-bq-claude-slack-agent/src/main/resources/logback-spring.xml
  helpers/exclusion_list.txt
Labels: size/XXL

#1528 Update README.md fixing images
  examples/mcptoolbox-bq-claude-slack-agent/README.md
Labels: size/XS
