Repository GoogleCloudPlatform/professional-services, pull requests merged in 2025-02, with the labels that each got.

#1440 Update pom.xml
  examples/dataflow-dlp-hash-pipeline/pom.xml
Labels: size/XS

#1442 Update client libraries in Dataflow XML example
  examples/dataflow-xmlio-to-bq/pom.xml
Labels: size/S

#1445 feat: organize readme structure
  tools/gcpviz/README.md
Labels: size/M

#1448 Resolving Issue1447, out of date dependencies
  tools/secret-manager-helper/pom.xml
  tools/secret-manager-helper/src/main/java/com/google/cloud/secrethelper/SecretLookup.java
  tools/secret-manager-helper/src/main/java/com/google/cloud/secrethelper/SecretLookupToFile.java
  tools/secret-manager-helper/src/main/java/com/google/cloud/secrethelper/SecretManagerPropertiesExample.java
  tools/secret-manager-helper/src/main/java/com/google/cloud/secrethelper/SecretManagerStringSubstitutor.java
Labels: size/S

#1446 Setup service extensions(callout) with GCP Application Load Balancer (EXTERNAL_MANAGED)
  examples/gclb-callouts/README.md
  examples/gclb-callouts/manifests/deploy.yaml
  examples/gclb-callouts/manifests/service-extension.yaml
  examples/gclb-callouts/service-extensions/extproc/cmd/main.go
  examples/gclb-callouts/service-extensions/extproc/config/Dockerfile
  examples/gclb-callouts/service-extensions/extproc/internal/server/callout_server.go
  examples/gclb-callouts/service-extensions/extproc/internal/server/callout_server_test.go
  examples/gclb-callouts/service-extensions/extproc/update_header/update_header.go
  examples/gclb-callouts/service-extensions/extproc/update_header/update_header_test.go
  examples/gclb-callouts/service-extensions/go.mod
  examples/gclb-callouts/service-extensions/go.sum
  examples/gclb-callouts/terraform/main.tf
Labels: size/XXL

#1452 Dataproc cluster write to Spanner using Apache Spark Scala
  .gitignore
  README.md
  examples/dataproc-spanner/mutations/LICENSE
  examples/dataproc-spanner/mutations/README.md
  examples/dataproc-spanner/mutations/build.sbt
  examples/dataproc-spanner/mutations/project/build.properties
  examples/dataproc-spanner/mutations/src/main/META-INF/MANIFEST.MF
  examples/dataproc-spanner/mutations/src/main/scala/SpannerMutations.scala
  examples/dataproc-spanner/mutations/src/main/scala/SpannerUtils.scala
  examples/dataproc-spanner/mutations/src/main/scala/SparkPipelineExample.scala
  examples/dataproc-spanner/mutations/src/main/scala/main.scala
Labels: size/XL

#1453 update spanner mutation code
  examples/dataproc-spanner/mutations/src/main/scala/SpannerUtils.scala
  examples/dataproc-spanner/mutations/src/main/scala/SparkPipelineExample.scala
Labels: size/M

#1454 Adds an example in Scala of writing to Cloud Spanner using Apache Spark on Cloud Dataproc.
  examples/dataproc-spanner/jdbc/README.md
  examples/dataproc-spanner/jdbc/build.properties
  examples/dataproc-spanner/jdbc/build.sbt
  examples/dataproc-spanner/jdbc/project/build.properties
  examples/dataproc-spanner/jdbc/src/main/META-INF/MANIFEST.MF
  examples/dataproc-spanner/jdbc/src/main/scala/Main.scala
  examples/dataproc-spanner/jdbc/src/main/scala/Pipeline.scala
  examples/dataproc-spanner/jdbc/src/main/scala/SpannerJdbcDialect.scala
Labels: size/L
